import { Languages } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { adminTranslationSource, adminTranslationT } from "../../adminTranslationI18n";
import { adminSystemT } from "../../adminSystemI18n";
import { useAuth, type TranslationReviewItem, type TranslationSetReview } from "../../auth";
import type { UiLocale } from "../../types";
import { AdminLayout } from "./AdminLayout";

export function TranslationReviewPage({locale,onSiteHome}:{locale:UiLocale;onSiteHome:()=>void}){
  const auth=useAuth(),t=(key:Parameters<typeof adminTranslationT>[1])=>adminTranslationT(locale,key),[items,setItems]=useState<TranslationReviewItem[]>([]),[sets,setSets]=useState<TranslationSetReview[]>([]),[query,setQuery]=useState(""),[appliedQuery,setAppliedQuery]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),loadRequestId=useRef(0);
  const load=()=>{if(!auth.user?.isAdmin)return;const requestId=++loadRequestId.current;setBusy(true);void auth.adminGetTranslations(appliedQuery).then(result=>{if(requestId!==loadRequestId.current)return;setItems(result.translations);setSets(result.translationSets);setError("");}).catch(()=>{if(requestId===loadRequestId.current)setError(t("loadError"));}).finally(()=>{if(requestId===loadRequestId.current)setBusy(false);});};
  useEffect(()=>{const timeout=window.setTimeout(()=>setAppliedQuery(query.trim()),300);return()=>window.clearTimeout(timeout);},[query]);
  useEffect(load,[auth.user?.isAdmin,appliedQuery]);
  const groups=useMemo(()=>{const grouped:Record<string,{lessonId:string;lessonTitle:string;languageCode:string;languageName:string;count:number;canApproveLesson:boolean;approvalBlockReason:TranslationSetReview["approvalBlockReason"]}>={};for(const set of sets){const key=`${set.lessonId}:${set.languageCode}`;grouped[key]={lessonId:set.lessonId,lessonTitle:set.lessonTitle,languageCode:set.languageCode,languageName:set.languageName,count:0,canApproveLesson:set.canApproveLesson,approvalBlockReason:set.approvalBlockReason};}for(const item of items){const key=`${item.lessonId}:${item.languageCode}`;grouped[key]??={lessonId:item.lessonId,lessonTitle:item.lessonTitle,languageCode:item.languageCode,languageName:item.languageName,count:0,canApproveLesson:false,approvalBlockReason:"translation_set_incomplete"};grouped[key].count+=1;}return Object.values(grouped);},[items,sets]);
  if(auth.loading)return <AdminLayout locale={locale} title={t("title")} onSiteHome={onSiteHome}><div className="admin-state">{adminSystemT(locale,"loading")}</div></AdminLayout>;
  if(!auth.user?.isAdmin)return <AdminLayout locale={locale} title={t("title")} onSiteHome={onSiteHome}><div className="admin-state">{adminSystemT(locale,"adminRequired")}</div></AdminLayout>;
  const review=async(item:TranslationReviewItem,action:"approve"|"reject")=>{const reason=action==="reject"?window.prompt(`${t("reject")}:`)??"":"";setBusy(true);setError("");try{await auth.adminReviewTranslation(item.id,action,reason);load();}catch(reasonValue){setError(reasonValue instanceof Error?reasonValue.message:t("loadError"));setBusy(false);}};
  const approvalMessage=(reason:(typeof groups)[number]["approvalBlockReason"])=>(reason==="lesson_inactive"?t("lessonInactive"):reason==="language_inactive"?t("languageInactive"):reason==="translation_set_empty"?t("emptySet"):reason==="translation_set_rejected"?t("rejectedSet"):t("incomplete"));
  const approveLesson=async(group:(typeof groups)[number])=>{if(!group.canApproveLesson)return;setBusy(true);setError("");try{await auth.adminApproveLessonTranslations(group.lessonId,group.languageCode);load();}catch(reason){const code=reason instanceof Error?reason.message:"";setError(code.includes("lesson_inactive")?t("lessonInactive"):code.includes("language_inactive")?t("languageInactive"):code.includes("translation_set_empty")?t("emptySet"):code.includes("translation_set_rejected")?t("rejectedSet"):code.includes("translation_set_incomplete")?t("incomplete"):code||t("loadError"));setBusy(false);}};
  return <AdminLayout locale={locale} title={t("title")} onSiteHome={onSiteHome}><p className="admin-dashboard-intro">{t("description")}</p><div className="admin-filters"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t("search")} aria-label={t("search")}/></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="translation-review-groups">{groups.map(group=>{const approvalTitle=group.canApproveLesson?t("approveLesson"):approvalMessage(group.approvalBlockReason);return <article key={`${group.lessonId}:${group.languageCode}`}><div><Languages size={18}/><span><strong>{group.lessonTitle}</strong><small>{group.languageName} · {group.count} {t("pending")}</small></span></div><span className="approval-button-wrap" title={approvalTitle}><button disabled={busy||!group.canApproveLesson} aria-label={approvalTitle} className="primary-button" type="button" onClick={()=>void approveLesson(group)}>{t("approveLesson")}</button></span></article>;})}</div><div className="translation-review-list">{items.map(item=>{const source=adminTranslationSource(locale,item.source);return <article key={item.id}><header><span>{item.lessonTitle} · #{item.position} · {item.languageName}</span><small>{source} · {item.submittedBy??source}</small></header><div className="translation-review-comparison"><p>{item.transcript}</p><p>{item.text}</p></div><footer><button disabled={busy} type="button" onClick={()=>void review(item,"reject")}>{t("reject")}</button><button disabled={busy} className="primary-button" type="button" onClick={()=>void review(item,"approve")}>{t("approve")}</button></footer></article>;})}{!busy&&!items.length&&!groups.length&&<div className="admin-state">{t("empty")}</div>}</div></AdminLayout>;
}
