import { BookCheck, ChevronLeft, ChevronRight, Clock3, Languages, MessageSquare, Search, ShieldBan, ShieldCheck, Trophy, UserRoundCog, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { adminUsersT } from "../../adminUsersI18n";
import { adminSystemT } from "../../adminSystemI18n";
import { useAuth, type AdminUserSummary } from "../../auth";
import type { UiLocale } from "../../types";
import { AdminLayout } from "./AdminLayout";

const localeTags:Record<UiLocale,string>={vi:"vi-VN",en:"en-US",zh:"zh-CN",ja:"ja-JP"};
type UserStatus="all"|"active"|"blocked";

export function UserManagementPage({locale,onSiteHome}:{locale:UiLocale;onSiteHome:()=>void}){
  const auth=useAuth(),t=(key:Parameters<typeof adminUsersT>[1],values?:Record<string,string|number>)=>adminUsersT(locale,key,values);
  const [items,setItems]=useState<AdminUserSummary[]>([]),[draft,setDraft]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState<UserStatus>("all"),[page,setPage]=useState(1),[total,setTotal]=useState(0);
  const [loading,setLoading]=useState(false),[error,setError]=useState<"load"|"action">(),[target,setTarget]=useState<AdminUserSummary>(),[reason,setReason]=useState(""),[saving,setSaving]=useState(false);
  const moderationDialogRef=useRef<HTMLDialogElement>(null);
  const pages=Math.max(1,Math.ceil(total/25));
  useEffect(()=>{if(!auth.user?.isAdmin)return;let active=true;setLoading(true);setError(undefined);void auth.adminGetUsers({query,status,page}).then(result=>{if(!active)return;setItems(result.users);setTotal(result.total);}).catch(()=>{if(active)setError("load");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[auth.user?.isAdmin,query,status,page]);
  useEffect(()=>{const dialog=moderationDialogRef.current;if(!target||!dialog)return;if(!dialog.open)dialog.showModal();return()=>{if(dialog.open)dialog.close();};},[target]);
  const applySearch=(event:React.FormEvent)=>{event.preventDefault();setPage(1);setQuery(draft.trim());};
  const openModeration=(user:AdminUserSummary)=>{setTarget(user);setReason("");setError(undefined);};
  const moderate=async()=>{if(!target||reason.trim().length<3||saving)return;setSaving(true);setError(undefined);try{await auth.adminModerateUser(target.id,target.isBlocked?"unblock":"block",reason.trim());setTarget(undefined);setReason("");const result=await auth.adminGetUsers({query,status,page});setItems(result.users);setTotal(result.total);}catch{setError("action");}finally{setSaving(false);}};
  if(auth.loading)return <AdminLayout locale={locale} title={t("title")} onSiteHome={onSiteHome}><div className="admin-state">{adminSystemT(locale,"loading")}</div></AdminLayout>;
  if(!auth.user?.isAdmin)return <AdminLayout locale={locale} title={t("title")} onSiteHome={onSiteHome}><div className="admin-state">{adminSystemT(locale,"adminRequired")}</div></AdminLayout>;
  return <AdminLayout locale={locale} title={t("title")} onSiteHome={onSiteHome}>
    <p className="admin-dashboard-intro">{t("description")}</p>
    <div className="admin-user-toolbar"><form onSubmit={applySearch}><Search size={17}/><input value={draft} maxLength={100} placeholder={t("search")} aria-label={t("search")} onChange={event=>setDraft(event.target.value)}/><button type="submit"><Search size={15}/><span>{t("search")}</span></button></form><label><span className="sr-only">{t("status")}</span><select value={status} onChange={event=>{setStatus(event.target.value as UserStatus);setPage(1);}}><option value="all">{t("all")}</option><option value="active">{t("active")}</option><option value="blocked">{t("blocked")}</option></select></label><strong>{t("total",{count:total})}</strong></div>
    {error==="load"&&<p className="admin-form-message error" role="alert">{t("loadError")}</p>}
    <div className="admin-user-list" aria-busy={loading}>{items.map(user=><UserCard key={user.id} user={user} locale={locale} currentUserId={auth.user!.id} onModerate={openModeration}/>)}</div>
    {!loading&&!items.length&&<div className="admin-state">{t("empty")}</div>}
    {total>25&&<nav className="admin-user-pagination" aria-label={t("page",{page,pages})}><button type="button" disabled={loading||page<=1} onClick={()=>setPage(value=>value-1)}><ChevronLeft size={16}/>{t("previous")}</button><span>{t("page",{page,pages})}</span><button type="button" disabled={loading||page>=pages} onClick={()=>setPage(value=>value+1)}>{t("next")}<ChevronRight size={16}/></button></nav>}
    {target&&<dialog ref={moderationDialogRef} className="admin-user-dialog" aria-labelledby="admin-user-dialog-title" onCancel={event=>{event.preventDefault();if(!saving)setTarget(undefined);}}><button className="admin-user-dialog-close" type="button" disabled={saving} aria-label={t("cancel")} onClick={()=>setTarget(undefined)}><X size={18}/></button><span className={target.isBlocked?"unblock":"block"}>{target.isBlocked?<ShieldCheck size={22}/>:<ShieldBan size={22}/>}</span><h2 id="admin-user-dialog-title">{t(target.isBlocked?"unblockTitle":"blockTitle")}</h2><p><b>{target.displayName}</b><small>{target.email}</small></p><div className="admin-user-dialog-help">{t(target.isBlocked?"unblockHelp":"blockHelp")}</div><label>{t("reason")}<textarea autoFocus minLength={3} maxLength={500} value={reason} placeholder={t("reasonPlaceholder")} onChange={event=>setReason(event.target.value)}/><small>{reason.trim().length}/500</small></label>{error==="action"&&<p className="admin-form-message error" role="alert">{t("actionError")}</p>}<footer><button type="button" disabled={saving} onClick={()=>setTarget(undefined)}>{t("cancel")}</button><button type="button" className={target.isBlocked?"primary-button":"danger-button"} disabled={saving||reason.trim().length<3} onClick={()=>void moderate()}>{saving?t("working"):t(target.isBlocked?"confirmUnblock":"confirmBlock")}</button></footer></dialog>}
  </AdminLayout>;
}

function UserCard({user,locale,currentUserId,onModerate}:{user:AdminUserSummary;locale:UiLocale;currentUserId:string;onModerate:(user:AdminUserSummary)=>void}){
  const t=(key:Parameters<typeof adminUsersT>[1],values?:Record<string,string|number>)=>adminUsersT(locale,key,values),date=new Intl.DateTimeFormat(localeTags[locale],{dateStyle:"medium"}),dateTime=new Intl.DateTimeFormat(localeTags[locale],{dateStyle:"medium",timeStyle:"short"}),protectedUser=user.isAdmin||user.id===currentUserId;
  const formatEpoch=(value:number|null)=>value?dateTime.format(new Date(value*1000)):t("never"),formatDuration=(seconds:number)=>seconds<3600?`${Math.round(seconds/60)}m`:`${Math.floor(seconds/3600)}h ${Math.round(seconds%3600/60)}m`;
  return <article className={`admin-user-card${user.isBlocked?" blocked":""}`}><header><span className="admin-user-avatar">{user.avatarUrl?<img src={user.avatarUrl} alt="" referrerPolicy="no-referrer"/>:user.displayName.slice(0,1).toUpperCase()}</span><div><strong>{user.displayName}</strong><small>{user.email}</small></div><span className={`admin-user-status ${user.isBlocked?"blocked":"active"}`}>{user.isBlocked?<ShieldBan size={13}/>:<ShieldCheck size={13}/>} {t(user.isBlocked?"blocked":"active")}</span>{user.isAdmin&&<span className="admin-user-status admin"><UserRoundCog size={13}/>{t("admin")}</span>}</header><dl className="admin-user-dates"><div><dt>{t("joined")}</dt><dd>{date.format(new Date(user.createdAt*1000))}</dd></div><div><dt>{t("lastActive")}</dt><dd>{formatEpoch(user.lastSeenAt)}</dd></div><div><dt>{t("leaderboard")}</dt><dd><Trophy size={13}/>{t(user.leaderboardVisible?"visible":"hidden")}</dd></div></dl><div className="admin-user-metrics"><span><MessageSquare size={16}/><b>{user.commentCount}</b><small>{t("comments")}</small></span><span><BookCheck size={16}/><b>{user.completedLessonCount}</b><small>{t("lessons")}</small></span><span><Clock3 size={16}/><b>{formatDuration(user.studySeconds30d)}</b><small>{t("studyTime")}</small></span><span><Languages size={16}/><b>{user.approvedTranslationCount}</b><small>{t("translations")}</small></span></div>{user.isBlocked&&<div className="admin-user-block-note"><b>{t("blockedOn",{date:dateTime.format(new Date(user.blockedAt!))})}</b>{user.blockedByName&&<span>{t("blockedBy",{name:user.blockedByName})}</span>}<p>{user.blockReason}</p></div>}<footer><button type="button" className={user.isBlocked?"primary-button":"danger-button"} disabled={protectedUser} title={protectedUser?t("protected"):undefined} onClick={()=>onModerate(user)}>{protectedUser?t("protected"):t(user.isBlocked?"unblock":"block")}</button></footer></article>;
}
