import { neon } from "@neondatabase/serverless";
import { lessons } from "../src/data/lessons";
import { answerScore } from "../src/lib/text";
import { normalizeListeningPreferences, parseListeningPreferences } from "../src/lib/listeningPreferences";
import { routeListening, serveRobots, serveSeoLesson, serveSitemap } from "./listening";

const SESSION_COOKIE = "__Host-echotype_session";
const OAUTH_COOKIE = "__Host-echotype_oauth_state";
const SESSION_SECONDS = 60 * 60 * 24 * 30;
const OAUTH_SECONDS = 60 * 10;
const MAX_JSON_BYTES = 16 * 1024;
type SessionUser = { id:string; email:string; display_name:string; avatar_url:string|null; leaderboard_visible:boolean; listening_preferences:unknown; preferred_translation_language_code:string|null; csrf_token:string; expires_at:number };
type OAuthAttempt = { code_verifier:string; return_to:string; expires_at:number };
type GoogleTokenResponse = { access_token?:string; error?:string };
type GoogleUser = { sub?:string; email?:string; email_verified?:boolean; name?:string; picture?:string };
type NeonSql = ReturnType<typeof neon>;
type TransactionQuery = ReturnType<NeonSql>;
type TransactionSql = NeonSql & { transaction(queries: TransactionQuery[]): Promise<unknown[]> };
// @neondatabase/serverless 1.1.0 omits its declarations from package exports,
// so TypeScript infers only the callback overload although runtime also accepts query arrays.
const db = (env:Env) => neon(env.DATABASE_URL) as TransactionSql;

export default { async fetch(request,env,ctx):Promise<Response> { try { const url=new URL(request.url); let response: Response; if (url.pathname === "/sitemap.xml") response = await serveSitemap(env, request); else if (url.pathname === "/robots.txt") response = serveRobots(request); else if (url.pathname.startsWith("/lessons/")) response = await serveSeoLesson(request, env, url); else response = url.pathname.startsWith("/api/")||url.pathname.startsWith("/auth/") ? await routeApi(request,env,ctx,url) : await env.ASSETS.fetch(request); return withSecurityHeaders(response); } catch(error) { console.error(JSON.stringify({event:"request_error",message:error instanceof Error?error.message:"unknown"})); return error instanceof HttpError?json({error:error.code},error.status):json({error:"internal_error"},500); } } } satisfies ExportedHandler<Env>;
async function routeApi(req:Request,env:Env,ctx:ExecutionContext,url:URL):Promise<Response> { if(url.pathname.startsWith("/api/listening/")){const session=await requireSession(req,env,ctx),mutationValid=req.method==="GET"||req.method==="HEAD"?true:!!session&&await validMutation(req,env,session);return routeListening(req,env,url,session,mutationValid,ctx);} if(req.method==="GET"&&url.pathname==="/api/auth/google")return startGoogleAuth(env,ctx,url); if(req.method==="GET"&&url.pathname==="/api/auth/google/callback")return finishGoogleAuth(req,env,ctx,url); if(req.method==="GET"&&url.pathname==="/api/me")return getMe(req,env,ctx); if(req.method==="PATCH"&&url.pathname==="/api/me")return updateMe(req,env,ctx); if(req.method==="PATCH"&&url.pathname==="/api/listening-preferences")return updateListeningPreferences(req,env,ctx); if(req.method==="POST"&&url.pathname==="/api/logout")return logout(req,env,ctx); if(req.method==="GET"&&url.pathname==="/api/progress")return getProgress(req,env,ctx); if(req.method==="POST"&&url.pathname==="/api/progress/import")return importProgress(req,env,ctx); if(req.method==="POST"&&url.pathname==="/api/progress/events")return recordProgress(req,env,ctx); if(req.method==="GET"&&url.pathname==="/api/leaderboard")return getLeaderboard(req,env,ctx,url); return json({error:"not_found"},404); }
async function startGoogleAuth(env:Env,ctx:ExecutionContext,url:URL) { if(!env.GOOGLE_CLIENT_ID||env.GOOGLE_CLIENT_ID==="set-with-dashboard-or-environment")return json({error:"oauth_not_configured"},503); const state=randomToken(32),verifier=randomToken(64),now=epochSeconds(),requested=url.searchParams.get("returnTo")??"#/",returnTo=/^#\/(?:[\w\-/]*)?$/.test(requested)?requested:"#/"; const sql=db(env),stateHash=await sha256Hex(state); await sql`INSERT INTO oauth_attempts(state_hash,code_verifier,return_to,created_at,expires_at) VALUES(${stateHash},${verifier},${returnTo},${now},${now+OAUTH_SECONDS})`; ctx.waitUntil(sql`DELETE FROM oauth_attempts WHERE expires_at<${now}`.catch(()=>undefined)); const target=new URL("https://accounts.google.com/o/oauth2/v2/auth"); target.search=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,redirect_uri:`${env.APP_ORIGIN}/api/auth/google/callback`,response_type:"code",scope:"openid email profile",state,code_challenge:await sha256Base64Url(verifier),code_challenge_method:"S256",prompt:"select_account"}).toString(); return redirect(target.toString(),serializeCookie(OAUTH_COOKIE,state,OAUTH_SECONDS)); }
async function finishGoogleAuth(req:Request,env:Env,ctx:ExecutionContext,url:URL) { const code=url.searchParams.get("code"),state=url.searchParams.get("state"),cookie=parseCookies(req.headers.get("Cookie"))[OAUTH_COOKIE]; if(!code||!state||!cookie||!(await safeEqual(state,cookie)))return oauthFailure(env,"invalid_state"); const sql=db(env),hash=await sha256Hex(state),rows=await sql`SELECT code_verifier,return_to,expires_at::int AS expires_at FROM oauth_attempts WHERE state_hash=${hash}`,attempt=rows[0] as OAuthAttempt|undefined; if(!attempt||attempt.expires_at<epochSeconds())return oauthFailure(env,"expired_state"); await sql`DELETE FROM oauth_attempts WHERE state_hash=${hash}`; const tokenResponse=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,redirect_uri:`${env.APP_ORIGIN}/api/auth/google/callback`,grant_type:"authorization_code",code_verifier:attempt.code_verifier})}); if(!tokenResponse.ok)return oauthFailure(env,"token_exchange_failed"); const token=await tokenResponse.json<GoogleTokenResponse>(); if(!token.access_token)return oauthFailure(env,token.error??"missing_access_token"); const userResponse=await fetch("https://openidconnect.googleapis.com/v1/userinfo",{headers:{Authorization:`Bearer ${token.access_token}`,Accept:"application/json"}}); if(!userResponse.ok)return oauthFailure(env,"userinfo_failed"); const user=await userResponse.json<GoogleUser>(); if(!user.sub||!user.email||user.email_verified!==true)return oauthFailure(env,"unverified_account"); const now=epochSeconds(),existingRows=await sql`SELECT id,display_name FROM users WHERE google_subject=${user.sub}`,existing=existingRows[0] as {id:string;display_name:string}|undefined,userId=existing?.id??crypto.randomUUID(),name=cleanDisplayName(user.name??user.email.split("@")[0])??"Learner"; await sql`INSERT INTO users(id,google_subject,email,display_name,avatar_url,created_at,updated_at) VALUES(${userId},${user.sub},${user.email},${existing?.display_name??name},${user.picture??null},${now},${now}) ON CONFLICT(google_subject) DO UPDATE SET email=EXCLUDED.email,avatar_url=EXCLUDED.avatar_url,updated_at=EXCLUDED.updated_at`; const sessionToken=randomToken(48),csrf=randomToken(32); await sql`INSERT INTO sessions(token_hash,user_id,csrf_token,created_at,expires_at,last_seen_at) VALUES(${await sha256Hex(sessionToken)},${userId},${csrf},${now},${now+SESSION_SECONDS},${now})`; ctx.waitUntil(sql`DELETE FROM sessions WHERE expires_at<${now}`.catch(()=>undefined)); const headers=new Headers({Location:`${env.APP_ORIGIN}/${attempt.return_to}`,"Cache-Control":"no-store"}); headers.append("Set-Cookie",serializeCookie(SESSION_COOKIE,sessionToken,SESSION_SECONDS)); headers.append("Set-Cookie",serializeCookie(OAUTH_COOKIE,"",0)); return new Response(null,{status:302,headers}); }
async function getMe(req:Request,env:Env,ctx:ExecutionContext){const s=await requireSession(req,env,ctx);return s?json({user:{...publicUser(s),isAdmin:isAdminEmail(env,s.email)},csrfToken:s.csrf_token}):json({user:null});}
async function updateMe(req:Request,env:Env,ctx:ExecutionContext){const s=await requireSession(req,env,ctx);if(!s)return json({error:"unauthorized"},401);if(!(await validMutation(req,env,s)))return json({error:"invalid_csrf"},403);const body=await readJson<{displayName?:unknown;leaderboardVisible?:unknown}>(req),name=typeof body.displayName==="string"?cleanDisplayName(body.displayName):null;if(!name)return json({error:"invalid_display_name"},422);const visible=typeof body.leaderboardVisible==="boolean"?body.leaderboardVisible:s.leaderboard_visible;await db(env)`UPDATE users SET display_name=${name},leaderboard_visible=${visible},updated_at=${epochSeconds()} WHERE id=${s.id}`;return json({user:{...publicUser(s),displayName:name,leaderboardVisible:visible,isAdmin:isAdminEmail(env,s.email)}});}
async function updateListeningPreferences(req:Request,env:Env,ctx:ExecutionContext){const s=await requireSession(req,env,ctx);if(!s)return json({error:"unauthorized"},401);if(!(await validMutation(req,env,s)))return json({error:"invalid_csrf"},403);const preferences=parseListeningPreferences(await readJson<unknown>(req));if(!preferences)return json({error:"invalid_listening_preferences"},422);await db(env)`UPDATE users SET listening_preferences=${JSON.stringify(preferences)}::jsonb,updated_at=${epochSeconds()} WHERE id=${s.id}`;return json({preferences});}
async function logout(req:Request,env:Env,ctx:ExecutionContext){const s=await requireSession(req,env,ctx);if(s&&!(await validMutation(req,env,s)))return json({error:"invalid_csrf"},403);const token=parseCookies(req.headers.get("Cookie"))[SESSION_COOKIE];if(token)await db(env)`DELETE FROM sessions WHERE token_hash=${await sha256Hex(token)}`;const response=json({ok:true});response.headers.append("Set-Cookie",serializeCookie(SESSION_COOKIE,"",0));return response;}
async function getProgress(req:Request,env:Env,ctx:ExecutionContext){const s=await requireSession(req,env,ctx);if(!s)return json({error:"unauthorized"},401);return json({progress:await db(env)`SELECT lesson_id,language,sentence_index,best_score,attempts,completed,updated_at::int AS updated_at FROM lesson_progress WHERE user_id=${s.id} ORDER BY updated_at DESC LIMIT 5000`});}
async function recordProgress(req:Request,env:Env,ctx:ExecutionContext){const s=await requireSession(req,env,ctx);if(!s)return json({error:"unauthorized"},401);if(!(await validMutation(req,env,s)))return json({error:"invalid_csrf"},403);const b=await readJson<Record<string,unknown>>(req),eventId=typeof b.eventId==="string"&&/^[0-9a-f-]{36}$/i.test(b.eventId)?b.eventId:null,lessonId=typeof b.lessonId==="string"&&/^[\w-]{1,80}$/.test(b.lessonId)?b.lessonId:null,language=b.language==="en"||b.language==="zh"||b.language==="ja"?b.language:null,index=Number.isInteger(b.sentenceIndex)&&Number(b.sentenceIndex)>=0&&Number(b.sentenceIndex)<=500?Number(b.sentenceIndex):null,answer=typeof b.typedAnswer==="string"&&[...b.typedAnswer].length<=1000?b.typedAnswer:null,duration=Number.isInteger(b.durationSeconds)?Math.min(300,Math.max(1,Number(b.durationSeconds))):null,lesson=lessons.find(x=>x.id===lessonId&&x.language===language);if(!eventId||!lessonId||!language||index===null||answer===null||duration===null||!lesson?.sentences[index])return json({error:"invalid_progress_event"},422);const now=epochSeconds(),score=answerScore(lesson.sentences[index].text,answer),completed=score>=80,day=new Date(now*1000).toISOString().slice(0,10),sql=db(env),queries:TransactionQuery[]=[sql`INSERT INTO progress_events(id,user_id,lesson_id,language,sentence_index,score,duration_seconds,completed,occurred_at,activity_day) VALUES(${eventId},${s.id},${lessonId},${language},${index},${score},${duration},${completed},${now},${day}) ON CONFLICT DO NOTHING`,sql`INSERT INTO lesson_progress(user_id,lesson_id,language,sentence_index,best_score,attempts,completed,updated_at) VALUES(${s.id},${lessonId},${language},${index},${score},1,${completed},${now}) ON CONFLICT(user_id,lesson_id,sentence_index) DO UPDATE SET best_score=GREATEST(lesson_progress.best_score,EXCLUDED.best_score),attempts=lesson_progress.attempts+1,completed=lesson_progress.completed OR EXCLUDED.completed,updated_at=EXCLUDED.updated_at`];await sql.transaction(queries);return json({ok:true,countedForLeaderboard:completed});}
async function importProgress(req:Request,env:Env,ctx:ExecutionContext){const s=await requireSession(req,env,ctx);if(!s)return json({error:"unauthorized"},401);if(!(await validMutation(req,env,s)))return json({error:"invalid_csrf"},403);const body=await readJson<{items?:unknown}>(req);if(!Array.isArray(body.items)||body.items.length>500)return json({error:"invalid_import"},422);const sql=db(env),now=epochSeconds(),queries:TransactionQuery[]=[];let imported=0;for(const candidate of body.items as unknown[]){if(!candidate||typeof candidate!=="object")continue;const i=candidate as Record<string,unknown>,lessonId=typeof i.lessonId==="string"&&/^[\w-]{1,80}$/.test(i.lessonId)?i.lessonId:null,language=i.language==="en"||i.language==="zh"||i.language==="ja"?i.language:null,index=Number.isInteger(i.sentenceIndex)&&Number(i.sentenceIndex)>=0&&Number(i.sentenceIndex)<=500?Number(i.sentenceIndex):null;if(!lessonId||!language||index===null||!lessons.find(x=>x.id===lessonId&&x.language===language)?.sentences[index])continue;queries.push(sql`INSERT INTO lesson_progress(user_id,lesson_id,language,sentence_index,best_score,attempts,completed,updated_at) VALUES(${s.id},${lessonId},${language},${index},100,1,true,${now}) ON CONFLICT(user_id,lesson_id,language,sentence_index) DO UPDATE SET best_score=GREATEST(lesson_progress.best_score,100),completed=true,updated_at=GREATEST(lesson_progress.updated_at,EXCLUDED.updated_at)`);imported++;}if(queries.length)await sql.transaction(queries);return json({ok:true,imported});}
async function getLeaderboard(req:Request,env:Env,ctx:ExecutionContext,url:URL){const s=await requireSession(req,env,ctx),period=url.searchParams.get("period")??"week";if(!(["day","week","month","year"] as const).includes(period as never))return json({error:"invalid_period"},422);const start=periodStart(period as "day"|"week"|"month"|"year"),rows=await db(env)`WITH totals AS(SELECT pe.user_id,COUNT(*)::int AS completed_sentences,SUM(LEAST(pe.duration_seconds,120))::int AS active_seconds,(COUNT(*)*10+FLOOR(SUM(LEAST(pe.duration_seconds,120))/60.0))::int AS points FROM progress_events pe WHERE pe.completed=true AND pe.occurred_at>=${start} GROUP BY pe.user_id),ranked AS(SELECT ROW_NUMBER() OVER(ORDER BY totals.points DESC,totals.active_seconds DESC,u.created_at ASC)::int AS rank,u.id AS user_id,u.display_name,u.avatar_url,totals.completed_sentences,totals.active_seconds,totals.points FROM totals JOIN users u ON u.id=totals.user_id WHERE u.leaderboard_visible=true) SELECT * FROM ranked WHERE rank<=50 OR user_id=${s?.id??""} ORDER BY rank ASC`;return json({period,startsAt:new Date(start*1000).toISOString(),leaders:rows,currentUserId:s?.id??null});}
async function requireSession(req:Request,env:Env,ctx:ExecutionContext):Promise<SessionUser|null>{const token=parseCookies(req.headers.get("Cookie"))[SESSION_COOKIE];if(!token)return null;const now=epochSeconds(),hash=await sha256Hex(token),rows=await db(env)`SELECT u.id,u.email,u.display_name,u.avatar_url,u.leaderboard_visible,u.listening_preferences,u.preferred_translation_language_code,s.csrf_token,s.expires_at::int AS expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=${hash} AND s.expires_at>${now}`,s=rows[0] as SessionUser|undefined;if(!s)return null;ctx.waitUntil(db(env)`UPDATE sessions SET last_seen_at=${now} WHERE token_hash=${hash} AND last_seen_at<${now-3600}`.catch(()=>undefined));return s;}
async function validMutation(req:Request,env:Env,s:SessionUser){const origin=req.headers.get("Origin"),csrf=req.headers.get("X-CSRF-Token");return origin===env.APP_ORIGIN&&!!csrf&&await safeEqual(csrf,s.csrf_token);}
function publicUser(s:SessionUser){return{id:s.id,email:s.email,displayName:s.display_name,avatarUrl:s.avatar_url,leaderboardVisible:s.leaderboard_visible,listeningPreferences:normalizeListeningPreferences(s.listening_preferences),preferredTranslationLanguage:s.preferred_translation_language_code??"vi"};}
function isAdminEmail(env:Env,email:string){return env.ADMIN_EMAILS.split(",").map(item=>item.trim().toLocaleLowerCase()).filter(Boolean).includes(email.toLocaleLowerCase());}
function cleanDisplayName(value:string){const cleaned=value.normalize("NFKC").replace(/\s+/g," ").trim(),length=[...cleaned].length;return length>=2&&length<=40&&!/[\p{C}<>]/u.test(cleaned)?cleaned:null;}
function periodStart(period:"day"|"week"|"month"|"year",now=new Date()){const start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));if(period==="week")start.setUTCDate(start.getUTCDate()-((start.getUTCDay()+6)%7));if(period==="month")start.setUTCDate(1);if(period==="year"){start.setUTCMonth(0);start.setUTCDate(1);}return Math.floor(start.getTime()/1000);}
async function readJson<T>(req:Request):Promise<T>{if(!req.body)throw new HttpError(400,"missing_body");const reader=req.body.getReader(),chunks:Uint8Array[]=[];let size=0;while(true){const{value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>MAX_JSON_BYTES){await reader.cancel();throw new HttpError(413,"body_too_large");}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}try{return JSON.parse(new TextDecoder().decode(bytes)) as T;}catch{throw new HttpError(400,"invalid_json");}}
class HttpError extends Error{constructor(readonly status:number,readonly code:string){super(code);}}
function parseCookies(header:string|null){if(!header)return{};return Object.fromEntries(header.split(";").map(x=>x.trim().split(/=(.*)/s).slice(0,2)).filter(([key])=>key).map(([key,value])=>[key,decodeURIComponent(value??"")]));}
function serializeCookie(name:string,value:string,maxAge:number){return`${name}=${encodeURIComponent(value)}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`;}
function randomToken(bytes:number){const buffer=new Uint8Array(bytes);crypto.getRandomValues(buffer);return base64Url(buffer);}
function base64Url(bytes:Uint8Array){let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
async function sha256Hex(value:string){const digest=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)));return[...digest].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
async function sha256Base64Url(value:string){return base64Url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))));}
async function safeEqual(left:string,right:string){const[a,b]=await Promise.all([crypto.subtle.digest("SHA-256",new TextEncoder().encode(left)),crypto.subtle.digest("SHA-256",new TextEncoder().encode(right))]);return crypto.subtle.timingSafeEqual(a,b);}
function epochSeconds(){return Math.floor(Date.now()/1000);}
function json(body:unknown,status=200){return Response.json(body,{status,headers:{"Cache-Control":"no-store","Content-Type":"application/json; charset=utf-8"}});}
function redirect(location:string,cookie?:string){const headers=new Headers({Location:location,"Cache-Control":"no-store"});if(cookie)headers.append("Set-Cookie",cookie);return new Response(null,{status:302,headers});}
function oauthFailure(env:Env,reason:string){console.warn(JSON.stringify({event:"oauth_failure",reason}));return redirect(`${env.APP_ORIGIN}/#/?authError=${encodeURIComponent(reason)}`,serializeCookie(OAUTH_COOKIE,"",0));}
function withSecurityHeaders(response:Response){const next=new Response(response.body,response);next.headers.set("X-Content-Type-Options","nosniff");next.headers.set("Referrer-Policy","strict-origin-when-cross-origin");next.headers.set("Permissions-Policy","camera=(), microphone=(), geolocation=()");next.headers.set("X-Frame-Options","DENY");return next;}
export { cleanDisplayName, periodStart };
