import { neon } from "@neondatabase/serverless";
import { decodeSentenceCommentCursor, encodeSentenceCommentCursor, normalizeSentenceComment } from "../src/lib/sentenceComments";

interface CommentSession { id: string; is_blocked?: boolean }
type NeonSql = ReturnType<typeof neon>;
export type CommentSqlFactory = (env: Env) => NeonSql;
const PAGE_SIZE=20,PAGE_SIZE_MAX=50,RATE_LIMIT=10,RATE_WINDOW_MINUTES=10,MAX_BODY_BYTES=4*1024;
const REPORT_REASONS=new Set(["SPAM","HARASSMENT","HATE","SEXUAL","VIOLENCE","OTHER"]);

export async function routeListeningComments(request:Request,env:Env,url:URL,session:CommentSession|null,mutationValid:boolean,admin=false,sqlFactory:CommentSqlFactory=sqlFor):Promise<Response|null>{
  try{
    const sentence=url.pathname.match(/^\/api\/listening\/sentences\/([\w-]+)\/comments$/u);
    if(request.method==="GET"&&sentence)return listComments(sqlFactory(env),url,sentence[1],session);
    if(request.method==="POST"&&sentence){const denied=guardMutation(session,mutationValid);if(denied)return denied;if(session!.is_blocked)return json({error:"user_blocked"},403);return createComment(request,sqlFactory(env),session!,sentence[1]);}
    const report=url.pathname.match(/^\/api\/listening\/comments\/([\w-]+)\/reports$/u);
    if(request.method==="POST"&&report){const denied=guardMutation(session,mutationValid);return denied??reportComment(request,sqlFactory(env),session!,report[1]);}
    const comment=url.pathname.match(/^\/api\/listening\/comments\/([\w-]+)$/u);
    if(request.method==="DELETE"&&comment){const denied=guardMutation(session,mutationValid);return denied??deleteComment(sqlFactory(env),session!,comment[1]);}
    if(request.method==="GET"&&url.pathname==="/api/listening/admin/comments/reports")return admin&&session?listReportedComments(sqlFactory(env)):json({error:"forbidden"},403);
    const moderation=url.pathname.match(/^\/api\/listening\/admin\/comments\/([\w-]+)\/moderation$/u);
    if(request.method==="POST"&&moderation){const denied=guardMutation(session,mutationValid);if(denied)return denied;return admin?moderateComment(request,sqlFactory(env),session!,moderation[1]):json({error:"forbidden"},403);}
    return null;
  }catch(error){if(error instanceof CommentHttpError)return json({error:error.code},error.status);throw error;}
}

function guardMutation(session:CommentSession|null,valid:boolean){return !session?json({error:"unauthorized"},401):!valid?json({error:"invalid_csrf"},403):null;}
async function listComments(sql:NeonSql,url:URL,sentenceId:string,session:CommentSession|null){
  if(!validResourceId(sentenceId))return json({error:"invalid_sentence"},422);if(!(await publishedSentenceExists(sql,sentenceId)))return json({error:"not_found"},404);
  const limit=Number(url.searchParams.get("limit")??PAGE_SIZE),cursorValue=url.searchParams.get("cursor"),cursor=decodeSentenceCommentCursor(cursorValue);
  if(!Number.isInteger(limit)||limit<1||limit>PAGE_SIZE_MAX)return json({error:"invalid_limit"},422);if(cursorValue&&!cursor)return json({error:"invalid_cursor"},422);
  const rows=cursor?await sql`SELECT c.id,c.sentence_id AS "sentenceId",c.body,c.created_at AS "createdAt",c.user_id AS "authorId",u.display_name AS "authorName",u.avatar_url AS "authorAvatarUrl" FROM listening_sentence_comments c JOIN users u ON u.id=c.user_id WHERE c.sentence_id=${sentenceId} AND c.status='VISIBLE' AND (c.created_at,c.id)<(${cursor.createdAt}::timestamptz,${cursor.id}) ORDER BY c.created_at DESC,c.id DESC LIMIT ${limit+1}`:await sql`SELECT c.id,c.sentence_id AS "sentenceId",c.body,c.created_at AS "createdAt",c.user_id AS "authorId",u.display_name AS "authorName",u.avatar_url AS "authorAvatarUrl" FROM listening_sentence_comments c JOIN users u ON u.id=c.user_id WHERE c.sentence_id=${sentenceId} AND c.status='VISIBLE' ORDER BY c.created_at DESC,c.id DESC LIMIT ${limit+1}`;
  const comments=rows.slice(0,limit).map(row=>serializeComment(row,session)),last=comments.at(-1);return json({comments,nextCursor:rows.length>limit&&last?encodeSentenceCommentCursor({createdAt:last.createdAt,id:last.id}):null});
}
async function createComment(request:Request,sql:NeonSql,session:CommentSession,sentenceId:string){
  if(!validResourceId(sentenceId))return json({error:"invalid_sentence"},422);const input=await readJson(request),id=typeof input.id==="string"&&validUuid(input.id)?input.id:null,body=normalizeSentenceComment(input.body);if(!id||!body)return json({error:"invalid_comment"},422);if(!(await publishedSentenceExists(sql,sentenceId)))return json({error:"not_found"},404);
  const retry=await sql`SELECT c.id,c.sentence_id AS "sentenceId",c.body,c.created_at AS "createdAt",c.user_id AS "authorId",u.display_name AS "authorName",u.avatar_url AS "authorAvatarUrl" FROM listening_sentence_comments c JOIN users u ON u.id=c.user_id WHERE c.id=${id} AND c.user_id=${session.id}`;if(retry[0])return json({comment:serializeComment(retry[0],session)});
  try{const rows=await sql`WITH rate_lock AS MATERIALIZED (SELECT pg_advisory_xact_lock(hashtextextended(${session.id},0))), permitted AS MATERIALIZED (SELECT 1 FROM rate_lock WHERE (SELECT COUNT(*) FROM listening_sentence_comments WHERE user_id=${session.id} AND created_at>now()-interval '10 minutes')<${RATE_LIMIT}), inserted AS (INSERT INTO listening_sentence_comments(id,sentence_id,user_id,body) SELECT ${id},${sentenceId},${session.id},${body} FROM permitted RETURNING *) SELECT inserted.id,inserted.sentence_id AS "sentenceId",inserted.body,inserted.created_at AS "createdAt",inserted.user_id AS "authorId",u.display_name AS "authorName",u.avatar_url AS "authorAvatarUrl" FROM inserted JOIN users u ON u.id=inserted.user_id`;return rows[0]?json({comment:serializeComment(rows[0],session)},201):json({error:"comment_rate_limited"},429,{"Retry-After":String(RATE_WINDOW_MINUTES*60)});}catch(error){if(postgresErrorCode(error)==="23505")return json({error:"comment_id_conflict"},409);throw error;}
}
async function deleteComment(sql:NeonSql,session:CommentSession,id:string){if(!validUuid(id))return json({error:"invalid_comment"},422);const rows=await sql`DELETE FROM listening_sentence_comments WHERE id=${id} AND user_id=${session.id} RETURNING id`;return rows[0]?json({ok:true}):json({error:"not_found"},404);}
async function reportComment(request:Request,sql:NeonSql,session:CommentSession,commentId:string){if(!validUuid(commentId))return json({error:"invalid_comment"},422);const input=await readJson(request),reason=typeof input.reason==="string"&&REPORT_REASONS.has(input.reason)?input.reason:null,details=typeof input.details==="string"?input.details.trim():null;if(!reason||(details!==null&&(!details||[...details].length>500)))return json({error:"invalid_report"},422);const rows=await sql`INSERT INTO listening_sentence_comment_reports(id,comment_id,reporter_user_id,reason,details) SELECT ${crypto.randomUUID()},c.id,${session.id},${reason},${details} FROM listening_sentence_comments c WHERE c.id=${commentId} AND c.status='VISIBLE' AND c.user_id<>${session.id} ON CONFLICT(comment_id,reporter_user_id) DO UPDATE SET reason=EXCLUDED.reason,details=EXCLUDED.details RETURNING id`;return rows[0]?json({ok:true},201):json({error:"not_found"},404);}
async function listReportedComments(sql:NeonSql){const rows=await sql`SELECT c.id,c.body,c.status,c.created_at AS "createdAt",u.display_name AS "authorName",COUNT(r.id)::int AS "reportCount",array_agg(DISTINCT r.reason) AS reasons,l.title AS "lessonTitle",s.position,s.transcript FROM listening_sentence_comment_reports r JOIN listening_sentence_comments c ON c.id=r.comment_id JOIN users u ON u.id=c.user_id JOIN listening_sentences s ON s.id=c.sentence_id JOIN listening_lessons l ON l.id=s.lesson_id GROUP BY c.id,u.display_name,l.title,s.position,s.transcript ORDER BY MAX(r.created_at) DESC LIMIT 200`;return json({comments:rows});}
async function moderateComment(request:Request,sql:NeonSql,session:CommentSession,commentId:string){if(!validUuid(commentId))return json({error:"invalid_comment"},422);const input=await readJson(request),action=input.action==="hide"?"HIDDEN":input.action==="restore"?"RESTORED":null,reason=typeof input.reason==="string"?input.reason.trim():"";if(!action||![...reason].length||[...reason].length>500)return json({error:"invalid_moderation"},422);const status=action==="HIDDEN"?"HIDDEN":"VISIBLE",auditId=crypto.randomUUID();const rows=await sql`WITH changed AS (UPDATE listening_sentence_comments SET status=${status} WHERE id=${commentId} AND status<>${status} RETURNING id,user_id,body), logged AS (INSERT INTO listening_sentence_comment_moderation_log(id,comment_id,target_user_id,actor_user_id,action,reason,body_snapshot) SELECT ${auditId},id,user_id,${session.id},${action},${reason},body FROM changed RETURNING id) SELECT id FROM changed`;return rows[0]?json({ok:true,status}):json({error:"not_found_or_unchanged"},404);}
async function publishedSentenceExists(sql:NeonSql,id:string){const rows=await sql`SELECT 1 FROM listening_sentences sentence JOIN listening_lessons lesson ON lesson.id=sentence.lesson_id JOIN listening_sections section ON section.id=lesson.section_id JOIN listening_categories category ON category.id=section.category_id JOIN languages language ON language.id=category.language_id WHERE sentence.id=${id} AND lesson.is_published=true AND section.is_published=true AND category.is_published=true AND language.is_enabled=true LIMIT 1`;return rows.length>0;}
async function readJson(request:Request):Promise<Record<string,unknown>>{if(!request.headers.get("content-type")?.toLocaleLowerCase().startsWith("application/json"))throw new CommentHttpError(415,"unsupported_media_type");const length=Number(request.headers.get("content-length")??0);if(Number.isFinite(length)&&length>MAX_BODY_BYTES)throw new CommentHttpError(413,"body_too_large");if(!request.body)throw new CommentHttpError(400,"missing_body");const reader=request.body.getReader(),chunks:Uint8Array[]=[];let size=0;while(true){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>MAX_BODY_BYTES){await reader.cancel();throw new CommentHttpError(413,"body_too_large");}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}try{const value=JSON.parse(new TextDecoder().decode(bytes)) as unknown;if(!value||typeof value!=="object"||Array.isArray(value))throw new Error();return value as Record<string,unknown>;}catch{throw new CommentHttpError(400,"invalid_json");}}
function serializeComment(row:Record<string,unknown>,session:CommentSession|null){return{id:String(row.id),sentenceId:String(row.sentenceId),body:String(row.body),createdAt:new Date(String(row.createdAt)).toISOString(),isOwner:row.authorId===session?.id,author:{displayName:String(row.authorName),avatarUrl:row.authorAvatarUrl?String(row.authorAvatarUrl):null}};}
function sqlFor(env:Env){return neon(env.DATABASE_URL);}function validResourceId(value:string){return /^[\w-]{1,100}$/u.test(value);}function validUuid(value:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(value);}function postgresErrorCode(error:unknown){return error&&typeof error==="object"&&"code" in error?String((error as{code?:unknown}).code??""):"";}function json(body:unknown,status=200,headers:Record<string,string>={}){return Response.json(body,{status,headers:{"Cache-Control":"no-store","Content-Type":"application/json; charset=utf-8",...headers}});}
class CommentHttpError extends Error{constructor(readonly status:number,readonly code:string){super(code);}}
