import { neon } from "@neondatabase/serverless";
import { canonicalizeLanguageCode, getLessonApprovalBlockReason, getPopularTranslationLanguage, isValidTranslationText } from "../src/lib/translation";

export interface TranslationSession { id: string; email: string; }
type NeonSql = ReturnType<typeof neon>;
type TransactionQuery = ReturnType<NeonSql>;
type TransactionSql = NeonSql & { transaction(queries: TransactionQuery[]): Promise<unknown[]> };
type GoogleTranslationResponse = { data?: { translations?: Array<{ translatedText?: string }> }; error?: { message?: string } };
const sqlFor = (env: Env) => neon(env.DATABASE_URL) as TransactionSql;
const json = (body: unknown, status = 200) => Response.json(body, { status, headers: { "Cache-Control":"no-store", "Content-Type":"application/json; charset=utf-8" } });
const validId = (value: string | null, max = 100) => value && new RegExp(`^[\\w-]{1,${max}}$`, "u").test(value) ? value : null;

export async function routeListeningTranslations(request:Request,env:Env,url:URL,session:TranslationSession|null,admin:boolean,mutationValid:boolean,ctx:ExecutionContext):Promise<Response|null>{
  if(request.method==="GET"&&url.pathname==="/api/listening/translation-languages")return getTranslationLanguages(env,url,session);
  if(request.method==="GET"&&url.pathname==="/api/listening/translations")return getTranslations(env,url,session);
  if(request.method==="POST"&&url.pathname==="/api/listening/translation-languages")return session&&mutationValid?addTranslationLanguage(request,env,session):json({error:session?"invalid_csrf":"unauthorized"},session?403:401);
  if(request.method==="PATCH"&&url.pathname==="/api/listening/translation-preference")return session&&mutationValid?saveTranslationPreference(request,env,session):json({error:session?"invalid_csrf":"unauthorized"},session?403:401);
  const sentenceMatch=url.pathname.match(/^\/api\/listening\/translations\/([\w-]+)$/u);
  if(request.method==="PUT"&&sentenceMatch)return session&&mutationValid?submitSentenceTranslation(request,env,session,sentenceMatch[1]):json({error:session?"invalid_csrf":"unauthorized"},session?403:401);
  if(request.method==="GET"&&url.pathname==="/api/listening/admin/translations")return admin?getAdminTranslations(env,url):json({error:"forbidden"},403);
  const reviewMatch=url.pathname.match(/^\/api\/listening\/admin\/translations\/([\w-]+)$/u);
  if(request.method==="PATCH"&&reviewMatch)return admin&&mutationValid?reviewTranslation(request,env,session!,reviewMatch[1]):json({error:session?"forbidden":"unauthorized"},session?403:401);
  const bulkMatch=url.pathname.match(/^\/api\/listening\/admin\/translations\/lessons\/([\w-]+)\/([^/]+)\/approve$/u);
  if(request.method==="POST"&&bulkMatch){if(!admin||!mutationValid)return json({error:session?"forbidden":"unauthorized"},session?403:401);let languageCode:string;try{languageCode=decodeURIComponent(bulkMatch[2]);}catch{return json({error:"invalid_translation_set"},422);}return approveLessonTranslations(env,session!,bulkMatch[1],languageCode);}
  const generateMatch=url.pathname.match(/^\/api\/listening\/admin\/translations\/lessons\/([\w-]+)\/generate$/u);
  if(request.method==="POST"&&generateMatch){if(!admin||!mutationValid)return json({error:session?"forbidden":"unauthorized"},session?403:401);let body:{languageCode?:unknown}={};try{body=await boundedJson(request);}catch{return json({error:"invalid_json"},400);}const languageCode=typeof body.languageCode==="string"?canonicalizeLanguageCode(body.languageCode):null;if(body.languageCode!==undefined&&!languageCode)return json({error:"invalid_language"},422);const scheduled=await scheduleAutomaticTranslations(env,ctx,generateMatch[1],languageCode?[languageCode]:undefined,session!.id);return scheduled?json({ok:true,status:env.GOOGLE_TRANSLATE_API_KEY?"PENDING":"NOT_CONFIGURED"},202):json({error:"machine_translation_not_available"},404);}
  return null;
}

async function getTranslationLanguages(env:Env,url:URL,session:TranslationSession|null){
  const lessonId=validId(url.searchParams.get("lessonId"));if(!lessonId)return json({error:"invalid_lesson"},422);
  const viewerId=session?.id??"",sql=sqlFor(env);
  const lessonRows=await sql`SELECT sentence_count FROM listening_lessons WHERE id=${lessonId} AND is_published=true`;if(!lessonRows.length)return json({error:"not_found"},404);
  const rows=await sql`SELECT lang.code,lang.name,lang.native_name AS "nativeName",lang.is_builtin AS "isBuiltin",lang.machine_translation_enabled AS "machineTranslationEnabled",lang.status,lang.created_by=${viewerId} AS "isOwner",COUNT(DISTINCT tr.sentence_id) FILTER(WHERE tr.status='APPROVED' AND s.id IS NOT NULL)::int AS "approvedCount" FROM listening_translation_languages lang LEFT JOIN listening_sentence_translation_versions tr ON tr.language_code=lang.code AND tr.status='APPROVED' LEFT JOIN listening_sentences s ON s.id=tr.sentence_id AND s.lesson_id=${lessonId} WHERE lang.status='ACTIVE' OR lang.created_by=${viewerId} GROUP BY lang.code ORDER BY lang.is_builtin DESC,lang.native_name`;
  return json({languages:rows.map(row=>({...row,sentenceCount:Number(lessonRows[0].sentence_count),canContribute:!!session&&(row.status==="ACTIVE"||row.isOwner===true)}))});
}

async function getTranslations(env:Env,url:URL,session:TranslationSession|null){
  const lessonId=validId(url.searchParams.get("lessonId")),languageCode=canonicalizeLanguageCode(url.searchParams.get("languageCode")??"");if(!lessonId||!languageCode)return json({error:"invalid_translation_query"},422);
  const sql=sqlFor(env),viewerId=session?.id??"";
  const languageRows=await sql`SELECT code,status,created_by FROM listening_translation_languages WHERE code=${languageCode} AND (status='ACTIVE' OR created_by=${viewerId})`;if(!languageRows.length)return json({error:"language_not_available"},404);
  const approved=await sql`SELECT tr.id,tr.sentence_id AS "sentenceId",tr.translated_text AS text,tr.source,tr.updated_at AS "updatedAt" FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id JOIN listening_lessons l ON l.id=s.lesson_id WHERE l.id=${lessonId} AND l.is_published=true AND tr.language_code=${languageCode} AND tr.status='APPROVED' ORDER BY s.position`;
  const contributions=session?await sql`SELECT tr.id,tr.sentence_id AS "sentenceId",tr.translated_text AS text,tr.status,tr.updated_at AS "updatedAt" FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id WHERE s.lesson_id=${lessonId} AND tr.language_code=${languageCode} AND tr.submitted_by=${session.id} AND tr.status='PENDING' ORDER BY s.position`:[];
  const setRows=await sql`SELECT status,machine_status AS "machineStatus",last_error AS "lastError" FROM listening_lesson_translation_sets WHERE lesson_id=${lessonId} AND language_code=${languageCode}`;
  return json({languageCode,approved,contributions,set:setRows[0]??null});
}

async function addTranslationLanguage(request:Request,env:Env,session:TranslationSession){
  let body:{code?:unknown};try{body=await boundedJson(request);}catch{return json({error:"invalid_json"},400);}
  const catalogLanguage=typeof body.code==="string"?getPopularTranslationLanguage(body.code):null;if(!catalogLanguage)return json({error:"language_not_in_catalog"},422);const {code,name,nativeName}=catalogLanguage;
  const sql=sqlFor(env),existing=await sql`SELECT code,name,native_name AS "nativeName",is_builtin AS "isBuiltin",machine_translation_enabled AS "machineTranslationEnabled",status,created_by=${session.id} AS "isOwner" FROM listening_translation_languages WHERE code=${code}`;
  if(existing.length){if(existing[0].status==="ACTIVE"||existing[0].isOwner===true)return json({language:{...existing[0],canContribute:true,approvedCount:0,sentenceCount:0}});return json({error:"language_already_requested"},409);}
  const countRows=await sql`SELECT COUNT(*)::int AS count FROM listening_translation_languages WHERE created_by=${session.id} AND status='PENDING'`;if(Number(countRows[0]?.count??0)>=10)return json({error:"pending_language_limit_reached"},429);
  const inserted=await sql`INSERT INTO listening_translation_languages(code,name,native_name,status,created_by) VALUES(${code},${name},${nativeName},'PENDING',${session.id}) ON CONFLICT(code) DO NOTHING RETURNING code`;if(!inserted.length)return json({error:"language_already_requested"},409);
  return json({language:{code,name,nativeName,isBuiltin:false,machineTranslationEnabled:false,status:"PENDING",isOwner:true,canContribute:true,approvedCount:0,sentenceCount:0}},201);
}

async function submitSentenceTranslation(request:Request,env:Env,session:TranslationSession,sentenceId:string){
  if(!validId(sentenceId))return json({error:"invalid_sentence"},422);let body:{languageCode?:unknown;text?:unknown};try{body=await boundedJson(request);}catch{return json({error:"invalid_json"},400);}
  const languageCode=typeof body.languageCode==="string"?canonicalizeLanguageCode(body.languageCode):null;if(!languageCode||!isValidTranslationText(body.text))return json({error:"invalid_translation"},422);
  const sql=sqlFor(env),rows=await sql`SELECT s.id,s.lesson_id,lang.status,lang.created_by FROM listening_sentences s JOIN listening_lessons l ON l.id=s.lesson_id JOIN listening_translation_languages lang ON lang.code=${languageCode} WHERE s.id=${sentenceId} AND l.is_published=true AND (lang.status='ACTIVE' OR lang.created_by=${session.id})`;if(!rows.length)return json({error:"not_found"},404);
  const lessonId=String(rows[0].lesson_id),text=String(body.text).trim(),existing=await sql`SELECT id FROM listening_sentence_translation_versions WHERE sentence_id=${sentenceId} AND language_code=${languageCode} AND submitted_by=${session.id} AND status='PENDING'`;
  if(!existing.length){const countRows=await sql`SELECT COUNT(*)::int AS count FROM listening_sentence_translation_versions WHERE submitted_by=${session.id} AND status='PENDING'`;if(Number(countRows[0]?.count??0)>=500)return json({error:"pending_translation_limit_reached"},429);}
  const translationId=existing.length?String(existing[0].id):crypto.randomUUID(),queries:TransactionQuery[]=[sql`INSERT INTO listening_lesson_translation_sets(lesson_id,language_code,status,requested_by) VALUES(${lessonId},${languageCode},'PENDING',${session.id}) ON CONFLICT(lesson_id,language_code) DO UPDATE SET status=CASE WHEN listening_lesson_translation_sets.status='APPROVED' THEN 'PARTIALLY_APPROVED' ELSE 'PENDING' END,updated_at=now()`];
  if(existing.length)queries.push(sql`UPDATE listening_sentence_translation_versions SET translated_text=${text},source='USER',updated_at=now() WHERE id=${translationId}`);else queries.push(sql`INSERT INTO listening_sentence_translation_versions(id,sentence_id,language_code,translated_text,source,status,submitted_by) VALUES(${translationId},${sentenceId},${languageCode},${text},'USER','PENDING',${session.id})`);
  queries.push(sql`INSERT INTO listening_translation_audit_log(id,translation_id,lesson_id,sentence_id,language_code,action,actor_id) VALUES(${crypto.randomUUID()},${translationId},${lessonId},${sentenceId},${languageCode},${existing.length?"UPDATED":"SUBMITTED"},${session.id})`);
  try{await sql.transaction(queries);}catch(error){if(postgresErrorCode(error)==="23505")return json({error:"translation_update_conflict"},409);throw error;}return json({translation:{id:translationId,sentenceId,languageCode,text,status:"PENDING"}},existing.length?200:201);
}

async function saveTranslationPreference(request:Request,env:Env,session:TranslationSession){
  let body:{languageCode?:unknown};try{body=await boundedJson(request);}catch{return json({error:"invalid_json"},400);}const code=typeof body.languageCode==="string"?canonicalizeLanguageCode(body.languageCode):null;if(!code)return json({error:"invalid_language"},422);
  const sql=sqlFor(env),rows=await sql`SELECT code FROM listening_translation_languages WHERE code=${code} AND (status='ACTIVE' OR created_by=${session.id})`;if(!rows.length)return json({error:"language_not_available"},404);
  await sql`UPDATE users SET preferred_translation_language_code=${code},updated_at=${Math.floor(Date.now()/1000)} WHERE id=${session.id}`;return json({languageCode:code});
}

async function getAdminTranslations(env:Env,url:URL){
  const status=url.searchParams.get("status")??"PENDING",q=(url.searchParams.get("q")??"").trim().slice(0,100);if(!["PENDING","APPROVED","REJECTED"].includes(status))return json({error:"invalid_status"},422);
  const sql=sqlFor(env),rows=await sql`SELECT tr.id,tr.sentence_id AS "sentenceId",tr.language_code AS "languageCode",tr.translated_text AS text,tr.source,tr.status,tr.created_at AS "createdAt",s.position,s.transcript,l.id AS "lessonId",l.title AS "lessonTitle",lang.native_name AS "languageName",u.display_name AS "submittedBy" FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id JOIN listening_lessons l ON l.id=s.lesson_id JOIN listening_translation_languages lang ON lang.code=tr.language_code LEFT JOIN users u ON u.id=tr.submitted_by WHERE tr.status=${status} AND (${q}='' OR l.title ILIKE ${`%${q}%`} OR s.transcript ILIKE ${`%${q}%`} OR tr.translated_text ILIKE ${`%${q}%`}) ORDER BY tr.created_at ASC LIMIT 500`;
  const sets=await sql`SELECT sets.lesson_id AS "lessonId",l.title AS "lessonTitle",sets.language_code AS "languageCode",lang.native_name AS "languageName",sets.status,sets.machine_status AS "machineStatus",sets.last_error AS "lastError",sets.attempt_count AS "attemptCount",l.is_published AS "lessonActive",lang.status AS "languageStatus",(SELECT COUNT(*)::int FROM listening_sentences s WHERE s.lesson_id=l.id) AS "sentenceCount",(SELECT COUNT(*)::int FROM listening_sentences s WHERE s.lesson_id=l.id AND EXISTS(SELECT 1 FROM listening_sentence_translation_versions tr WHERE tr.sentence_id=s.id AND tr.language_code=sets.language_code AND tr.status IN('PENDING','APPROVED'))) AS "readySentenceCount",(SELECT COUNT(*)::int FROM listening_sentences s WHERE s.lesson_id=l.id AND NOT EXISTS(SELECT 1 FROM listening_sentence_translation_versions tr WHERE tr.sentence_id=s.id AND tr.language_code=sets.language_code AND tr.status IN('PENDING','APPROVED')) AND EXISTS(SELECT 1 FROM listening_sentence_translation_versions tr WHERE tr.sentence_id=s.id AND tr.language_code=sets.language_code AND tr.status='REJECTED')) AS "rejectedSentenceCount" FROM listening_lesson_translation_sets sets JOIN listening_lessons l ON l.id=sets.lesson_id JOIN listening_translation_languages lang ON lang.code=sets.language_code WHERE (sets.status<>'APPROVED' OR EXISTS(SELECT 1 FROM listening_sentence_translation_versions pending JOIN listening_sentences sentence ON sentence.id=pending.sentence_id WHERE sentence.lesson_id=sets.lesson_id AND pending.language_code=sets.language_code AND pending.status='PENDING')) AND (${q}='' OR l.title ILIKE ${`%${q}%`}) ORDER BY sets.updated_at DESC LIMIT 500`;
  const translationSets=sets.map(row=>{const sentenceCount=Number(row.sentenceCount),readySentenceCount=Number(row.readySentenceCount),rejectedSentenceCount=Number(row.rejectedSentenceCount),approvalBlockReason=getLessonApprovalBlockReason({lessonActive:row.lessonActive===true,languageActive:row.languageStatus==="ACTIVE",sentenceCount,readySentenceCount,rejectedSentenceCount});return{...row,sentenceCount,readySentenceCount,rejectedSentenceCount,canApproveLesson:approvalBlockReason===null,approvalBlockReason};});
  return json({translations:rows,translationSets});
}

async function reviewTranslation(request:Request,env:Env,session:TranslationSession,translationId:string){
  let body:{action?:unknown;reason?:unknown};try{body=await boundedJson(request);}catch{return json({error:"invalid_json"},400);}if(body.action!=="approve"&&body.action!=="reject")return json({error:"invalid_action"},422);
  const reason=typeof body.reason==="string"?body.reason.trim().slice(0,500):"",sql=sqlFor(env),rows=await sql`SELECT tr.id,tr.sentence_id,tr.language_code,s.lesson_id,(SELECT current.id FROM listening_sentence_translation_versions current WHERE current.sentence_id=tr.sentence_id AND current.language_code=tr.language_code AND current.status='APPROVED' LIMIT 1) AS current_approved_id FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id WHERE tr.id=${translationId} AND tr.status='PENDING'`;if(!rows.length)return json({error:"not_found"},404);
  const row=rows[0],lessonId=String(row.lesson_id),sentenceId=String(row.sentence_id),languageCode=String(row.language_code),queries:TransactionQuery[]=[];
  if(body.action==="approve"){
    if(row.current_approved_id)queries.push(sql`INSERT INTO listening_translation_audit_log(id,translation_id,lesson_id,sentence_id,language_code,action,actor_id,details) VALUES(${crypto.randomUUID()},${String(row.current_approved_id)},${lessonId},${sentenceId},${languageCode},'SUPERSEDED',${session.id},${JSON.stringify({reason:"replacement_approved"})}::jsonb)`);
    queries.push(sql`UPDATE listening_sentence_translation_versions SET status='SUPERSEDED',updated_at=now() WHERE sentence_id=${sentenceId} AND language_code=${languageCode} AND status='APPROVED'`);
    queries.push(sql`UPDATE listening_sentence_translation_versions SET status='APPROVED',approved_by=${session.id},approved_at=now(),rejection_reason=NULL,updated_at=now() WHERE id=${translationId} AND status='PENDING'`);
    queries.push(sql`UPDATE listening_translation_languages SET status='ACTIVE',updated_at=now() WHERE code=${languageCode} AND status='PENDING'`);
  }else queries.push(sql`UPDATE listening_sentence_translation_versions SET status='REJECTED',rejection_reason=${reason||null},updated_at=now() WHERE id=${translationId} AND status='PENDING'`);
  queries.push(sql`INSERT INTO listening_translation_audit_log(id,translation_id,lesson_id,sentence_id,language_code,action,actor_id,details) VALUES(${crypto.randomUUID()},${translationId},${lessonId},${sentenceId},${languageCode},${body.action==="approve"?"APPROVED":"REJECTED"},${session.id},${JSON.stringify(reason?{reason}:{})}::jsonb)`);
  queries.push(translationSetStatusQuery(sql,lessonId,languageCode));try{await sql.transaction(queries);}catch(error){if(postgresErrorCode(error)==="23505")return json({error:"translation_review_conflict"},409);throw error;}return json({ok:true});
}

async function approveLessonTranslations(env:Env,session:TranslationSession,lessonId:string,rawLanguageCode:string){
  const languageCode=canonicalizeLanguageCode(rawLanguageCode);if(!validId(lessonId)||!languageCode)return json({error:"invalid_translation_set"},422);const sql=sqlFor(env);
  const stateRows=await sql`SELECT l.is_published AS lesson_active,lang.status AS language_status FROM listening_lessons l CROSS JOIN listening_translation_languages lang WHERE l.id=${lessonId} AND lang.code=${languageCode}`;if(!stateRows.length)return json({error:"not_found"},404);if(stateRows[0].lesson_active!==true)return json({error:"lesson_inactive"},409);if(stateRows[0].language_status!=="ACTIVE")return json({error:"language_inactive"},409);
  const rows=await sql`SELECT s.id AS sentence_id,p.id AS pending_id,a.id AS approved_id FROM listening_sentences s LEFT JOIN LATERAL(SELECT id FROM listening_sentence_translation_versions WHERE sentence_id=s.id AND language_code=${languageCode} AND status='PENDING' ORDER BY created_at DESC LIMIT 1)p ON true LEFT JOIN LATERAL(SELECT id FROM listening_sentence_translation_versions WHERE sentence_id=s.id AND language_code=${languageCode} AND status='APPROVED' LIMIT 1)a ON true WHERE s.lesson_id=${lessonId} ORDER BY s.position`;
  if(!rows.length||!rows.some(row=>row.pending_id||row.approved_id))return json({error:"translation_set_empty"},409);if(rows.some(row=>!row.pending_id&&!row.approved_id)){const rejected=await sql`SELECT EXISTS(SELECT 1 FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id WHERE s.lesson_id=${lessonId} AND tr.language_code=${languageCode} AND tr.status='REJECTED' AND NOT EXISTS(SELECT 1 FROM listening_sentence_translation_versions valid WHERE valid.sentence_id=s.id AND valid.language_code=${languageCode} AND valid.status IN('PENDING','APPROVED'))) AS value`;return json({error:rejected[0]?.value===true?"translation_set_rejected":"translation_set_incomplete"},409);}
  const selected=rows.filter(row=>row.pending_id).map(row=>({id:String(row.pending_id),sentenceId:String(row.sentence_id)})),selectedIds=selected.map(row=>row.id),oldApproved=rows.filter(row=>row.pending_id&&row.approved_id).map(row=>({id:String(row.approved_id),sentenceId:String(row.sentence_id)}));
  const allPending=await sql`SELECT tr.id,tr.sentence_id FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id WHERE s.lesson_id=${lessonId} AND tr.language_code=${languageCode} AND tr.status='PENDING'`,selectedIdSet=new Set(selectedIds),unselected=allPending.filter(row=>!selectedIdSet.has(String(row.id))).map(row=>({id:String(row.id),sentenceId:String(row.sentence_id)})),queries:TransactionQuery[]=[];
  if(oldApproved.length){const auditIds=oldApproved.map(()=>crypto.randomUUID()),translationIds=oldApproved.map(row=>row.id),sentenceIds=oldApproved.map(row=>row.sentenceId);queries.push(sql`UPDATE listening_sentence_translation_versions current SET status='SUPERSEDED',updated_at=transaction_timestamp() WHERE current.id=ANY(${translationIds}) AND current.status='APPROVED' AND EXISTS(SELECT 1 FROM listening_sentence_translation_versions candidate WHERE candidate.sentence_id=current.sentence_id AND candidate.id=ANY(${selectedIds}) AND candidate.status='PENDING')`);queries.push(sql`INSERT INTO listening_translation_audit_log(id,translation_id,lesson_id,sentence_id,language_code,action,actor_id,details) SELECT entry.audit_id,entry.translation_id,${lessonId},entry.sentence_id,${languageCode},'SUPERSEDED',${session.id},${JSON.stringify({reason:"bulk_replacement_approved"})}::jsonb FROM UNNEST(${auditIds}::text[],${translationIds}::text[],${sentenceIds}::text[]) AS entry(audit_id,translation_id,sentence_id) JOIN listening_sentence_translation_versions tr ON tr.id=entry.translation_id WHERE tr.status='SUPERSEDED' AND tr.updated_at=transaction_timestamp()`);}
  if(unselected.length){const auditIds=unselected.map(()=>crypto.randomUUID()),translationIds=unselected.map(row=>row.id),sentenceIds=unselected.map(row=>row.sentenceId);queries.push(sql`UPDATE listening_sentence_translation_versions SET status='SUPERSEDED',updated_at=transaction_timestamp() WHERE id=ANY(${translationIds}) AND status='PENDING'`);queries.push(sql`INSERT INTO listening_translation_audit_log(id,translation_id,lesson_id,sentence_id,language_code,action,actor_id,details) SELECT entry.audit_id,entry.translation_id,${lessonId},entry.sentence_id,${languageCode},'SUPERSEDED',${session.id},${JSON.stringify({reason:"bulk_candidate_not_selected"})}::jsonb FROM UNNEST(${auditIds}::text[],${translationIds}::text[],${sentenceIds}::text[]) AS entry(audit_id,translation_id,sentence_id) JOIN listening_sentence_translation_versions tr ON tr.id=entry.translation_id WHERE tr.status='SUPERSEDED' AND tr.updated_at=transaction_timestamp()`);}
  if(selected.length){const auditIds=selected.map(()=>crypto.randomUUID()),sentenceIds=selected.map(row=>row.sentenceId);queries.push(sql`UPDATE listening_sentence_translation_versions SET status='APPROVED',approved_by=${session.id},approved_at=transaction_timestamp(),rejection_reason=NULL,updated_at=transaction_timestamp() WHERE id=ANY(${selectedIds}) AND status='PENDING'`);queries.push(sql`INSERT INTO listening_translation_audit_log(id,translation_id,lesson_id,sentence_id,language_code,action,actor_id) SELECT entry.audit_id,entry.translation_id,${lessonId},entry.sentence_id,${languageCode},'BULK_APPROVED',${session.id} FROM UNNEST(${auditIds}::text[],${selectedIds}::text[],${sentenceIds}::text[]) AS entry(audit_id,translation_id,sentence_id) JOIN listening_sentence_translation_versions tr ON tr.id=entry.translation_id WHERE tr.status='APPROVED' AND tr.approved_by=${session.id} AND tr.approved_at=transaction_timestamp()`);}
  queries.push(translationSetStatusQuery(sql,lessonId,languageCode));try{await sql.transaction(queries);}catch(error){if(postgresErrorCode(error)==="23505")return json({error:"translation_review_conflict"},409);throw error;}return json({ok:true,approved:selected.length});
}

export async function scheduleAutomaticTranslations(env:Env,ctx:ExecutionContext,lessonId:string,targetCodes?:string[],requestedBy?:string):Promise<number>{
  const sql=sqlFor(env),configured=!!env.GOOGLE_TRANSLATE_API_KEY,targets=targetCodes?.length?targetCodes:undefined;
  const sourceRows=await sql`SELECT lang.code FROM listening_lessons l JOIN listening_sections sec ON sec.id=l.section_id JOIN listening_categories cat ON cat.id=sec.category_id JOIN languages lang ON lang.id=cat.language_id WHERE l.id=${lessonId}`;if(!sourceRows.length)return 0;const sourceLanguage=googleLanguageCode(String(sourceRows[0].code));
  const languageRows=targets?await sql`SELECT code FROM listening_translation_languages WHERE machine_translation_enabled=true AND status='ACTIVE' AND code=ANY(${targets})`:await sql`SELECT code FROM listening_translation_languages WHERE machine_translation_enabled=true AND status='ACTIVE' ORDER BY code`,languages=languageRows.filter(row=>String(row.code)!==sourceLanguage);
  if(!languages.length)return 0;
  for(const language of languages)await sql`INSERT INTO listening_lesson_translation_sets(lesson_id,language_code,status,machine_status,requested_by,last_error) VALUES(${lessonId},${String(language.code)},'PENDING',${configured?"PENDING":"NOT_CONFIGURED"},${requestedBy??null},${configured?null:"google_translate_not_configured"}) ON CONFLICT(lesson_id,language_code) DO UPDATE SET machine_status=${configured?"PENDING":"NOT_CONFIGURED"},requested_by=COALESCE(${requestedBy??null},listening_lesson_translation_sets.requested_by),last_error=${configured?null:"google_translate_not_configured"},updated_at=now()`;
  if(!configured)return languages.length;
  for(const language of languages){const targetCode=String(language.code);ctx.waitUntil(generateAutomaticTranslations(env,lessonId,[targetCode]).catch(error=>console.error(JSON.stringify({event:"lesson_translation_generation_failed",lessonId,targetCode,message:error instanceof Error?error.message:"unknown"}))));}
  return languages.length;
}

async function generateAutomaticTranslations(env:Env,lessonId:string,targetCodes:string[]){
  const sql=sqlFor(env),lessonRows=await sql`SELECT lang.code AS source_language FROM listening_lessons l JOIN listening_sections sec ON sec.id=l.section_id JOIN listening_categories cat ON cat.id=sec.category_id JOIN languages lang ON lang.id=cat.language_id WHERE l.id=${lessonId}`;if(!lessonRows.length)return;
  const sentences=await sql`SELECT id,transcript FROM listening_sentences WHERE lesson_id=${lessonId} ORDER BY position`;if(!sentences.length)return;const sourceLanguage=googleLanguageCode(String(lessonRows[0].source_language));
  for(const targetCode of targetCodes){
    if(targetCode===sourceLanguage){await sql`UPDATE listening_lesson_translation_sets SET machine_status='COMPLETED',last_error=NULL,updated_at=now() WHERE lesson_id=${lessonId} AND language_code=${targetCode}`;continue;}
    let attemptCount:number|null=null;
    try{
      const attemptRows=await sql`UPDATE listening_lesson_translation_sets SET machine_status='PROCESSING',attempt_count=attempt_count+1,last_error=NULL,updated_at=now() WHERE lesson_id=${lessonId} AND language_code=${targetCode} RETURNING attempt_count`;if(!attemptRows.length)continue;attemptCount=Number(attemptRows[0].attempt_count);
      const translated:string[]=[],chunks=chunkTexts(sentences.map(row=>String(row.transcript)));for(let offset=0;offset<chunks.length;offset+=4){const results=await Promise.all(chunks.slice(offset,offset+4).map(chunk=>googleTranslate(env,chunk,sourceLanguage,targetCode)));for(const result of results)translated.push(...result);}if(translated.length!==sentences.length)throw new Error("google_translate_count_mismatch");
      const currentAttempt=await sql`SELECT attempt_count FROM listening_lesson_translation_sets WHERE lesson_id=${lessonId} AND language_code=${targetCode}`;if(Number(currentAttempt[0]?.attempt_count)!==attemptCount)continue;
      const approvedRows=await sql`SELECT tr.sentence_id FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id WHERE s.lesson_id=${lessonId} AND tr.language_code=${targetCode} AND tr.status='APPROVED'`,approvedIds=new Set(approvedRows.map(row=>String(row.sentence_id))),pendingRows=await sql`SELECT tr.id,tr.sentence_id FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id WHERE s.lesson_id=${lessonId} AND tr.language_code=${targetCode} AND tr.source='GOOGLE' AND tr.status='PENDING'`,pendingBySentence=new Map(pendingRows.map(row=>[String(row.sentence_id),String(row.id)]));
      for(let offset=0;offset<sentences.length;offset+=50){const queries:TransactionQuery[]=[];for(let index=offset;index<Math.min(sentences.length,offset+50);index++){const sentenceId=String(sentences[index].id);if(approvedIds.has(sentenceId))continue;const translationId=crypto.randomUUID(),oldPendingId=pendingBySentence.get(sentenceId);if(oldPendingId)queries.push(sql`INSERT INTO listening_translation_audit_log(id,translation_id,lesson_id,sentence_id,language_code,action,details) VALUES(${crypto.randomUUID()},${oldPendingId},${lessonId},${sentenceId},${targetCode},'SUPERSEDED',${JSON.stringify({reason:"machine_retry"})}::jsonb)`);queries.push(sql`UPDATE listening_sentence_translation_versions SET status='SUPERSEDED',updated_at=now() WHERE sentence_id=${sentenceId} AND language_code=${targetCode} AND source='GOOGLE' AND status='PENDING'`);queries.push(sql`INSERT INTO listening_sentence_translation_versions(id,sentence_id,language_code,translated_text,source,status) VALUES(${translationId},${sentenceId},${targetCode},${translated[index]},'GOOGLE','PENDING')`);queries.push(sql`INSERT INTO listening_translation_audit_log(id,translation_id,lesson_id,sentence_id,language_code,action,details) VALUES(${crypto.randomUUID()},${translationId},${lessonId},${sentenceId},${targetCode},'GENERATED',${JSON.stringify({provider:"google-translation-basic-v2"})}::jsonb)`);}if(queries.length)await sql.transaction(queries);}
      await sql`UPDATE listening_lesson_translation_sets SET machine_status='COMPLETED',status=CASE WHEN status IN ('APPROVED','PARTIALLY_APPROVED') THEN status ELSE 'PENDING' END,last_error=NULL,updated_at=now() WHERE lesson_id=${lessonId} AND language_code=${targetCode} AND attempt_count=${attemptCount}`;
    }catch(error){const message=(error instanceof Error?error.message:"google_translate_failed").slice(0,500);if(attemptCount!==null)await sql`UPDATE listening_lesson_translation_sets SET machine_status='FAILED',status=CASE WHEN status='APPROVED' THEN status ELSE 'FAILED' END,last_error=${message},updated_at=now() WHERE lesson_id=${lessonId} AND language_code=${targetCode} AND machine_status='PROCESSING' AND attempt_count=${attemptCount}`;console.error(JSON.stringify({event:"google_translation_target_failed",lessonId,targetCode,attemptCount,message}));}
  }
}

async function googleTranslate(env:Env,texts:string[],source:string,target:string):Promise<string[]>{
  const response=await fetch("https://translation.googleapis.com/language/translate/v2",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json","X-Goog-Api-Key":env.GOOGLE_TRANSLATE_API_KEY},body:JSON.stringify({q:texts,source,target,format:"text"}),signal:AbortSignal.timeout(20_000)});
  const body=await response.json<GoogleTranslationResponse>();if(!response.ok)throw new Error(`google_translate_${response.status}:${body.error?.message?.slice(0,200)??"request_failed"}`);const translations=body.data?.translations;if(!Array.isArray(translations)||translations.some(item=>typeof item.translatedText!=="string"))throw new Error("google_translate_invalid_response");return translations.map(item=>decodeGoogleText(item.translatedText!));
}

function chunkTexts(texts:string[]):string[][]{const chunks:string[][]=[];let current:string[]=[],characters=0;for(const text of texts){if(current.length&&(current.length>=100||characters+[...text].length>20_000)){chunks.push(current);current=[];characters=0;}current.push(text);characters+=[...text].length;}if(current.length)chunks.push(current);return chunks;}
function googleLanguageCode(code:string){return code==="zh"?"zh-CN":code;}
function decodeGoogleText(value:string){return value.replace(/&#(\d+);/gu,(_,number)=>String.fromCodePoint(Number(number))).replace(/&#x([0-9a-f]+);/giu,(_,number)=>String.fromCodePoint(Number.parseInt(number,16))).replace(/&quot;/gu,'"').replace(/&#39;|&apos;/gu,"'").replace(/&lt;/gu,"<").replace(/&gt;/gu,">").replace(/&amp;/gu,"&");}

function translationSetStatusQuery(sql:TransactionSql,lessonId:string,languageCode:string){return sql`UPDATE listening_lesson_translation_sets sets SET status=CASE WHEN (SELECT COUNT(*) FROM listening_sentences WHERE lesson_id=${lessonId})=(SELECT COUNT(*) FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id WHERE s.lesson_id=${lessonId} AND tr.language_code=${languageCode} AND tr.status='APPROVED') AND EXISTS(SELECT 1 FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id WHERE s.lesson_id=${lessonId} AND tr.language_code=${languageCode} AND tr.status='PENDING') THEN 'PARTIALLY_APPROVED' WHEN (SELECT COUNT(*) FROM listening_sentences WHERE lesson_id=${lessonId})=(SELECT COUNT(*) FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id WHERE s.lesson_id=${lessonId} AND tr.language_code=${languageCode} AND tr.status='APPROVED') THEN 'APPROVED' WHEN EXISTS(SELECT 1 FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id WHERE s.lesson_id=${lessonId} AND tr.language_code=${languageCode} AND tr.status='APPROVED') THEN 'PARTIALLY_APPROVED' WHEN EXISTS(SELECT 1 FROM listening_sentence_translation_versions tr JOIN listening_sentences s ON s.id=tr.sentence_id WHERE s.lesson_id=${lessonId} AND tr.language_code=${languageCode} AND tr.status='PENDING') THEN 'PENDING' ELSE 'DRAFT' END,updated_at=now() WHERE sets.lesson_id=${lessonId} AND sets.language_code=${languageCode}`;}
async function boundedJson<T>(request:Request):Promise<T>{if(!request.body)throw new Error("missing_body");const reader=request.body.getReader(),chunks:Uint8Array[]=[];let size=0;while(true){const{value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>64*1024){await reader.cancel();throw new Error("body_too_large");}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}return JSON.parse(new TextDecoder().decode(bytes)) as T;}
function postgresErrorCode(error:unknown){return typeof error==="object"&&error!==null&&"code" in error?String((error as {code?:unknown}).code??""):"";}
