import type { UiLocale } from "./types";

const en={title:"Translation review",description:"Review community translations sentence by sentence or approve a complete lesson.",search:"Search lessons or translations",approve:"Approve",reject:"Reject",approveLesson:"Approve complete lesson",pending:"Pending translations",empty:"No translations are waiting for review.",loadError:"Translations could not be loaded.",incomplete:"Every sentence must have a pending or approved translation.",emptySet:"At least one sentence must have a translation.",rejectedSet:"Resolve rejected sentences before approving the lesson.",lessonInactive:"The lesson must be published and active.",languageInactive:"The target language must be active.",manage:"Manage",sourceUser:"Community",sourceAdmin:"Administrator",sourceGoogle:"Google"} as const;
export type AdminTranslationKey=keyof typeof en;type Messages=Record<AdminTranslationKey,string>;
const vi:Messages={title:"Kiểm duyệt bản dịch",description:"Duyệt bản dịch do cộng đồng cung cấp theo từng câu hoặc toàn bộ bài học.",search:"Tìm bài học hoặc bản dịch",approve:"Duyệt",reject:"Từ chối",approveLesson:"Duyệt toàn bộ bài học",pending:"Bản dịch chờ duyệt",empty:"Không có bản dịch nào đang chờ duyệt.",loadError:"Không thể tải danh sách bản dịch.",incomplete:"Mọi câu phải có bản dịch đang chờ duyệt hoặc đã duyệt.",emptySet:"Phải có ít nhất một câu có bản dịch.",rejectedSet:"Cần xử lý các câu đang bị từ chối trước khi duyệt bài học.",lessonInactive:"Bài học phải được xuất bản và đang hoạt động.",languageInactive:"Ngôn ngữ đích phải đang hoạt động.",manage:"Quản lý",sourceUser:"Cộng đồng",sourceAdmin:"Quản trị viên",sourceGoogle:"Google"};
const zh:Messages={title:"翻译审核",description:"逐句审核社区提供的翻译，或批准整节课程。",search:"搜索课程或翻译",approve:"批准",reject:"拒绝",approveLesson:"批准整节课程",pending:"待审核翻译",empty:"没有待审核的翻译。",loadError:"无法加载翻译。",incomplete:"每个句子都必须有待审核或已批准的翻译。",emptySet:"至少一个句子必须有翻译。",rejectedSet:"批准课程前请先处理被拒绝的句子。",lessonInactive:"课程必须已发布并处于启用状态。",languageInactive:"目标语言必须处于启用状态。",manage:"管理",sourceUser:"社区",sourceAdmin:"管理员",sourceGoogle:"Google"};
const ja:Messages={title:"翻訳レビュー",description:"コミュニティから提供された翻訳を文ごと、またはレッスン単位で承認します。",search:"レッスンまたは翻訳を検索",approve:"承認",reject:"却下",approveLesson:"レッスン全体を承認",pending:"審査待ちの翻訳",empty:"審査待ちの翻訳はありません。",loadError:"翻訳を読み込めませんでした。",incomplete:"すべての文に審査待ちまたは承認済みの翻訳が必要です。",emptySet:"少なくとも1つの文に翻訳が必要です。",rejectedSet:"レッスンを承認する前に却下された文を解決してください。",lessonInactive:"レッスンは公開済みで有効である必要があります。",languageInactive:"対象言語は有効である必要があります。",manage:"管理",sourceUser:"コミュニティ",sourceAdmin:"管理者",sourceGoogle:"Google"};
const messages:Record<UiLocale,Messages>={vi,en,zh,ja};export const adminTranslationT=(locale:UiLocale,key:AdminTranslationKey)=>messages[locale][key];
export function adminTranslationSource(locale:UiLocale,source:string){return adminTranslationT(locale,source==="USER"?"sourceUser":source==="GOOGLE"?"sourceGoogle":"sourceAdmin");}
