import type { UiLocale } from "./types";

const en={title:"User management",description:"Review user activity and moderate access to community features.",search:"Search by name or email",all:"All users",active:"Active",blocked:"Blocked",admin:"Administrator",status:"Status",joined:"Joined",lastActive:"Last active",never:"Never",comments:"Comments",lessons:"Completed lessons",studyTime:"Study time (30d)",translations:"Approved translations",leaderboard:"Leaderboard",visible:"Visible",hidden:"Hidden",block:"Block user",unblock:"Unblock user",protected:"Protected account",blockTitle:"Block user",unblockTitle:"Unblock user",blockHelp:"Blocking immediately prevents new comments and removes the user from leaderboards.",unblockHelp:"Unblocking restores commenting. Leaderboard visibility remains off until the user opts in again.",reason:"Moderation reason",reasonPlaceholder:"Enter a clear reason (3–500 characters)",cancel:"Cancel",confirmBlock:"Confirm block",confirmUnblock:"Confirm unblock",working:"Saving…",loadError:"Users could not be loaded.",actionError:"The moderation action could not be completed.",empty:"No users match these filters.",previous:"Previous",next:"Next",page:"Page {page} of {pages}",total:"{count} users",blockedOn:"Blocked on {date}",blockedBy:"by {name}"} as const;
export type AdminUsersKey=keyof typeof en;
type Messages=Record<AdminUsersKey,string>;
const vi:Messages={title:"Quản lý người dùng",description:"Theo dõi hoạt động và kiểm soát quyền tham gia các tính năng cộng đồng.",search:"Tìm theo tên hoặc email",all:"Tất cả người dùng",active:"Đang hoạt động",blocked:"Đã chặn",admin:"Quản trị viên",status:"Trạng thái",joined:"Ngày tham gia",lastActive:"Hoạt động gần nhất",never:"Chưa có",comments:"Bình luận",lessons:"Bài đã hoàn thành",studyTime:"Thời gian học (30 ngày)",translations:"Bản dịch đã duyệt",leaderboard:"Bảng xếp hạng",visible:"Đang hiển thị",hidden:"Đang ẩn",block:"Chặn người dùng",unblock:"Bỏ chặn",protected:"Tài khoản được bảo vệ",blockTitle:"Chặn người dùng",unblockTitle:"Bỏ chặn người dùng",blockHelp:"Chặn sẽ lập tức ngăn bình luận mới và loại người dùng khỏi bảng xếp hạng.",unblockHelp:"Bỏ chặn sẽ cho phép bình luận lại. Người dùng phải tự bật lại quyền xuất hiện trên bảng xếp hạng.",reason:"Lý do kiểm duyệt",reasonPlaceholder:"Nhập lý do rõ ràng (3–500 ký tự)",cancel:"Hủy",confirmBlock:"Xác nhận chặn",confirmUnblock:"Xác nhận bỏ chặn",working:"Đang lưu…",loadError:"Không thể tải danh sách người dùng.",actionError:"Không thể hoàn tất thao tác kiểm duyệt.",empty:"Không có người dùng phù hợp bộ lọc.",previous:"Trước",next:"Sau",page:"Trang {page}/{pages}",total:"{count} người dùng",blockedOn:"Bị chặn ngày {date}",blockedBy:"bởi {name}"};
const zh:Messages={title:"用户管理",description:"查看用户活动并管理社区功能访问权限。",search:"按姓名或邮箱搜索",all:"所有用户",active:"正常",blocked:"已封禁",admin:"管理员",status:"状态",joined:"注册时间",lastActive:"最近活动",never:"暂无",comments:"评论",lessons:"已完成课程",studyTime:"学习时长（30天）",translations:"已批准翻译",leaderboard:"排行榜",visible:"已显示",hidden:"已隐藏",block:"封禁用户",unblock:"解除封禁",protected:"受保护账户",blockTitle:"封禁用户",unblockTitle:"解除封禁",blockHelp:"封禁后将立即禁止新评论，并从排行榜中移除。",unblockHelp:"解除后可重新评论；排行榜显示需由用户再次主动开启。",reason:"管理原因",reasonPlaceholder:"请输入明确原因（3–500字）",cancel:"取消",confirmBlock:"确认封禁",confirmUnblock:"确认解除",working:"保存中…",loadError:"无法加载用户。",actionError:"无法完成管理操作。",empty:"没有符合筛选条件的用户。",previous:"上一页",next:"下一页",page:"第 {page}/{pages} 页",total:"共 {count} 位用户",blockedOn:"封禁于 {date}",blockedBy:"操作人：{name}"};
const ja:Messages={title:"ユーザー管理",description:"ユーザー活動を確認し、コミュニティ機能へのアクセスを管理します。",search:"名前またはメールで検索",all:"すべて",active:"有効",blocked:"ブロック中",admin:"管理者",status:"状態",joined:"登録日",lastActive:"最終アクティブ",never:"なし",comments:"コメント",lessons:"完了レッスン",studyTime:"学習時間（30日）",translations:"承認済み翻訳",leaderboard:"ランキング",visible:"表示中",hidden:"非表示",block:"ユーザーをブロック",unblock:"ブロック解除",protected:"保護されたアカウント",blockTitle:"ユーザーをブロック",unblockTitle:"ブロックを解除",blockHelp:"ブロックすると新規コメントを禁止し、ランキングから直ちに除外します。",unblockHelp:"解除後はコメント可能になります。ランキング表示はユーザーが再度有効にする必要があります。",reason:"管理理由",reasonPlaceholder:"明確な理由を入力（3～500文字）",cancel:"キャンセル",confirmBlock:"ブロックを確定",confirmUnblock:"解除を確定",working:"保存中…",loadError:"ユーザーを読み込めませんでした。",actionError:"管理操作を完了できませんでした。",empty:"条件に一致するユーザーはいません。",previous:"前へ",next:"次へ",page:"{page}/{pages} ページ",total:"{count} 人",blockedOn:"{date} にブロック",blockedBy:"実行者: {name}"};
const messages:Record<UiLocale,Messages>={en,vi,zh,ja};
export function adminUsersT(locale:UiLocale,key:AdminUsersKey,values:Record<string,string|number>={}){return Object.entries(values).reduce((text,[name,value])=>text.replaceAll(`{${name}}`,String(value)),messages[locale][key]);}
