import type { UiLocale } from "./types";

const vi = {
  chooseTitle: "Hôm nay bạn muốn học ngôn ngữ nào?", chooseSubtitle: "Chọn một ngôn ngữ để mở thư viện bài học tương ứng. Bạn có thể đổi lại bất cứ lúc nào.", startLearning: "Bắt đầu học", interfaceLanguage: "Ngôn ngữ giao diện", learners: "người đang học", lessons: "bài học", freeForever: "Miễn phí để bắt đầu", home: "Trang chủ", overview: "Tổng quan", library: "Thư viện bài học", progress: "Tiến độ", saved: "Đã lưu", learning: "Đang học", settings: "Cài đặt", guide: "Hướng dẫn", search: "Tìm bài luyện nghe...", dailyPractice: "Luyện nghe mỗi ngày.", dailySubtitle: "Nghe từng câu, gõ lại chính xác và xây dựng phản xạ tự nhiên.", weekProgress: "Tiến độ tuần này", accuracy: "độ chính xác", suggested: "Bài đề xuất hôm nay", sentences: "câu", minutes: "phút", voice: "Giọng", begin: "Bắt đầu luyện", allStories: "Tất cả câu chuyện", level: "Trình độ", all: "Tất cả", section: "Phần", noLessons: "Không tìm thấy bài học", retryFilter: "Thử từ khóa hoặc bộ lọc khác nhé.", backLibrary: "Thư viện", sentence: "Câu", repeat: "Lặp lại", spaceListen: "để nghe", typePrompt: "Gõ lại những gì bạn nghe được", characters: "ký tự", typePlaceholder: "Bắt đầu nhập câu trả lời...", caseHint: "Không phân biệt hoa thường và dấu câu", check: "Kiểm tra", next: "Câu tiếp theo", excellent: "Tuyệt vời!", almost: "Gần đúng rồi!", correctMessage: "Bạn đã nghe chính xác câu này.", retryMessage: "Các phần màu đỏ cần được nghe lại.", translation: "Xem bản dịch", transcript: "Toàn bài & transcript", sentenceList: "Danh sách câu", listenComplete: "Nghe và hoàn thành câu này", tip: "Mẹo nhỏ", tipText: "Nghe 2–3 lần trước khi xem gợi ý. Tai bạn sẽ bắt đầu nhận ra cách nối âm.", fullTranscript: "TOÀN BỘ TRANSCRIPT", learningExperience: "Trải nghiệm học", autoPlay: "Tự động phát câu tiếp theo", autoPlayHint: "Phát audio khi chuyển câu", showTranslation: "Hiển thị bản dịch", showTranslationHint: "Hiện nghĩa sau khi chấm", reset: "Xóa toàn bộ tiến độ", changeLanguage: "Đổi ngôn ngữ học", signIn: "Đăng nhập", signInGoogle: "Tiếp tục với Google", leaderboard: "Bảng xếp hạng", day: "Ngày", week: "Tuần", month: "Tháng", year: "Năm", points: "điểm", activeMinutes: "phút học", editName: "Đổi tên hiển thị", displayName: "Tên hiển thị", save: "Lưu thay đổi", cancel: "Hủy", logout: "Đăng xuất", leaderboardTitle: "Những người học chăm chỉ", emptyLeaderboard: "Chưa có hoạt động trong khoảng thời gian này.", yourPosition: "Vị trí của bạn", publicRanking: "Hiện trên bảng xếp hạng", publicRankingHint: "Chỉ công khai tên và ảnh đại diện",
  comingSoon: "Sắp ra mắt", loading: "Đang tải…", loadError: "Không thể tải nội dung.", retry: "Thử lại", previous: "Câu trước", audioUnavailable: "Không có âm thanh.", playbackSpeed: "Tốc độ phát", saving: "Đang lưu…", lessonComplete: "Đã hoàn thành bài học",
};

const en: typeof vi = {
  chooseTitle: "What would you like to learn today?", chooseSubtitle: "Choose a language to open its lesson library. You can switch whenever you like.", startLearning: "Start learning", interfaceLanguage: "Interface language", learners: "active learners", lessons: "lessons", freeForever: "Free to get started", home: "Home", overview: "Overview", library: "Lesson library", progress: "Progress", saved: "Saved", learning: "Learning", settings: "Settings", guide: "Guide", search: "Search listening lessons...", dailyPractice: "Listen better every day.", dailySubtitle: "Listen sentence by sentence, type accurately, and build a natural response.", weekProgress: "This week's progress", accuracy: "accuracy", suggested: "Suggested for today", sentences: "sentences", minutes: "minutes", voice: "Voice", begin: "Start practice", allStories: "All stories", level: "Level", all: "All", section: "Section", noLessons: "No lessons found", retryFilter: "Try another keyword or filter.", backLibrary: "Library", sentence: "Sentence", repeat: "Repeat", spaceListen: "to listen", typePrompt: "Type what you hear", characters: "characters", typePlaceholder: "Start typing your answer...", caseHint: "Capitalization and punctuation are ignored", check: "Check", next: "Next sentence", excellent: "Excellent!", almost: "Almost there!", correctMessage: "You heard this sentence accurately.", retryMessage: "Listen again to the parts shown in red.", translation: "Show translation", transcript: "Full audio & transcript", sentenceList: "Sentence list", listenComplete: "Listen and complete this sentence", tip: "Quick tip", tipText: "Listen two or three times before using a hint. Your ears will begin to notice connected speech.", fullTranscript: "FULL TRANSCRIPT", learningExperience: "Learning experience", autoPlay: "Autoplay next sentence", autoPlayHint: "Play audio when changing sentences", showTranslation: "Show translation", showTranslationHint: "Reveal meaning after checking", reset: "Reset all progress", changeLanguage: "Change learning language", signIn: "Sign in", signInGoogle: "Continue with Google", leaderboard: "Leaderboard", day: "Day", week: "Week", month: "Month", year: "Year", points: "points", activeMinutes: "active min", editName: "Edit display name", displayName: "Display name", save: "Save changes", cancel: "Cancel", logout: "Sign out", leaderboardTitle: "Most dedicated learners", emptyLeaderboard: "No learning activity in this period yet.", yourPosition: "Your position", publicRanking: "Appear on leaderboard", publicRankingHint: "Only your name and avatar are public",
  comingSoon: "Coming soon", loading: "Loading…", loadError: "Content could not be loaded.", retry: "Retry", previous: "Previous", audioUnavailable: "Audio is unavailable.", playbackSpeed: "Playback speed", saving: "Saving…", lessonComplete: "Lesson complete",
};

const zh: typeof vi = {
  chooseTitle: "今天你想学习哪种语言？", chooseSubtitle: "选择一种语言，进入相应的课程库。你可以随时回来更换。", startLearning: "开始学习", interfaceLanguage: "界面语言", learners: "名学习者", lessons: "节课程", freeForever: "免费开始学习", home: "主页", overview: "概览", library: "课程库", progress: "学习进度", saved: "已收藏", learning: "正在学习", settings: "设置", guide: "使用指南", search: "搜索听力课程…", dailyPractice: "每天练习听力。", dailySubtitle: "逐句听写，准确输入，培养自然的语言反应。", weekProgress: "本周进度", accuracy: "正确率", suggested: "今日推荐", sentences: "句", minutes: "分钟", voice: "口音", begin: "开始练习", allStories: "全部故事", level: "级别", all: "全部", section: "单元", noLessons: "没有找到课程", retryFilter: "请尝试其他关键词或筛选条件。", backLibrary: "课程库", sentence: "句子", repeat: "重复播放", spaceListen: "播放音频", typePrompt: "输入你听到的内容", characters: "个字符", typePlaceholder: "开始输入答案…", caseHint: "不区分大小写和标点符号", check: "检查", next: "下一句", excellent: "非常好！", almost: "快答对了！", correctMessage: "你准确地听出了这句话。", retryMessage: "请重新听红色部分。", translation: "查看翻译", transcript: "全文与音频", sentenceList: "句子列表", listenComplete: "听音频并完成句子", tip: "学习提示", tipText: "查看提示前先听两三遍，你会逐渐听出自然连读。", fullTranscript: "完整文本", learningExperience: "学习体验", autoPlay: "自动播放下一句", autoPlayHint: "切换句子时自动播放", showTranslation: "显示翻译", showTranslationHint: "检查后显示释义", reset: "清除全部进度", changeLanguage: "更换学习语言", signIn: "登录", signInGoogle: "使用 Google 继续", leaderboard: "排行榜", day: "今日", week: "本周", month: "本月", year: "今年", points: "分", activeMinutes: "分钟学习", editName: "修改显示名称", displayName: "显示名称", save: "保存", cancel: "取消", logout: "退出登录", leaderboardTitle: "最勤奋的学习者", emptyLeaderboard: "该时段还没有学习记录。", yourPosition: "你的排名", publicRanking: "显示在排行榜中", publicRankingHint: "仅公开名称和头像",
  comingSoon: "即将推出", loading: "正在加载…", loadError: "无法加载内容。", retry: "重试", previous: "上一句", audioUnavailable: "音频不可用。", playbackSpeed: "播放速度", saving: "正在保存…", lessonComplete: "课程已完成",
};

const ja: typeof vi = {
  chooseTitle: "今日は何語を学びますか？", chooseSubtitle: "言語を選ぶと、その言語のレッスン一覧が開きます。いつでも変更できます。", startLearning: "学習を始める", interfaceLanguage: "表示言語", learners: "人が学習中", lessons: "レッスン", freeForever: "無料で始める", home: "ホーム", overview: "概要", library: "レッスン一覧", progress: "進捗", saved: "保存済み", learning: "学習中", settings: "設定", guide: "ガイド", search: "リスニング教材を検索…", dailyPractice: "毎日、耳を鍛えよう。", dailySubtitle: "一文ずつ聞いて正確に入力し、自然な反応力を身につけます。", weekProgress: "今週の進捗", accuracy: "正解率", suggested: "今日のおすすめ", sentences: "文", minutes: "分", voice: "音声", begin: "練習を始める", allStories: "すべてのストーリー", level: "レベル", all: "すべて", section: "セクション", noLessons: "レッスンが見つかりません", retryFilter: "別のキーワードや条件をお試しください。", backLibrary: "レッスン一覧", sentence: "文", repeat: "リピート", spaceListen: "で再生", typePrompt: "聞こえた内容を入力してください", characters: "文字", typePlaceholder: "回答を入力…", caseHint: "大文字・小文字と句読点は区別しません", check: "答え合わせ", next: "次の文", excellent: "すばらしい！", almost: "あと少し！", correctMessage: "正確に聞き取れました。", retryMessage: "赤い部分をもう一度聞いてみましょう。", translation: "翻訳を見る", transcript: "全文と音声", sentenceList: "文の一覧", listenComplete: "音声を聞いて文を完成させましょう", tip: "ヒント", tipText: "ヒントを見る前に2〜3回聞くと、音のつながりが少しずつ分かります。", fullTranscript: "全文", learningExperience: "学習設定", autoPlay: "次の文を自動再生", autoPlayHint: "文を切り替えたら音声を再生", showTranslation: "翻訳を表示", showTranslationHint: "答え合わせ後に意味を表示", reset: "進捗をすべて削除", changeLanguage: "学習言語を変更", signIn: "ログイン", signInGoogle: "Googleで続ける", leaderboard: "ランキング", day: "今日", week: "今週", month: "今月", year: "今年", points: "ポイント", activeMinutes: "分学習", editName: "表示名を変更", displayName: "表示名", save: "保存", cancel: "キャンセル", logout: "ログアウト", leaderboardTitle: "よく学んでいる人", emptyLeaderboard: "この期間の学習記録はまだありません。", yourPosition: "あなたの順位", publicRanking: "ランキングに表示", publicRankingHint: "名前と画像のみ公開されます",
  comingSoon: "近日公開", loading: "読み込み中…", loadError: "コンテンツを読み込めませんでした。", retry: "再試行", previous: "前の文", audioUnavailable: "音声を利用できません。", playbackSpeed: "再生速度", saving: "保存中…", lessonComplete: "レッスン完了",
};

export type TranslationKey = keyof typeof vi;
export const translations = { vi, en, zh, ja };
export const localeLabels: Record<UiLocale, string> = { vi: "Tiếng Việt", en: "English", zh: "中文", ja: "日本語" };
export const translate = (locale: UiLocale, key: TranslationKey) => translations[locale][key];
