import type { UiLocale } from "./types";

const messages = {
  vi: { vocabLevel: "Trình độ", sentenceProgress: "Câu", previousSentence: "Câu trước", nextSentence: "Câu tiếp theo", answer: "Đáp án", correctAnswer: "Đáp án chính xác", revealedAnswer: "Đáp án đã được hiển thị", pronunciation: "Luyện phát âm", pronunciationHint: "Đọc to câu này để ghi nhớ nhịp điệu và cách nối âm.", microphoneSoon: "Tính năng trả lời bằng giọng nói sẽ sớm ra mắt", listeningTip: "Mẹo luyện nghe", listeningTipText: "Hãy nghe hai hoặc ba lần trước khi kiểm tra hoặc bỏ qua. Sau khi thấy đáp án, thử đọc to cả câu.", settings: "Tùy chọn phát", dictationTab: "Nghe và chép", transcriptTab: "Toàn bộ transcript", settingsTitle:"Cài đặt bài nghe", closeSettings:"Đóng cài đặt", settingsDescription:"Các tùy chọn này được lưu riêng cho tài khoản của bạn.", replayKey:"Phím nghe lại", playPauseKey:"Phím phát / tạm dừng", autoReplay:"Tự động nghe lại", replayDelay:"Thời gian giữa các lần nghe", wordSuggestions:"Gợi ý từ trên điện thoại", shortcutTips:"Hiển thị mẹo phím tắt", seconds:"giây", enabled:"Bật", disabled:"Tắt", settingsSaveError:"Không thể lưu cài đặt. Vui lòng thử lại.", replayShortcut:"Nghe lại", playPauseShortcut:"Phát / tạm dừng" },
  en: { vocabLevel: "Level", sentenceProgress: "Sentence", previousSentence: "Previous sentence", nextSentence: "Next sentence", answer: "Answer", correctAnswer: "Correct answer", revealedAnswer: "Answer revealed", pronunciation: "Pronunciation practice", pronunciationHint: "Read the sentence aloud to remember its rhythm and connected speech.", microphoneSoon: "Voice answers are coming soon", listeningTip: "Listening tip", listeningTipText: "Listen two or three times before checking or skipping. Once the answer appears, try reading the full sentence aloud.", settings: "Playback options", dictationTab: "Dictation", transcriptTab: "Full transcript", settingsTitle:"Listening settings", closeSettings:"Close settings", settingsDescription:"These preferences are saved separately for your account.", replayKey:"Replay key", playPauseKey:"Play / pause key", autoReplay:"Auto replay", replayDelay:"Seconds between replays", wordSuggestions:"Word suggestions on smartphones", shortcutTips:"Show shortcut key tips", seconds:"seconds", enabled:"Enabled", disabled:"Disabled", settingsSaveError:"Settings could not be saved. Please try again.", replayShortcut:"Replay", playPauseShortcut:"Play / pause" },
  zh: { vocabLevel: "级别", sentenceProgress: "句子", previousSentence: "上一句", nextSentence: "下一句", answer: "答案", correctAnswer: "正确答案", revealedAnswer: "答案已显示", pronunciation: "发音练习", pronunciationHint: "大声朗读句子，记住节奏和连读。", microphoneSoon: "语音回答功能即将推出", listeningTip: "听力提示", listeningTipText: "检查或跳过前先听两三遍。看到答案后，试着大声朗读完整句子。", settings: "播放选项", dictationTab: "听写", transcriptTab: "完整文本", settingsTitle:"听力设置", closeSettings:"关闭设置", settingsDescription:"这些设置会单独保存到你的帐户。", replayKey:"重播键", playPauseKey:"播放 / 暂停键", autoReplay:"自动重播", replayDelay:"重播间隔", wordSuggestions:"手机单词建议", shortcutTips:"显示快捷键提示", seconds:"秒", enabled:"开启", disabled:"关闭", settingsSaveError:"无法保存设置，请重试。", replayShortcut:"重播", playPauseShortcut:"播放 / 暂停" },
  ja: { vocabLevel: "レベル", sentenceProgress: "文", previousSentence: "前の文", nextSentence: "次の文", answer: "答え", correctAnswer: "正解", revealedAnswer: "答えを表示しました", pronunciation: "発音練習", pronunciationHint: "文を声に出して、リズムと音のつながりを覚えましょう。", microphoneSoon: "音声回答機能は近日公開予定です", listeningTip: "リスニングのヒント", listeningTipText: "確認やスキップの前に2〜3回聞きましょう。答えを見た後は、文全体を声に出してみてください。", settings: "再生オプション", dictationTab: "ディクテーション", transcriptTab: "全文", settingsTitle:"リスニング設定", closeSettings:"設定を閉じる", settingsDescription:"この設定はアカウントごとに保存されます。", replayKey:"リプレイキー", playPauseKey:"再生 / 一時停止キー", autoReplay:"自動リプレイ", replayDelay:"リプレイ間隔", wordSuggestions:"スマートフォンの単語候補", shortcutTips:"ショートカットのヒントを表示", seconds:"秒", enabled:"有効", disabled:"無効", settingsSaveError:"設定を保存できませんでした。もう一度お試しください。", replayShortcut:"リプレイ", playPauseShortcut:"再生 / 一時停止" },
} as const satisfies Record<UiLocale, Record<string, string>>;

const supplementalMessages = {
  vi: { nextLesson: "Bài nghe tiếp theo", checkShortcut: "Nhấn Enter để kiểm tra", nextShortcut: "Nhấn Enter để tiếp tục", skipShortcut: "Nhấn Esc để bỏ qua", playSentence:"Phát câu", pauseSentence:"Tạm dừng câu", seekSentence:"Tua trong câu", repeatSentence:"Nghe lại câu", audioConnectionError:"Không thể phát âm thanh. Hãy kiểm tra kết nối rồi thử lại.", fullLessonAudio:"Audio toàn bài", retryAnswer:"Làm lại câu này", retryAnswerError:"Không thể xóa kết quả. Vui lòng thử lại.", resetLesson:"Học lại từ đầu", resetLessonConfirm:"Xóa toàn bộ tiến độ và học lại bài này từ đầu?", resetLessonError:"Không thể đặt lại bài học. Vui lòng thử lại.", addFavorite:"Thêm bài học vào yêu thích", removeFavorite:"Bỏ bài học khỏi yêu thích", favoriteError:"Không thể cập nhật yêu thích. Vui lòng thử lại.", stars:"lượt yêu thích", completedLesson:"Đã hoàn thành", properNounSuggestions:"Tên riêng có thể xuất hiện", playAllTranscript:"Phát toàn bộ", pauseAllTranscript:"Tạm dừng", translateTo:"Dịch sang", noTranslation:"Không dịch" },
  en: { nextLesson: "Next listening lesson", checkShortcut: "Press Enter to check", nextShortcut: "Press Enter to continue", skipShortcut: "Press Esc to skip", playSentence:"Play sentence", pauseSentence:"Pause sentence", seekSentence:"Seek within sentence", repeatSentence:"Repeat sentence", audioConnectionError:"Audio is unavailable. Check your connection and try again.", fullLessonAudio:"Full lesson audio", retryAnswer:"Try this sentence again", retryAnswerError:"The result could not be cleared. Please try again.", resetLesson:"Reset lesson", resetLessonConfirm:"Clear all progress and restart this lesson?", resetLessonError:"The lesson could not be reset. Please try again.", addFavorite:"Add lesson to favorites", removeFavorite:"Remove lesson from favorites", favoriteError:"The favorite could not be updated. Please try again.", stars:"favorites", completedLesson:"Completed", properNounSuggestions:"Names you may hear", playAllTranscript:"Play all", pauseAllTranscript:"Pause", translateTo:"Translate to", noTranslation:"No translation" },
  zh: { nextLesson: "下一节听力课", checkShortcut: "按 Enter 检查", nextShortcut: "按 Enter 继续", skipShortcut: "按 Esc 跳过", playSentence:"播放句子", pauseSentence:"暂停句子", seekSentence:"在句子中定位", repeatSentence:"重播句子", audioConnectionError:"音频无法播放。请检查网络连接后重试。", fullLessonAudio:"完整课程音频", retryAnswer:"重新回答此句", retryAnswerError:"无法清除结果，请重试。", resetLesson:"重置课程", resetLessonConfirm:"清除所有进度并重新开始本课？", resetLessonError:"无法重置课程，请重试。", addFavorite:"将课程加入收藏", removeFavorite:"从收藏中移除课程", favoriteError:"无法更新收藏，请重试。", stars:"次收藏", completedLesson:"已完成", properNounSuggestions:"可能听到的专有名称", playAllTranscript:"播放全部", pauseAllTranscript:"暂停", translateTo:"翻译成", noTranslation:"不翻译" },
  ja: { nextLesson: "次のリスニングレッスン", checkShortcut: "Enterで確認", nextShortcut: "Enterで次へ", skipShortcut: "Escでスキップ", playSentence:"文を再生", pauseSentence:"文を一時停止", seekSentence:"文の中を移動", repeatSentence:"文をもう一度再生", audioConnectionError:"音声を再生できません。接続を確認して再試行してください。", fullLessonAudio:"レッスン全体の音声", retryAnswer:"この文をやり直す", retryAnswerError:"結果を消去できませんでした。もう一度お試しください。", resetLesson:"レッスンをリセット", resetLessonConfirm:"すべての進捗を消去して、このレッスンを最初からやり直しますか？", resetLessonError:"レッスンをリセットできませんでした。もう一度お試しください。", addFavorite:"レッスンをお気に入りに追加", removeFavorite:"お気に入りから削除", favoriteError:"お気に入りを更新できませんでした。もう一度お試しください。", stars:"件のお気に入り", completedLesson:"完了", properNounSuggestions:"聞こえる可能性のある固有名詞", playAllTranscript:"すべて再生", pauseAllTranscript:"一時停止", translateTo:"翻訳先", noTranslation:"翻訳なし" },
} as const satisfies Record<UiLocale, Record<string, string>>;

type SupplementalMessageKey = keyof typeof supplementalMessages.en;
export type LessonMessageKey = keyof typeof messages.en | SupplementalMessageKey;
export const lessonT = (locale: UiLocale, key: LessonMessageKey) => key in supplementalMessages.en ? supplementalMessages[locale][key as SupplementalMessageKey] : messages[locale][key as keyof typeof messages.en];
