import type { UiLocale } from "./types";

const en = {
  searchLessons:"Search lessons", searchPlaceholder:"Search by title or slug", status:"Status", allStatuses:"All statuses", published:"Published", draft:"Draft", language:"Language", allLanguages:"All languages", english:"English", chinese:"Chinese", japanese:"Japanese", lessonId:"Lesson ID", title:"Title", slug:"Slug", level:"Level", description:"Description", placement:"Placement", order:"Order", scriptJson:"Script/resource JSON", scriptHint:"Edit text, position, startMs, and endMs. Sentence IDs must remain unchanged.", cancel:"Cancel", saveChanges:"Save changes", open:"Open", delete:"Delete", loadError:"Unable to load lessons.", openError:"Unable to open the lesson.", updateError:"Unable to update the lesson.", deleteError:"Unable to delete the lesson.", deleteConfirm:"Delete “{title}”? This also removes its audio and progress.",
} as const;
type BaseLessonManagementKey=keyof typeof en;
type Messages=Record<BaseLessonManagementKey,string>;
const vi:Messages={searchLessons:"Tìm bài học",searchPlaceholder:"Tìm theo tiêu đề hoặc slug",status:"Trạng thái",allStatuses:"Tất cả trạng thái",published:"Đã xuất bản",draft:"Bản nháp",language:"Ngôn ngữ",allLanguages:"Tất cả ngôn ngữ",english:"Tiếng Anh",chinese:"Tiếng Trung",japanese:"Tiếng Nhật",lessonId:"ID bài học",title:"Tiêu đề",slug:"Slug",level:"Trình độ",description:"Mô tả",placement:"Vị trí",order:"Thứ tự",scriptJson:"JSON nội dung/tài nguyên",scriptHint:"Chỉnh sửa text, position, startMs và endMs. Không được thay đổi ID của câu.",cancel:"Hủy",saveChanges:"Lưu thay đổi",open:"Mở",delete:"Xóa",loadError:"Không thể tải danh sách bài học.",openError:"Không thể mở bài học.",updateError:"Không thể cập nhật bài học.",deleteError:"Không thể xóa bài học.",deleteConfirm:"Xóa “{title}”? Audio và tiến độ liên quan cũng sẽ bị xóa."};
const zh:Messages={searchLessons:"搜索课程",searchPlaceholder:"按标题或 slug 搜索",status:"状态",allStatuses:"所有状态",published:"已发布",draft:"草稿",language:"语言",allLanguages:"所有语言",english:"英语",chinese:"中文",japanese:"日语",lessonId:"课程 ID",title:"标题",slug:"Slug",level:"级别",description:"描述",placement:"所属位置",order:"顺序",scriptJson:"脚本/资源 JSON",scriptHint:"可编辑 text、position、startMs 和 endMs。句子 ID 不得更改。",cancel:"取消",saveChanges:"保存更改",open:"打开",delete:"删除",loadError:"无法加载课程。",openError:"无法打开课程。",updateError:"无法更新课程。",deleteError:"无法删除课程。",deleteConfirm:"删除“{title}”？相关音频和学习进度也会被删除。"};
const ja:Messages={searchLessons:"レッスンを検索",searchPlaceholder:"タイトルまたは slug で検索",status:"状態",allStatuses:"すべての状態",published:"公開済み",draft:"下書き",language:"言語",allLanguages:"すべての言語",english:"英語",chinese:"中国語",japanese:"日本語",lessonId:"レッスン ID",title:"タイトル",slug:"Slug",level:"レベル",description:"説明",placement:"配置先",order:"並び順",scriptJson:"スクリプト/リソース JSON",scriptHint:"text、position、startMs、endMsを編集できます。文のIDは変更しないでください。",cancel:"キャンセル",saveChanges:"変更を保存",open:"開く",delete:"削除",loadError:"レッスンを読み込めませんでした。",openError:"レッスンを開けませんでした。",updateError:"レッスンを更新できませんでした。",deleteError:"レッスンを削除できませんでした。",deleteConfirm:"「{title}」を削除しますか？音声と学習進捗も削除されます。"};
const extras = {
  en: { exactPath:"Exact canonical path", exactPathPlaceholder:"/lessons/a1/short-stories/lesson-slug", canonicalPath:"Canonical path", editDetails:"Edit details", rename:"Rename", renameError:"Unable to rename the lesson.", selectLesson:"Select {title}", selectAll:"Select up to 50 visible lessons", selectedCount:"{count} selected (maximum 50)", batchDelete:"Delete selected", batchDeleteConfirm:"Delete {count} selected lessons? Their audio and progress will also be removed.", batchDeleteError:"Unable to delete the selected lessons.", batchDeletePartial:"Deleted {deleted} lessons; {failed} could not be deleted.", lessonCount:"{count} lessons", noLessons:"No lessons match the current filters." },
  vi: { exactPath:"Canonical path chính xác", exactPathPlaceholder:"/lessons/a1/short-stories/lesson-slug", canonicalPath:"Canonical path", editDetails:"Sửa chi tiết", rename:"Đổi tên", renameError:"Không thể đổi tên bài học.", selectLesson:"Chọn {title}", selectAll:"Chọn tối đa 50 bài đang hiển thị", selectedCount:"Đã chọn {count} (tối đa 50)", batchDelete:"Xóa mục đã chọn", batchDeleteConfirm:"Xóa {count} bài học đã chọn? Audio và tiến độ liên quan cũng sẽ bị xóa.", batchDeleteError:"Không thể xóa các bài học đã chọn.", batchDeletePartial:"Đã xóa {deleted} bài; không thể xóa {failed} bài.", lessonCount:"{count} bài học", noLessons:"Không có bài học nào khớp với bộ lọc hiện tại." },
  zh: { exactPath:"精确规范路径", exactPathPlaceholder:"/lessons/a1/short-stories/lesson-slug", canonicalPath:"规范路径", editDetails:"编辑详情", rename:"重命名", renameError:"无法重命名课程。", selectLesson:"选择 {title}", selectAll:"最多选择当前显示的 50 节课程", selectedCount:"已选择 {count} 项（最多 50 项）", batchDelete:"删除所选", batchDeleteConfirm:"删除选中的 {count} 节课程？相关音频和进度也会被删除。", batchDeleteError:"无法删除所选课程。", batchDeletePartial:"已删除 {deleted} 节课程；{failed} 节无法删除。", lessonCount:"{count} 节课程", noLessons:"没有符合当前筛选条件的课程。" },
  ja: { exactPath:"正確な canonical path", exactPathPlaceholder:"/lessons/a1/short-stories/lesson-slug", canonicalPath:"Canonical path", editDetails:"詳細を編集", rename:"名前を変更", renameError:"レッスン名を変更できませんでした。", selectLesson:"{title} を選択", selectAll:"表示中のレッスンを最大50件選択", selectedCount:"{count} 件選択中（最大50件）", batchDelete:"選択項目を削除", batchDeleteConfirm:"選択した {count} 件のレッスンを削除しますか？音声と進捗も削除されます。", batchDeleteError:"選択したレッスンを削除できませんでした。", batchDeletePartial:"{deleted} 件を削除しました。{failed} 件は削除できませんでした。", lessonCount:"{count} 件のレッスン", noLessons:"現在のフィルターに一致するレッスンがありません。" },
} as const satisfies Record<UiLocale,Record<string,string>>;
type ExtraLessonManagementKey=keyof typeof extras.en;
export type LessonManagementKey=BaseLessonManagementKey|ExtraLessonManagementKey;
export const lessonManagementMessages:Record<UiLocale,Messages>={vi,en,zh,ja};
export function lessonManagementT(locale:UiLocale,key:LessonManagementKey,values:Record<string,string|number>={}){const source=key in extras.en?extras[locale][key as ExtraLessonManagementKey]:lessonManagementMessages[locale][key as BaseLessonManagementKey];return Object.entries(values).reduce((message,[name,value])=>message.replaceAll(`{${name}}`,String(value)),source);}
