import { ArrowLeft, ArrowRight, BookOpen, Check, Clock3, Headphones, RotateCcw } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useAuth } from "./auth";
import { AudioSegmentPlayer, type AudioSegmentPlayerHandle } from "./components/AudioSegmentPlayer";
import { translate } from "./i18n";
import { evaluateAnswer } from "./lib/dictation";
import type { UiLocale } from "./types";

interface Category { id:string; slug:string; name:string; description:string|null; }
interface Section { id:string; number:number; title:string; description:string|null; lesson_count:number; }
interface LessonSummary { id:string; slug:string; title:string; description:string|null; level:string|null; duration_ms:number; sentence_count:number; }
interface ListeningSentence { id:string; position:number; transcript:string; start_ms:number; end_ms:number; metadata:Record<string,unknown>; }
interface ListeningLesson extends LessonSummary { audio_url:string|null; category_slug:string; section_id:string; section_number:number; sentences:ListeningSentence[]; }
interface ReviewSentence { id:string; position:number; text:string; startMs:number; endMs:number; }

async function getJson<T>(path:string):Promise<T>{const response=await fetch(path,{credentials:"same-origin"});const body=await response.json() as T&{error?:string};if(!response.ok)throw new Error(body.error??"request_failed");return body;}
const navigate=(path:string)=>{window.location.hash=path;window.scrollTo({top:0,behavior:"smooth"});};

function useHash(){const [hash,setHash]=useState(window.location.hash);useEffect(()=>{const update=()=>setHash(window.location.hash);window.addEventListener("hashchange",update);return()=>window.removeEventListener("hashchange",update);},[]);return hash;}

export function EnglishLearningApp({locale,onHome,header}:{locale:UiLocale;onHome:()=>void;header:React.ReactNode}){
  const hash=useHash(),lesson=hash.match(/^#\/learn\/en\/lesson\/([\w-]+)$/u),section=hash.match(/^#\/learn\/en\/([\w-]+)\/([\w-]+)$/u),category=hash.match(/^#\/learn\/en\/([\w-]+)$/u);
  const content=lesson?<DictationLesson lessonSlug={lesson[1]} locale={locale} onHome={onHome}/>:section?<LessonList categorySlug={section[1]} sectionId={section[2]} locale={locale} onHome={onHome}/>:category?<SectionList categorySlug={category[1]} locale={locale} onHome={onHome}/>:<CategoryList locale={locale} onHome={onHome}/>;
  return <><div className="learning-page-header">{header}</div>{content}</>;
}

interface Breadcrumb { label: string; onClick?: () => void; }
function Breadcrumbs({items,locale}:{items:Breadcrumb[];locale:UiLocale}){return <nav className="breadcrumbs" aria-label={translate(locale,"breadcrumb")}>{items.map((item,index)=><span key={`${item.label}-${index}`}>{index>0&&<b aria-hidden="true">/</b>}{item.onClick?<button type="button" onClick={item.onClick}>{item.label}</button>:<span aria-current="page">{item.label}</span>}</span>)}</nav>;}
function formatCategory(slug:string){return slug.split("-").map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(" ");}
function formatSection(id:string,locale:UiLocale){const number=id.match(/-(\d+)$/u)?.[1];return number?`${translate(locale,"section")} ${number}`:translate(locale,"section");}
function Shell({children,onHome,title,locale="en",breadcrumbs}:{children:React.ReactNode;onHome:()=>void;title:string;locale?:UiLocale;breadcrumbs?:Breadcrumb[]}){return <div className="content-shell"><header>{breadcrumbs?<Breadcrumbs locale={locale} items={breadcrumbs}/>:<><button onClick={onHome} className="back-link"><ArrowLeft size={18}/>{translate(locale,"home")}</button><h1>{title}</h1></>}</header><main>{children}</main></div>;}
function Loading({locale="en"}:{locale?:UiLocale}){return <div className="content-state" role="status">{translate(locale,"loading")}</div>;} function LoadError({retry,locale="en"}:{retry:()=>void;locale?:UiLocale}){return <div className="content-state" role="alert"><p>{translate(locale,"loadError")}</p><button onClick={retry}>{translate(locale,"retry")}</button></div>;}

function CategoryList({locale,onHome}:{locale:UiLocale;onHome:()=>void}){const [items,setItems]=useState<Category[]>(),[failed,setFailed]=useState(false),[attempt,setAttempt]=useState(0);useEffect(()=>{setFailed(false);void getJson<{categories:Category[]}>("/api/listening/categories?language=en").then(x=>setItems(x.categories)).catch(()=>setFailed(true));},[attempt]);return <Shell locale={locale} onHome={onHome} title="English" breadcrumbs={[{label:translate(locale,"allTopics"),onClick:onHome}]}>{failed?<LoadError retry={()=>setAttempt(x=>x+1)}/>:!items?<Loading/>:<div className="content-grid">{items.map(item=><button className="content-card" key={item.id} onClick={()=>navigate(`/learn/en/${item.slug}`)}><BookOpen/><h2>{item.name}</h2><p>{item.description??translate(locale,"dailySubtitle")}</p><span>{translate(locale,"startLearning")} <ArrowRight size={16}/></span></button>)}</div>}</Shell>;}

function SectionList({categorySlug,locale,onHome}:{categorySlug:string;locale:UiLocale;onHome:()=>void}){const [items,setItems]=useState<Section[]>(),[failed,setFailed]=useState(false),[attempt,setAttempt]=useState(0);useEffect(()=>{setFailed(false);void getJson<{sections:Section[]}>(`/api/listening/sections?category=${encodeURIComponent(categorySlug)}`).then(x=>setItems(x.sections)).catch(()=>setFailed(true));},[categorySlug,attempt]);return <Shell locale={locale} onHome={onHome} title={translate(locale,"section")} breadcrumbs={[{label:translate(locale,"allTopics"),onClick:onHome},{label:formatCategory(categorySlug),onClick:()=>navigate(`/learn/en/${categorySlug}`)}]}>{failed?<LoadError retry={()=>setAttempt(x=>x+1)}/>:!items?<Loading/>:<div className="content-grid">{items.map(item=><button className="content-card" key={item.id} onClick={()=>navigate(`/learn/en/${categorySlug}/${item.id}`)}><h2>{item.title}</h2><p>{item.description??`${item.lesson_count} ${translate(locale,"lessons")}`}</p><ArrowRight/></button>)}</div>}</Shell>;}

function LessonList({categorySlug,sectionId,locale,onHome}:{categorySlug:string;sectionId:string;locale:UiLocale;onHome:()=>void}){const [items,setItems]=useState<LessonSummary[]>(),[failed,setFailed]=useState(false),[attempt,setAttempt]=useState(0);useEffect(()=>{setFailed(false);void getJson<{lessons:LessonSummary[]}>(`/api/listening/lessons?section=${encodeURIComponent(sectionId)}`).then(x=>setItems(x.lessons)).catch(()=>setFailed(true));},[sectionId,attempt]);return <Shell locale={locale} onHome={onHome} title={translate(locale,"lessons")} breadcrumbs={[{label:translate(locale,"allTopics"),onClick:onHome},{label:formatCategory(categorySlug),onClick:()=>navigate(`/learn/en/${categorySlug}`)},{label:formatSection(sectionId,locale)}]}>{failed?<LoadError retry={()=>setAttempt(x=>x+1)}/>:!items?<Loading/>:items.length?<div className="content-grid">{items.map(item=><button className="content-card" key={item.id} onClick={()=>navigate(`/learn/en/lesson/${item.id}`)}><span className="level-badge mint">{item.level??"—"}</span><h2>{item.title}</h2><p>{item.description}</p><small><Headphones size={14}/>{item.sentence_count} {translate(locale,"sentences")} · <Clock3 size={14}/>{Math.ceil(item.duration_ms/60000)} {translate(locale,"minutes")}</small></button>)}</div>:<div className="content-state">{translate(locale,"noLessons")}</div>}</Shell>;}

const guestKey=(lessonId:string)=>`me2listen-listening-progress-${lessonId}`;
function loadGuest(lessonId:string){try{return new Set<string>(JSON.parse(localStorage.getItem(guestKey(lessonId))??"[]") as string[]);}catch{return new Set<string>();}}

function DictationLesson({lessonSlug,locale,onHome}:{lessonSlug:string;locale:UiLocale;onHome:()=>void}){
  const auth=useAuth(),playerRef=useRef<AudioSegmentPlayerHandle>(null),[lesson,setLesson]=useState<ListeningLesson>(),[failed,setFailed]=useState(false),[index,setIndex]=useState(0),[typed,setTyped]=useState(""),[submitted,setSubmitted]=useState(false),[completed,setCompleted]=useState<Set<string>>(new Set()),[attempts,setAttempts]=useState(0),[speed,setSpeed]=useState(1),[repeat,setRepeat]=useState(false),[mode,setMode]=useState<"dictation"|"transcript">("dictation"),[saving,setSaving]=useState(false);
  useEffect(()=>{setFailed(false);void getJson<{lesson:ListeningLesson}>(`/api/listening/lessons/${encodeURIComponent(lessonSlug)}`).then(({lesson:item})=>{setLesson(item);const local=loadGuest(item.id);setCompleted(local);if(auth.user)void getJson<{lesson:{current_sentence_position:number}|null;sentences:Array<{sentence_id:string;is_completed:boolean}>}>(`/api/listening/progress?lesson=${encodeURIComponent(item.id)}`).then(progress=>{const merged=new Set(local);progress.sentences.filter(x=>x.is_completed).forEach(x=>merged.add(x.sentence_id));setCompleted(merged);setIndex(Math.max(0,Math.min(item.sentences.length-1,(progress.lesson?.current_sentence_position??1)-1)));}).catch(()=>undefined);}).catch(()=>setFailed(true));},[lessonSlug,auth.user?.id]);
  useEffect(()=>{setTyped("");setSubmitted(false);setAttempts(0);},[index,lesson?.id]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null,isTyping=target?.tagName==="TEXTAREA"||target?.tagName==="INPUT";if(event.code==="Space"&&!isTyping){event.preventDefault();playerRef.current?.toggle();}if(event.key.toLocaleLowerCase()==="r"&&!isTyping)playerRef.current?.replay();if(event.key==="Enter"&&!isTyping)document.querySelector<HTMLButtonElement>(".answer-footer .primary-button")?.click();};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[]);
  if(failed)return <Shell onHome={onHome} title="English"><LoadError retry={()=>location.reload()}/></Shell>;if(!lesson)return <Loading/>;if(!lesson.sentences.length)return <Shell onHome={onHome} title={lesson.title}><div className="content-state">{translate(locale,"noLessons")}</div></Shell>;
  const sentence=lesson.sentences[index],evaluation=evaluateAnswer({expected:sentence.transcript,actual:typed,language:"en"}),isDone=completed.has(sentence.id),accepted=isDone||(submitted&&evaluation.correct),percent=Math.round(completed.size/lesson.sentences.length*100);
  const complete=async()=>{if(isDone)return;const next=new Set(completed).add(sentence.id);setCompleted(next);localStorage.setItem(guestKey(lesson.id),JSON.stringify([...next]));if(auth.user){setSaving(true);try{await auth.saveListeningProgress({lessonId:lesson.id,sentenceId:sentence.id,position:sentence.position,attemptCount:attempts+1,firstTryCorrect:attempts===0});}catch{/* local progress remains usable and can be retried */}finally{setSaving(false);}}};
  const submit=()=>{if(!typed.trim())return;setSubmitted(true);if(evaluation.correct)void complete();else setAttempts(value=>value+1);};
  const next=()=>{if(!accepted)return;if(index<lesson.sentences.length-1)setIndex(index+1);};
  const onEnter=(event:React.KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key!=="Enter"||event.shiftKey)return;event.preventDefault();if(accepted)next();else submit();};
  return <div className="dictation-shell"><header><button className="back-link" onClick={()=>navigate(`/learn/en/${lesson.category_slug}/${lesson.section_id}`)}><ArrowLeft size={18}/>{translate(locale,"backLibrary")}</button><div><b>{lesson.title}</b><small>{translate(locale,"sentence")} {index+1}/{lesson.sentences.length}</small></div><span>{percent}%</span></header><div className="mode-tabs"><button className={mode==="dictation"?"active":""} onClick={()=>setMode("dictation")}>{translate(locale,"learning")}</button><button className={mode==="transcript"?"active":""} onClick={()=>setMode("transcript")}>{translate(locale,"fullTranscript")}</button></div>{mode==="transcript"?<main className="full-transcript-view">{lesson.audio_url&&<audio controls preload="metadata" src={lesson.audio_url}/>}<ol>{lesson.sentences.map(item=><li key={item.id}>{item.transcript}</li>)}</ol></main>:<main className="dictation-main"><div className="sentence-progress"><i style={{width:`${percent}%`}}/></div>{lesson.audio_url?<AudioSegmentPlayer ref={playerRef} src={lesson.audio_url} startMs={sentence.start_ms} endMs={sentence.end_ms} playbackRate={speed} repeat={repeat}/>:<div className="audio-error" role="alert">Audio is unavailable.</div>}<div className="playback-options"><button className={repeat?"active":""} onClick={()=>setRepeat(x=>!x)}><RotateCcw size={15}/>{translate(locale,"repeat")}</button><select aria-label="Playback speed" value={speed} onChange={event=>setSpeed(Number(event.target.value))}>{[.5,.75,1,1.25,1.5].map(value=><option key={value} value={value}>{value}×</option>)}</select></div><section className={`answer-panel ${submitted?(evaluation.correct?"success":"retry"):""}`}><label htmlFor="listening-answer">{translate(locale,"typePrompt")}</label>{accepted?<div className="correct-answer"><Check/>{sentence.transcript}</div>:<textarea id="listening-answer" value={typed} onChange={event=>setTyped(event.target.value)} onKeyDown={onEnter} placeholder={translate(locale,"typePlaceholder")} autoFocus={window.innerWidth>780}/>} {submitted&&!evaluation.correct&&<div className="word-result" aria-live="polite">{evaluation.tokens.map((token,i)=><span key={`${token.text}-${i}`} className={token.status}>{token.status==="hidden"?"*****":token.text}</span>)}</div>}<div className="answer-footer"><span>{saving?translate(locale,"saved"):translate(locale,"caseHint")}</span><button className="primary-button" disabled={!typed.trim()&&!isDone} onClick={accepted?next:submit}>{accepted?translate(locale,"next"):translate(locale,"check")}<ArrowRight size={16}/></button></div></section><nav className="sentence-nav"><button disabled={index===0} onClick={()=>setIndex(index-1)}><ArrowLeft/>Previous</button><button disabled={index===lesson.sentences.length-1||!accepted} onClick={next}>Next<ArrowRight/></button></nav></main>}</div>;
}

export function AdminListeningPage({onHome}:{onHome:()=>void}){
  const auth=useAuth(),[sections,setSections]=useState<Array<{section_id:string;category_name:string;section_title:string}>>([]),[file,setFile]=useState<File>(),[transcript,setTranscript]=useState(""),[title,setTitle]=useState(""),[level,setLevel]=useState("A1"),[sectionId,setSectionId]=useState(""),[lessonId,setLessonId]=useState(""),[review,setReview]=useState<ReviewSentence[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(auth.user?.isAdmin)void getJson<{sections:typeof sections}>("/api/listening/admin/bootstrap").then(x=>{setSections(x.sections);setSectionId(x.sections[0]?.section_id??"");}).catch(()=>setError("Unable to load admin data."));},[auth.user?.isAdmin]);
  if(auth.loading)return <Loading/>;if(!auth.user?.isAdmin)return <Shell onHome={onHome} title="Content management"><div className="content-state">Administrator access is required.</div></Shell>;
  const process=async()=>{if(!file)return;setBusy(true);setError("");try{const durationMs=await mediaDuration(file);const form=new FormData();form.set("audio",file);form.set("transcript",transcript);form.set("title",title);form.set("level",level);form.set("sectionId",sectionId);form.set("durationMs",String(durationMs));const result=await auth.adminImportLesson(form);setLessonId(result.lessonId);setReview((result.sentences as ReviewSentence[]));}catch(reason){setError(reason instanceof Error?reason.message:"Import failed");}finally{setBusy(false);}};
  const publish=async()=>{setBusy(true);setError("");try{await auth.adminReviewLesson(lessonId,{publish:true,sentences:review});setLessonId("");setReview([]);}catch(reason){setError(reason instanceof Error?reason.message:"Publish failed");}finally{setBusy(false);}};
  return <Shell onHome={onHome} title="Listening content management">{error&&<p className="form-error" role="alert">{error}</p>} {!lessonId?<form className="admin-import" onSubmit={event=>{event.preventDefault();void process();}}><label>Section<select value={sectionId} onChange={e=>setSectionId(e.target.value)}>{sections.map(item=><option key={item.section_id} value={item.section_id}>{item.category_name} · {item.section_title}</option>)}</select></label><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/><small>Slug sẽ được tự động tạo từ Title.</small></label><label>Level<input value={level} onChange={e=>setLevel(e.target.value)}/></label><label>Audio<input required type="file" accept="audio/*" onChange={e=>setFile(e.target.files?.[0])}/></label><label>Transcript, one sentence per line<textarea required value={transcript} onChange={e=>setTranscript(e.target.value)}/></label><button className="primary-button" disabled={busy||!file}>{busy?"Processing…":"Process"}</button></form>:<div className="alignment-review">{review.map((item,index)=><fieldset key={item.id}><legend>Sentence {item.position}</legend><button type="button" onClick={()=>file&&playFileSegment(file,item.startMs,item.endMs)}>▶</button><input type="number" value={item.startMs} onChange={e=>setReview(rows=>rows.map((row,i)=>i===index?{...row,startMs:Number(e.target.value)}:row))}/><span>→</span><input type="number" value={item.endMs} onChange={e=>setReview(rows=>rows.map((row,i)=>i===index?{...row,endMs:Number(e.target.value)}:row))}/><textarea value={item.text} onChange={e=>setReview(rows=>rows.map((row,i)=>i===index?{...row,text:e.target.value}:row))}/></fieldset>)}<button className="primary-button" disabled={busy} onClick={()=>void publish()}>{busy?"Publishing…":"Publish"}</button></div>}</Shell>;
}

function mediaDuration(file:File){return new Promise<number>((resolve,reject)=>{const audio=new Audio(),url=URL.createObjectURL(file);audio.preload="metadata";audio.onloadedmetadata=()=>{const duration=Math.round(audio.duration*1000);URL.revokeObjectURL(url);Number.isFinite(duration)&&duration>0?resolve(duration):reject(new Error("Invalid audio duration"));};audio.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("Audio metadata could not be read"));};audio.src=url;});}
function playFileSegment(file:File,startMs:number,endMs:number){const audio=new Audio(URL.createObjectURL(file));audio.currentTime=startMs/1000;void audio.play();const stop=()=>{if(audio.currentTime>=endMs/1000){audio.pause();URL.revokeObjectURL(audio.src);}else requestAnimationFrame(stop);};requestAnimationFrame(stop);}
