import { ArrowLeft, ArrowRight, BookOpen, ChevronDown, Clock3, Headphones, Lightbulb, Mic, RotateCcw, Search, Settings2, X } from "lucide-react";
import { useEffect, useRef, useState, type CSSProperties } from "react";
import { useAuth } from "./auth";
import { adminSystemT } from "./adminSystemI18n";
import { AudioSegmentPlayer, type AudioSegmentPlayerHandle } from "./components/AudioSegmentPlayer";
import { ListeningSettingsDialog } from "./components/ListeningSettingsDialog";
import { LessonTranslationPanel } from "./components/LessonTranslationPanel";
import { AdminLayout } from "./components/admin/AdminLayout";
import { LessonImportPage } from "./components/admin/LessonImportPage";
import { localeTags, translate } from "./i18n";
import { evaluateAnswer } from "./lib/dictation";
import { matchesReplayShortcut, shortcutLabel, type ListeningPreferences } from "./lib/listeningPreferences";
import { loadLocalListeningPreferences, saveLocalListeningPreferences } from "./lib/listeningPreferencesStorage";
import { lessonT } from "./lessonI18n";
import { lessonManagementT } from "./lessonManagementI18n";
import { findNextLesson, loadLessonManifest, type LessonManifest } from "./lib/lessonManifest";
import { abortSpeechRecognition, classifySpeechRecognitionError, collectRecognizedSpeech, getSpeechRecognitionConstructor, getSpeechRecognitionLocale, mergeRecognizedSpeech, type BrowserSpeechRecognition, type SpeechRecognitionErrorKind } from "./lib/speechRecognition";
import { buildLessonSections, collectLessonLevels, filterLessonSections } from "./lib/sectionCatalog";
import { buildTopicSummaries, formatLevelRange } from "./lib/topicCatalog";
import { findActiveTranscriptIndex } from "./lib/transcriptTracking";
import { hashHref, navigateToHash, navigateToPath } from "./router";
import { sectionT } from "./sectionI18n";
import { speechRecognitionT } from "./speechRecognitionI18n";
import { topicT } from "./topicI18n";
import type { UiLocale } from "./types";

interface Category { id:string; slug:string; name:string; description:string|null; }
interface Section { id:string; number:number; title:string; description:string|null; lesson_count:number; }
interface LessonSummary { id:string; slug:string; title:string; description:string|null; level:string|null; duration_ms:number; sentence_count:number; path?:string; }
interface ListeningSentence { id:string; position:number; transcript:string; start_ms:number; end_ms:number; metadata:Record<string,unknown>; }
interface ListeningLesson extends LessonSummary { audio_url:string|null; category_slug:string; section_id:string; section_number:number; language_code:string; sentences:ListeningSentence[]; }
interface ReviewSentence { id:string; position:number; text:string; startMs:number; endMs:number; }

async function getJson<T>(path:string):Promise<T>{const response=await fetch(path,{credentials:"same-origin"});const body=await response.json() as T&{error?:string};if(!response.ok)throw new Error(body.error??"request_failed");return body;}
const navigate=(path:string)=>{navigateToHash(path);window.scrollTo({top:0,behavior:"smooth"});};

function useLearningRoute(){
  const read=()=>window.location.hash.startsWith("#/learn/en")?window.location.hash.slice(1):window.location.pathname.startsWith("/learn/en")?window.location.pathname:"/learn/en";
  const [route,setRoute]=useState(read);
  useEffect(()=>{const update=()=>setRoute(read());window.addEventListener("hashchange",update);window.addEventListener("popstate",update);return()=>{window.removeEventListener("hashchange",update);window.removeEventListener("popstate",update);};},[]);
  return route;
}

export function EnglishLearningApp({locale,onHome,header,canonicalPath}:{locale:UiLocale;onHome:()=>void;header:React.ReactNode;canonicalPath?:string}){
  const manifestState=useLessonManifest();
  const route=useLearningRoute(),lesson=route.match(/^\/learn\/en\/lesson\/([\w-]+)$/u),section=route.match(/^\/learn\/en\/([\w-]+)\/([\w-]+)$/u),category=route.match(/^\/learn\/en\/([\w-]+)$/u);
  const canonical=canonicalPath?.match(/^\/lessons\/([^/]+)\/([^/]+)\/([^/]+)$/u);
  const content=canonical?<DictationLesson manifest={manifestState.manifest} lessonPath={{level:canonical[1],category:canonical[2],slug:canonical[3]}} locale={locale} onHome={onHome}/>:lesson?<DictationLesson manifest={manifestState.manifest} lessonSlug={lesson[1]} locale={locale} onHome={onHome}/>:manifestState.failed?<Shell locale={locale} onHome={onHome} title="English"><LoadError locale={locale} retry={manifestState.retry}/></Shell>:section?<LessonList manifest={manifestState.manifest} categorySlug={section[1]} sectionId={section[2]} locale={locale} onHome={onHome}/>:category?<SectionList manifest={manifestState.manifest} categorySlug={category[1]} locale={locale} onHome={onHome}/>:<CategoryList manifest={manifestState.manifest} locale={locale} onHome={onHome}/>;
  return <><div className="learning-page-header">{header}</div>{content}</>;
}
function useLessonManifest(){const [manifest,setManifest]=useState<LessonManifest>(),[failed,setFailed]=useState(false),[attempt,setAttempt]=useState(0);useEffect(()=>{setFailed(false);void loadLessonManifest().then(setManifest).catch(()=>setFailed(true));},[attempt]);return {manifest,failed,retry:()=>setAttempt(value=>value+1)};}

interface Breadcrumb { label: string; onClick?: () => void; }
function Breadcrumbs({items,locale}:{items:Breadcrumb[];locale:UiLocale}){return <nav className="breadcrumbs" aria-label={translate(locale,"breadcrumb")}>{items.map((item,index)=><span key={`${item.label}-${index}`}>{index>0&&<b aria-hidden="true">/</b>}{item.onClick?<button type="button" onClick={item.onClick}>{item.label}</button>:<span aria-current="page">{item.label}</span>}</span>)}</nav>;}
function formatCategory(slug:string){return slug.split("-").map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(" ");}
function formatSection(id:string,locale:UiLocale){const number=id.match(/-(\d+)$/u)?.[1];return number?`${translate(locale,"section")} ${number}`:translate(locale,"section");}
function Shell({children,onHome,title,locale="en",breadcrumbs,wide=false}:{children:React.ReactNode;onHome:()=>void;title:string;locale?:UiLocale;breadcrumbs?:Breadcrumb[];wide?:boolean}){return <div className={`content-shell${wide?" content-shell-wide":""}`}><header>{breadcrumbs?<Breadcrumbs locale={locale} items={breadcrumbs}/>:<><button onClick={onHome} className="back-link"><ArrowLeft size={18}/>{translate(locale,"home")}</button><h1>{title}</h1></>}</header><main>{children}</main></div>;}
function Loading({locale="en"}:{locale?:UiLocale}){return <div className="content-state" role="status">{translate(locale,"loading")}</div>;} function LoadError({retry,locale="en"}:{retry:()=>void;locale?:UiLocale}){return <div className="content-state" role="alert"><p>{translate(locale,"loadError")}</p><button onClick={retry}>{translate(locale,"retry")}</button></div>;}

function CategoryList({manifest,locale,onHome}:{manifest?:LessonManifest;locale:UiLocale;onHome:()=>void}){
  const [categories,setCategories]=useState<Category[]>([]);
  useEffect(()=>{let active=true;void getJson<{categories:Category[]}>("/api/listening/categories?language=en").then(result=>{if(active)setCategories(result.categories);}).catch(()=>undefined);return()=>{active=false;};},[]);
  const items=manifest?buildTopicSummaries(manifest.lessons,"en",categories):undefined;
  return <Shell wide locale={locale} onHome={onHome} title="English" breadcrumbs={[{label:translate(locale,"allTopics")}]}>
    {!items?<Loading locale={locale}/>:<section className="topics-catalog" aria-labelledby="topics-title">
      <header className="topics-heading"><span>{topicT(locale,"eyebrow")}</span><h1 id="topics-title">{translate(locale,"allTopics")}</h1><p>{topicT(locale,"intro")}</p></header>
      {items.length?<ul className="topics-grid">{items.map(item=>{const path=`/learn/en/${item.slug}`,style={"--topic-hue":item.hue} as CSSProperties;return <li key={item.slug}><a className="topic-card" href={hashHref(path)} onClick={event=>followHashLink(event,path)} aria-label={`${topicT(locale,"openTopic")}: ${item.name}`}><span className="topic-cover" style={style} aria-hidden="true"><BookOpen size={22}/><b>{item.initials}</b></span><span className="topic-card-body"><span className="topic-title-row"><h2>{item.name}</h2><ArrowRight className="topic-card-arrow" size={18}/></span>{item.description&&<p>{item.description}</p>}<span className="topic-meta"><span><b>{topicT(locale,"levels")}</b>{formatLevelRange(item.levels,topicT(locale,"allLevels"))}</span><span><Headphones size={14}/><b>{item.lessonCount}</b>{translate(locale,"lessons")}</span></span></span></a></li>;})}</ul>:<div className="content-state">{translate(locale,"noLessons")}</div>}
    </section>}
  </Shell>;
}

function SectionList({manifest,categorySlug,locale,onHome}:{manifest?:LessonManifest;categorySlug:string;locale:UiLocale;onHome:()=>void}){
  const [query,setQuery]=useState(""),[level,setLevel]=useState("all"),[openSections,setOpenSections]=useState<Set<string>>(new Set()),[sectionRecords,setSectionRecords]=useState<Section[]>([]);
  useEffect(()=>{let active=true;void getJson<{sections:Section[]}>(`/api/listening/sections?category=${encodeURIComponent(categorySlug)}`).then(result=>{if(active)setSectionRecords(result.sections);}).catch(()=>undefined);return()=>{active=false;};},[categorySlug]);
  const sections=manifest?buildLessonSections(manifest.lessons,"en",categorySlug,sectionRecords):undefined;
  const filteredSections=sections?filterLessonSections(sections,query,level):undefined;
  const levels=sections?collectLessonLevels(sections):[];
  const categoryName=sections?.[0]?.lessons[0]?.categoryName??formatCategory(categorySlug);
  const filtering=Boolean(query.trim())||level!=="all";
  useEffect(()=>{setQuery("");setLevel("all");setOpenSections(new Set());},[categorySlug]);
  useEffect(()=>{if(!filtering||!filteredSections)return;setOpenSections(new Set(filteredSections.map(section=>section.id)));},[query,level]);
  const toggle=(sectionId:string)=>setOpenSections(current=>{const next=new Set(current);if(next.has(sectionId))next.delete(sectionId);else next.add(sectionId);return next;});
  const clearFilters=()=>{setQuery("");setLevel("all");};
  return <Shell wide locale={locale} onHome={onHome} title={categoryName} breadcrumbs={[{label:translate(locale,"allTopics"),onClick:()=>navigate("/learn/en")},{label:categoryName}]}>
    {!sections||!filteredSections?<Loading locale={locale}/>:<section className="section-catalog" aria-labelledby="section-catalog-title">
      <header className="section-catalog-heading"><div><span>{topicT(locale,"eyebrow")}</span><h1 id="section-catalog-title">{categoryName}</h1><p>{sectionT(locale,"intro")}</p></div><div className="section-filters" role="search"><label className="section-search"><span className="sr-only">{sectionT(locale,"search")}</span><Search size={17} aria-hidden="true"/><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={sectionT(locale,"searchPlaceholder")}/>{query&&<button type="button" onClick={()=>setQuery("")} aria-label={sectionT(locale,"clearFilters")}><X size={15}/></button>}</label><label className="section-level-filter"><span className="sr-only">{translate(locale,"level")}</span><select value={level} onChange={event=>setLevel(event.target.value)}><option value="all">{sectionT(locale,"allLevels")}</option>{levels.map(item=><option value={item} key={item}>{item}</option>)}</select><ChevronDown size={16} aria-hidden="true"/></label></div></header>
      <div className="section-results" aria-live="polite"><span><b>{filteredSections.length}</b> {sectionT(locale,"sectionResults")}</span>{filtering&&<button type="button" onClick={clearFilters}><X size={14}/>{sectionT(locale,"clearFilters")}</button>}</div>
      {filteredSections.length?<div className="section-accordion">{filteredSections.map(section=>{const isOpen=openSections.has(section.id),panelId=`section-panel-${section.id}`,original=sections.find(item=>item.id===section.id);return <article className={`section-panel${isOpen?" open":""}`} key={section.id}><h2><button type="button" aria-expanded={isOpen} aria-controls={panelId} onClick={()=>toggle(section.id)}><span><b>{section.title||`${translate(locale,"section")} ${section.number}`}</b><small>{section.lessons.length} {translate(locale,"lessons")}</small></span><span className="section-toggle-label">{sectionT(locale,isOpen?"collapse":"expand")}</span><ChevronDown size={20} aria-hidden="true"/></button></h2>{isOpen&&<div className="section-lesson-grid" id={panelId}>{section.lessons.length?section.lessons.map(lesson=>{const lessonNumber=(original?.lessons.findIndex(item=>item.id===lesson.id)??0)+1;return <a className="section-lesson-card" href={lesson.path} onClick={event=>followPathLink(event,lesson.path)} key={lesson.id}><span className="section-lesson-number" aria-hidden="true">{String(lessonNumber).padStart(2,"0")}</span><span className="section-lesson-copy"><b>{lesson.name}</b><small><span>{lesson.sentenceCount} {sectionT(locale,"sentences")}</span><i aria-hidden="true"/><span>{translate(locale,"level")}: {lesson.level??sectionT(locale,"unknownLevel")}</span></small></span><ArrowRight size={17} aria-hidden="true"/></a>}):<p className="section-no-lessons">{translate(locale,"noLessons")}</p>}</div>}</article>;})}</div>:<div className="content-state section-empty"><Search size={24}/><p>{translate(locale,"noLessons")}</p><button type="button" onClick={clearFilters}>{sectionT(locale,"clearFilters")}</button></div>}
    </section>}
  </Shell>;
}

function LessonList({manifest,categorySlug,sectionId,locale,onHome}:{manifest?:LessonManifest;categorySlug:string;sectionId:string;locale:UiLocale;onHome:()=>void}){const items=manifest?.lessons.filter(x=>x.language==="en"&&x.categorySlug===categorySlug&&x.sectionId===sectionId);return <Shell locale={locale} onHome={onHome} title={translate(locale,"lessons")} breadcrumbs={[{label:translate(locale,"allTopics"),onClick:()=>navigate("/learn/en")},{label:formatCategory(categorySlug),onClick:()=>navigate(`/learn/en/${categorySlug}`)},{label:formatSection(sectionId,locale)}]}>{!items?<Loading locale={locale}/>:items.length?<div className="content-grid">{items.map(item=><a className="content-card" href={item.path} onClick={event=>followPathLink(event,item.path)} key={item.id}><span className="level-badge mint">{item.level??"—"}</span><h2>{item.name}</h2><small><Headphones size={14}/> {translate(locale,"sentences")}</small></a>)}</div>:<div className="content-state">{translate(locale,"noLessons")}</div>}</Shell>;}

function followHashLink(event:React.MouseEvent<HTMLAnchorElement>,path:string){if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();navigate(path);}
function followPathLink(event:React.MouseEvent<HTMLAnchorElement>,path:string){if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();navigateToPath(path);}

const guestKey=(lessonId:string)=>`me2listen-listening-progress-${lessonId}`;
function loadGuest(lessonId:string){try{return new Set<string>(JSON.parse(localStorage.getItem(guestKey(lessonId))??"[]") as string[]);}catch{return new Set<string>();}}

function DictationLesson({manifest,lessonSlug,lessonPath,locale,onHome}:{manifest?:LessonManifest;lessonSlug?:string;lessonPath?:{level:string;category:string;slug:string};locale:UiLocale;onHome:()=>void}){
  const auth=useAuth(),playerRef=useRef<AudioSegmentPlayerHandle>(null),textareaRef=useRef<HTMLTextAreaElement>(null),recognitionRef=useRef<BrowserSpeechRecognition|null>(null),[lesson,setLesson]=useState<ListeningLesson>(),[failed,setFailed]=useState(false),[index,setIndex]=useState(0),[typed,setTyped]=useState(""),[submitted,setSubmitted]=useState(false),[revealed,setRevealed]=useState(false),[completed,setCompleted]=useState<Set<string>>(new Set()),[attempts,setAttempts]=useState(0),[speed,setSpeed]=useState(1),[mode,setMode]=useState<"dictation"|"transcript">("dictation"),[transcriptTimeMs,setTranscriptTimeMs]=useState(0),[saving,setSaving]=useState(false),[progressError,setProgressError]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[speechListening,setSpeechListening]=useState(false),[speechError,setSpeechError]=useState<SpeechRecognitionErrorKind|null>(null),[speechPermissionDenied,setSpeechPermissionDenied]=useState(false),[preferences,setPreferences]=useState<ListeningPreferences>(()=>loadLocalListeningPreferences("guest"));
  useEffect(()=>{setFailed(false);const endpoint=lessonPath?`/api/listening/lessons/by-path?level=${encodeURIComponent(lessonPath.level)}&category=${encodeURIComponent(lessonPath.category)}&slug=${encodeURIComponent(lessonPath.slug)}`:`/api/listening/lessons/${encodeURIComponent(lessonSlug??"")}`;void getJson<{lesson:ListeningLesson}>(endpoint).then(({lesson:item})=>{setLesson(item);const local=loadGuest(item.id);setCompleted(local);if(auth.user)void getJson<{lesson:{current_sentence_position:number}|null;sentences:Array<{sentence_id:string;is_completed:boolean}>}>(`/api/listening/progress?lesson=${encodeURIComponent(item.id)}`).then(progress=>{const merged=new Set(local);progress.sentences.filter(x=>x.is_completed).forEach(x=>merged.add(x.sentence_id));setCompleted(merged);setIndex(Math.max(0,Math.min(item.sentences.length-1,(progress.lesson?.current_sentence_position??1)-1)));}).catch(()=>undefined);}).catch(()=>setFailed(true));},[lessonSlug,lessonPath?.level,lessonPath?.category,lessonPath?.slug,auth.user?.id]);
  useEffect(()=>{setTyped("");setSubmitted(false);setRevealed(false);setAttempts(0);setProgressError(false);},[index,lesson?.id]);
  useEffect(()=>{const recognition=recognitionRef.current;recognitionRef.current=null;abortSpeechRecognition(recognition);setSpeechListening(false);setSpeechError(null);},[index,lesson?.id,mode]);
  useEffect(()=>()=>{const recognition=recognitionRef.current;recognitionRef.current=null;abortSpeechRecognition(recognition);},[]);
  useEffect(()=>{if(auth.loading)return;setPreferences(auth.user?.listeningPreferences??loadLocalListeningPreferences("guest"));},[auth.loading,auth.user?.id,auth.user?.listeningPreferences]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null,inSettings=Boolean(target?.closest(".listening-settings-dialog")),isFormControl=target?.matches("textarea,input,select,button");if(inSettings||event.repeat)return;if(event.key==="Escape"){const skipButton=document.querySelector<HTMLButtonElement>(".skip-answer-button");if(skipButton){event.preventDefault();skipButton.click();}return;}if(event.key==="Enter"&&!event.shiftKey&&!isFormControl){const checkButton=document.querySelector<HTMLButtonElement>(".check-answer-button:not(:disabled)");if(checkButton){event.preventDefault();checkButton.click();return;}}if(matchesReplayShortcut(event,preferences.replayKey)){event.preventDefault();playerRef.current?.replay();}else if(!isFormControl&&event.code===preferences.playPauseKey){event.preventDefault();playerRef.current?.toggle();}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[preferences.playPauseKey,preferences.replayKey]);
  if(failed)return <Shell locale={locale} onHome={onHome} title="English"><LoadError locale={locale} retry={()=>location.reload()}/></Shell>;if(!lesson)return <Loading locale={locale}/>;if(!lesson.sentences.length)return <Shell locale={locale} onHome={onHome} title={lesson.title}><div className="content-state">{translate(locale,"noLessons")}</div></Shell>;
  const SpeechRecognition=getSpeechRecognitionConstructor(),speechLocale=getSpeechRecognitionLocale(lesson.language_code),speechLanguageUnavailable=speechError==="languageUnsupported",speechAvailable=Boolean(SpeechRecognition&&speechLocale&&!speechLanguageUnavailable),speechButtonLabel=speechListening?speechRecognitionT(locale,"stop"):!SpeechRecognition?speechRecognitionT(locale,"unsupported"):!speechLocale||speechLanguageUnavailable?speechRecognitionT(locale,"languageUnsupported"):speechPermissionDenied?speechRecognitionT(locale,"permission"):speechRecognitionT(locale,"start");
  const cancelSpeechRecognition=()=>{const recognition=recognitionRef.current;recognitionRef.current=null;abortSpeechRecognition(recognition);setSpeechListening(false);};
  const toggleSpeechRecognition=()=>{
    const active=recognitionRef.current;
    if(active){try{active.stop();}catch{cancelSpeechRecognition();}return;}
    if(!SpeechRecognition||!speechLocale||speechPermissionDenied)return;
    const recognition=new SpeechRecognition(),baseText=typed;
    recognition.lang=speechLocale;recognition.continuous=false;recognition.interimResults=true;recognition.maxAlternatives=1;recognitionRef.current=recognition;
    recognition.onstart=()=>{if(recognitionRef.current===recognition)setSpeechListening(true);};
    recognition.onresult=event=>{if(recognitionRef.current!==recognition)return;const recognized=collectRecognizedSpeech(event.results,lesson.language_code);setTyped(mergeRecognizedSpeech(baseText,recognized,lesson.language_code));setSubmitted(false);setSpeechError(null);};
    recognition.onerror=event=>{if(recognitionRef.current!==recognition)return;const kind=classifySpeechRecognitionError(event.error);recognitionRef.current=null;abortSpeechRecognition(recognition);if(kind==="permission")setSpeechPermissionDenied(true);if(kind)setSpeechError(kind);setSpeechListening(false);};
    recognition.onend=()=>{if(recognitionRef.current===recognition){recognitionRef.current=null;setSpeechListening(false);}};
    setSpeechError(null);
    try{recognition.start();setSpeechListening(true);}catch{cancelSpeechRecognition();setSpeechError("unknown");}
  };
  const sentence=lesson.sentences[index],evaluation=evaluateAnswer({expected:sentence.transcript,actual:typed,language:"en"}),isDone=completed.has(sentence.id),accepted=isDone||revealed||(submitted&&evaluation.correct),percent=Math.round(completed.size/lesson.sentences.length*100),activeTranscriptIndex=findActiveTranscriptIndex(lesson.sentences,transcriptTimeMs),nextLesson=findNextLesson(manifest,lesson.id);
  const complete=async()=>{if(isDone)return;setProgressError(false);const next=new Set(completed).add(sentence.id);setCompleted(next);localStorage.setItem(guestKey(lesson.id),JSON.stringify([...next]));if(auth.user){setSaving(true);try{await auth.saveListeningProgress({lessonId:lesson.id,sentenceId:sentence.id,position:sentence.position,attemptCount:attempts+1,firstTryCorrect:attempts===0});}catch{/* local progress remains usable and can be retried */}finally{setSaving(false);}}};
  const submit=()=>{if(!typed.trim())return;setSubmitted(true);if(evaluation.correct)void complete();else setAttempts(value=>value+1);};
  const moveToSentence=(targetIndex:number)=>{if(targetIndex<0||targetIndex>=lesson.sentences.length||targetIndex===index)return;setIndex(targetIndex);};
  const next=()=>{if(!accepted)return;if(index===lesson.sentences.length-1){navigate(`/learn/en/${lesson.category_slug}/${lesson.section_id}`);return;}moveToSentence(index+1);};
  const skip=()=>{setTyped(sentence.transcript);setSubmitted(true);setRevealed(true);};
  const retryAnswer=async()=>{
    if(!isDone||saving)return;
    cancelSpeechRecognition();setProgressError(false);
    const previous=new Set(completed),nextCompleted=new Set(completed);nextCompleted.delete(sentence.id);setCompleted(nextCompleted);localStorage.setItem(guestKey(lesson.id),JSON.stringify([...nextCompleted]));setTyped("");setSubmitted(false);setRevealed(false);setAttempts(0);
    try{if(auth.user){setSaving(true);await auth.resetListeningProgress({lessonId:lesson.id,sentenceId:sentence.id,position:sentence.position});}requestAnimationFrame(()=>textareaRef.current?.focus());}
    catch{setCompleted(previous);localStorage.setItem(guestKey(lesson.id),JSON.stringify([...previous]));setProgressError(true);}
    finally{setSaving(false);}
  };
  const savePreferences=async(nextPreferences:ListeningPreferences)=>{if(auth.user)await auth.saveListeningPreferences(nextPreferences);else saveLocalListeningPreferences("guest",nextPreferences);setPreferences(nextPreferences);};
  const onEnter=(event:React.KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key!=="Enter"||event.shiftKey)return;event.preventDefault();if(accepted)next();else if(!submitted)submit();};
  return <div className="dictation-shell">
    <main className="lesson-practice-page">
      <button type="button" className="lesson-back-button" onClick={()=>navigate(`/learn/en/${lesson.category_slug}/${lesson.section_id}`)}><ArrowLeft size={16}/>{translate(locale,"backLibrary")}</button>
      <div className="lesson-practice-heading"><div><h1>{lesson.title}</h1><span>{lessonT(locale,"vocabLevel")}: <b>{lesson.level??sectionT(locale,"unknownLevel")}</b></span></div><div className="lesson-completion"><span>{completed.size}/{lesson.sentences.length} {translate(locale,"sentences")}</span><div><i style={{width:`${percent}%`}}/></div></div></div>
      <div className="mode-tabs lesson-mode-tabs" aria-label={translate(locale,"learningExperience")}><button type="button" aria-pressed={mode==="dictation"} className={`dictation-tab${mode==="dictation"?" active":""}`} onClick={()=>setMode("dictation")}><Headphones size={16}/><span>{lessonT(locale,"dictationTab")}</span></button><button type="button" aria-pressed={mode==="transcript"} className={`transcript-tab${mode==="transcript"?" active":""}`} onClick={()=>setMode("transcript")}><BookOpen size={16}/><span>{lessonT(locale,"transcriptTab")}</span></button></div>
      {mode==="transcript"?<section className="lesson-practice-card full-transcript-view">{lesson.audio_url&&<audio aria-label={lessonT(locale,"fullLessonAudio")} controls preload="metadata" src={lesson.audio_url} onLoadedMetadata={()=>setTranscriptTimeMs(0)} onTimeUpdate={event=>setTranscriptTimeMs(event.currentTarget.currentTime*1000)} onSeeked={event=>setTranscriptTimeMs(event.currentTarget.currentTime*1000)}/>}<ol>{lesson.sentences.map((item,itemIndex)=>{const isCurrent=itemIndex===activeTranscriptIndex;return <li className={isCurrent?"current":""} aria-current={isCurrent?"step":undefined} key={item.id}><span>{itemIndex+1}</span><p>{item.transcript}</p></li>})}</ol></section>:<section className="lesson-practice-card">
        <div className="practice-toolbar"><nav aria-label={lessonT(locale,"sentenceProgress")}><button type="button" disabled={index===0} aria-label={lessonT(locale,"previousSentence")} onClick={()=>moveToSentence(index-1)}><ArrowLeft size={17}/></button><strong>{index+1} <span>/ {lesson.sentences.length}</span></strong><button type="button" disabled={index===lesson.sentences.length-1} aria-label={lessonT(locale,"nextSentence")} onClick={()=>moveToSentence(index+1)}><ArrowRight size={17}/></button></nav><div className="playback-options"><button type="button" className="playback-settings-button" onClick={()=>setSettingsOpen(true)}><Settings2 size={15}/>{lessonT(locale,"settings")}</button><select aria-label={translate(locale,"playbackSpeed")} value={speed} onChange={event=>setSpeed(Number(event.target.value))}>{[.5,.75,1,1.25,1.5].map(value=><option key={value} value={value}>{value}×</option>)}</select></div></div>
        <div className="sentence-progress"><i style={{width:`${(index+1)/lesson.sentences.length*100}%`}}/></div>
        <div className="practice-audio">{lesson.audio_url?<AudioSegmentPlayer ref={playerRef} locale={locale} src={lesson.audio_url} startMs={sentence.start_ms} endMs={sentence.end_ms} playbackRate={speed} repeat={preferences.autoReplay} repeatDelayMs={preferences.replayDelaySeconds*1000}/>:<div className="audio-error" role="alert">{translate(locale,"audioUnavailable")}</div>}</div>{preferences.shortcutTips&&<div className="shortcut-key-tips"><span><kbd>{shortcutLabel(preferences.playPauseKey)}</kbd>{lessonT(locale,"playPauseShortcut")}</span><span><kbd>{shortcutLabel(preferences.replayKey)}</kbd>{lessonT(locale,"replayShortcut")}</span></div>}
        <div className={`dictation-workspace${accepted?" answer-visible":""}`}>
          <div className="dictation-entry">
            <label htmlFor="listening-answer">{translate(locale,"typePrompt")}</label>
            <div className="answer-input-wrap">
              <textarea ref={textareaRef} id="listening-answer" value={accepted?sentence.transcript:typed} readOnly={accepted} autoComplete={preferences.wordSuggestions?"on":"off"} autoCorrect={preferences.wordSuggestions?"on":"off"} spellCheck={preferences.wordSuggestions} onChange={event=>{cancelSpeechRecognition();setTyped(event.target.value);setSubmitted(false);}} onKeyDown={onEnter} placeholder={translate(locale,"typePlaceholder")} autoFocus={window.innerWidth>780}/>
              {isDone&&<button type="button" className="retry-answer-button" disabled={saving} title={lessonT(locale,"retryAnswer")} aria-label={lessonT(locale,"retryAnswer")} onClick={()=>void retryAnswer()}><RotateCcw size={16}/></button>}
              <button type="button" className={`microphone-placeholder${speechListening?" listening":""}`} disabled={accepted||!speechAvailable||speechPermissionDenied} title={speechButtonLabel} aria-label={speechButtonLabel} aria-pressed={speechListening} aria-describedby={speechListening||speechError?"speech-recognition-status":undefined} onClick={toggleSpeechRecognition}><Mic size={17}/></button>
            </div>
            {(speechListening||speechError)&&<p id="speech-recognition-status" className={`speech-recognition-status${speechError?" error":""}`} role={speechError?"alert":"status"}>{speechRecognitionT(locale,speechError??"listening")}</p>}
            {progressError&&<p className="progress-reset-error" role="alert">{lessonT(locale,"retryAnswerError")}</p>}
            {submitted&&!accepted&&<div className="word-result" aria-live="polite">{evaluation.tokens.map((token,i)=><span key={`${token.text}-${i}`} className={token.status}>{token.status==="hidden"?"*****":token.text}</span>)}</div>}
            <div className="answer-footer">
              <span>{saving?translate(locale,"saving"):accepted?(revealed?lessonT(locale,"revealedAnswer"):translate(locale,"correctMessage")):translate(locale,"caseHint")}</span>
              <div>{!accepted?<>
                {!submitted&&<span className="shortcut-tooltip"><button type="button" className="primary-button check-answer-button" aria-describedby="check-answer-tooltip" disabled={!typed.trim()} onClick={submit}>{translate(locale,"check")}</button><span id="check-answer-tooltip" className="shortcut-tooltip-content" role="tooltip">{lessonT(locale,"checkShortcut")}</span></span>}
                <span className="shortcut-tooltip"><button type="button" className="skip-button skip-answer-button" aria-describedby="skip-answer-tooltip" onClick={skip}>{translate(locale,"skip")}</button><span id="skip-answer-tooltip" className="shortcut-tooltip-content" role="tooltip">{lessonT(locale,"skipShortcut")}</span></span>
              </>:<button type="button" className="primary-button" onClick={next}>{translate(locale,"next")}<ArrowRight size={16}/></button>}</div>
            </div>
          </div>
          <aside className="answer-insight" aria-live="polite" hidden={!accepted}>{accepted&&<><LessonTranslationPanel lessonId={lesson.id} sentenceId={sentence.id} locale={locale}/><section><h2>{lessonT(locale,"pronunciation")}</h2><div className="pronunciation-words">{sentence.transcript.split(/\s+/u).map((word,wordIndex)=><span key={`${word}-${wordIndex}`}>{word}</span>)}</div><small>{lessonT(locale,"pronunciationHint")}</small></section></>}</aside>
        </div>
      </section>}
      <aside className="lesson-tip"><Lightbulb size={19}/><div><b>{lessonT(locale,"listeningTip")}</b><p>{lessonT(locale,"listeningTipText")}</p></div></aside>
      {nextLesson&&<a className="next-lesson-card" href={nextLesson.path} onClick={event=>followPathLink(event,nextLesson.path)}><span className="next-lesson-icon" aria-hidden="true"><Headphones size={21}/></span><span className="next-lesson-copy"><small>{lessonT(locale,"nextLesson")}</small><strong>{nextLesson.name}</strong><span>{nextLesson.categoryName} · {nextLesson.sectionTitle}{nextLesson.level?` · ${lessonT(locale,"vocabLevel")}: ${nextLesson.level}`:""} · {nextLesson.sentenceCount} {translate(locale,"sentences")}</span></span><ArrowRight className="next-lesson-arrow" size={21}/></a>}
    </main>{settingsOpen&&<ListeningSettingsDialog locale={locale} preferences={preferences} onClose={()=>setSettingsOpen(false)} onSave={savePreferences}/>}
  </div>;
}

function LegacyAdminListeningPage({onHome}:{onHome:()=>void}){
  const auth=useAuth(),[sections,setSections]=useState<Array<{section_id:string;category_name:string;section_title:string}>>([]),[file,setFile]=useState<File>(),[transcript,setTranscript]=useState(""),[timing,setTiming]=useState(""),[importMode,setImportMode]=useState<"ai"|"pre_timed">("ai"),[title,setTitle]=useState(""),[level,setLevel]=useState("A1"),[sectionId,setSectionId]=useState(""),[lessonId,setLessonId]=useState(""),[review,setReview]=useState<ReviewSentence[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(auth.user?.isAdmin)void getJson<{sections:typeof sections}>("/api/listening/admin/bootstrap").then(x=>{setSections(x.sections);setSectionId(x.sections[0]?.section_id??"");}).catch(()=>setError("Unable to load admin data."));},[auth.user?.isAdmin]);
  if(auth.loading)return <Loading/>;if(!auth.user?.isAdmin)return <Shell onHome={onHome} title="Content management"><div className="content-state">Administrator access is required.</div></Shell>;
  const process=async()=>{if(!file)return;setBusy(true);setError("");try{const durationMs=await mediaDuration(file);const form=new FormData();form.set("audio",file);form.set("transcript",transcript);form.set("timing",timing);form.set("importMode",importMode);form.set("title",title);form.set("level",level);form.set("sectionId",sectionId);form.set("durationMs",String(durationMs));const result=await auth.adminImportLesson(form);setLessonId(result.lessonId);setReview((result.sentences as ReviewSentence[]));}catch(reason){setError(reason instanceof Error?reason.message:"Import failed");}finally{setBusy(false);}};
  const publish=async()=>{setBusy(true);setError("");try{await auth.adminReviewLesson(lessonId,{publish:true,sentences:review});setLessonId("");setReview([]);}catch(reason){setError(reason instanceof Error?reason.message:"Publish failed");}finally{setBusy(false);}};
  return <Shell onHome={onHome} title="Listening content management">{error&&<p className="form-error" role="alert">{error}</p>} {!lessonId?<form className="admin-import" onSubmit={event=>{event.preventDefault();void process();}}><label>Section<select value={sectionId} onChange={e=>setSectionId(e.target.value)}>{sections.map(item=><option key={item.section_id} value={item.section_id}>{item.category_name} · {item.section_title}</option>)}</select></label><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/><small>Slug sẽ được tự động tạo từ Title.</small></label><label>Level<input value={level} onChange={e=>setLevel(e.target.value)}/></label><label>Audio<input required type="file" accept="audio/*" onChange={e=>setFile(e.target.files?.[0])}/></label><label>Transcript, one sentence per line<textarea required value={transcript} onChange={e=>setTranscript(e.target.value)}/></label><button className="primary-button" disabled={busy||!file}>{busy?"Processing…":"Process"}</button></form>:<div className="alignment-review">{review.map((item,index)=><fieldset key={item.id}><legend>Sentence {item.position}</legend><button type="button" onClick={()=>file&&playFileSegment(file,item.startMs,item.endMs)}>▶</button><input type="number" value={item.startMs} onChange={e=>setReview(rows=>rows.map((row,i)=>i===index?{...row,startMs:Number(e.target.value)}:row))}/><span>→</span><input type="number" value={item.endMs} onChange={e=>setReview(rows=>rows.map((row,i)=>i===index?{...row,endMs:Number(e.target.value)}:row))}/><textarea value={item.text} onChange={e=>setReview(rows=>rows.map((row,i)=>i===index?{...row,text:e.target.value}:row))}/></fieldset>)}<button className="primary-button" disabled={busy} onClick={()=>void publish()}>{busy?"Publishing…":"Publish"}</button></div>}</Shell>;
}

function LegacyLessonManagementPage({onHome}:{onHome:()=>void}){
  const auth=useAuth(),[items,setItems]=useState<Array<{id:string;title:string;slug:string;path:string;level:string|null;is_published:boolean;updated_at:string}>>([]),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[error,setError]=useState("");
  const load=()=>{if(!auth.user?.isAdmin)return;void getJson<{lessons:typeof items}>(`/api/listening/admin/lessons?q=${encodeURIComponent(query)}&status=${status}`).then(x=>setItems(x.lessons)).catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load lessons."));};
  useEffect(load,[auth.user?.isAdmin,query,status]);
  if(auth.loading)return <Loading/>;if(!auth.user?.isAdmin)return <Shell onHome={onHome} title="Lesson management"><div className="content-state">Administrator access is required.</div></Shell>;
  return <Shell onHome={onHome} title="Lesson management"><p><button type="button" onClick={onHome}>Home</button></p><div className="admin-filters"><input aria-label="Search lessons" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title or slug"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Draft</option></select></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="admin-lesson-list">{items.map(item=><article key={item.id}><a href={item.is_published?item.path:`/api/listening/admin/lessons/${item.id}`}>{item.title}</a><small>{item.slug} · {item.level??"—"} · {item.is_published?"Published":"Draft"}</small><button type="button" onClick={()=>{if(window.confirm(`Delete ${item.title}?`))void auth.adminDeleteLesson(item.id).then(load).catch(reason=>setError(reason instanceof Error?reason.message:"Delete failed."));}}>Delete</button></article>)}</div></Shell>;
}

function LegacyAdminListeningPage2({onHome}:{onHome:()=>void}){
  const auth=useAuth();
  const [sections,setSections]=useState<Array<{section_id:string;category_name:string;section_title:string}>>([]);
  const [file,setFile]=useState<File>();
  const [transcript,setTranscript]=useState("");
  const [timing,setTiming]=useState(""),[srtFile,setSrtFile]=useState<File>();
  const [importMode,setImportMode]=useState<"ai"|"pre_timed">("ai");
  const [title,setTitle]=useState("");
  const [level,setLevel]=useState("A1");
  const [sectionId,setSectionId]=useState("");
  const [lessonId,setLessonId]=useState("");
  const [review,setReview]=useState<ReviewSentence[]>([]);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  useEffect(()=>{if(auth.user?.isAdmin)void getJson<{sections:typeof sections}>("/api/listening/admin/bootstrap").then(x=>{setSections(x.sections);setSectionId(x.sections[0]?.section_id??"");}).catch(()=>setError("Unable to load admin data."));},[auth.user?.isAdmin]);
  if(auth.loading)return <Loading/>;
  if(!auth.user?.isAdmin)return <Shell onHome={onHome} title="Content management"><div className="content-state">Administrator access is required.</div></Shell>;
  const process=async()=>{if(!file)return;setBusy(true);setError("");try{const durationMs=await mediaDuration(file),srt=importMode==="pre_timed"?(srtFile?await srtFile.text():timing):"";const form=new FormData();form.set("audio",file);form.set("transcript",transcript);form.set("importMode",importMode);if(importMode==="pre_timed")form.set("timing",srt);form.set("title",title);form.set("level",level);form.set("sectionId",sectionId);form.set("durationMs",String(durationMs));const result=await auth.adminImportLesson(form);setLessonId(result.lessonId);setReview(result.sentences as ReviewSentence[]);}catch(reason){setError(reason instanceof Error?reason.message:"Import failed");}finally{setBusy(false);}};
  const publish=async()=>{setBusy(true);setError("");try{await auth.adminReviewLesson(lessonId,{publish:true,sentences:review});setLessonId("");setReview([]);setFile(undefined);setTranscript("");setTiming("");setTitle("");}catch(reason){setError(reason instanceof Error?reason.message:"Publish failed");}finally{setBusy(false);}};
  return <Shell onHome={onHome} title="Listening content management"><p><a href="#/admin/listening/manage">Manage existing lessons</a></p>{error&&<p className="form-error" role="alert">{error}</p>}{!lessonId?<form className="admin-import" onSubmit={event=>{event.preventDefault();void process();}}><label>Import mode<select value={importMode} onChange={event=>setImportMode(event.target.value as "ai"|"pre_timed")}><option value="ai">AI Timing Import</option><option value="pre_timed">Pre-timed Script Import</option></select></label><label>Section<select required value={sectionId} onChange={event=>setSectionId(event.target.value)}>{sections.map(item=><option key={item.section_id} value={item.section_id}>{item.category_name} · {item.section_title}</option>)}</select></label><label>Title<input required maxLength={200} value={title} onChange={event=>setTitle(event.target.value)}/><small>Slug is generated automatically from Title.</small></label><label>Level<input maxLength={30} value={level} onChange={event=>setLevel(event.target.value)}/></label><label>Audio<input required type="file" accept="audio/*" onChange={event=>setFile(event.target.files?.[0])}/></label><label>Transcript, one sentence per line<textarea required maxLength={50000} value={transcript} onChange={event=>setTranscript(event.target.value)}/></label>{importMode==="pre_timed"&&<label>Timing JSON<textarea required value={timing} onChange={event=>setTiming(event.target.value)} placeholder='[{"startMs":0,"endMs":1200},{"startMs":1200,"endMs":2500}]'/><small>Provide exactly one timing segment for each non-empty transcript line. AI will not be called.</small></label>}<button className="primary-button" disabled={busy||!file||!sectionId}>{busy?"Processing…":"Process"}</button></form>:<div className="alignment-review">{review.map((item,index)=><fieldset key={item.id}><legend>Sentence {item.position}</legend><button type="button" onClick={()=>file&&playFileSegment(file,item.startMs,item.endMs)}>▶</button><input aria-label={`Sentence ${item.position} start`} type="number" min={0} value={item.startMs} onChange={event=>setReview(rows=>rows.map((row,i)=>i===index?{...row,startMs:Number(event.target.value)}:row))}/><span>→</span><input aria-label={`Sentence ${item.position} end`} type="number" min={1} value={item.endMs} onChange={event=>setReview(rows=>rows.map((row,i)=>i===index?{...row,endMs:Number(event.target.value)}:row))}/><textarea value={item.text} onChange={event=>setReview(rows=>rows.map((row,i)=>i===index?{...row,text:event.target.value}:row))}/></fieldset>)}<button className="primary-button" disabled={busy} onClick={()=>void publish()}>{busy?"Publishing…":"Publish"}</button></div>}</Shell>;
}

interface ManagedLesson {id:string;title:string;slug:string;path:string;level:string|null;description:string|null;sort_order:number;section_id:string;section_title:string;category_name:string;language_code:string;is_published:boolean;updated_at:string;sentences?:ReviewSentence[];}

export function LessonManagementPage({onHome,locale}:{onHome:()=>void;locale:UiLocale}){
  const auth=useAuth();
  const title=adminSystemT(locale,"lessonsTitle");
  const t=(key:Parameters<typeof lessonManagementT>[1],values?:Record<string,string|number>)=>lessonManagementT(locale,key,values);
  const [items,setItems]=useState<ManagedLesson[]>([]),[sections,setSections]=useState<Array<{section_id:string;category_name:string;section_title:string}>>([]),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[language,setLanguage]=useState("all"),[selected,setSelected]=useState<ManagedLesson>(),[sentencesJson,setSentencesJson]=useState("[]"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=()=>{if(!auth.user?.isAdmin)return;void Promise.all([getJson<{lessons:ManagedLesson[]}>(`/api/listening/admin/lessons?q=${encodeURIComponent(query)}&status=${encodeURIComponent(status)}&language=${encodeURIComponent(language)}`),getJson<{sections:typeof sections}>("/api/listening/admin/bootstrap")]).then(([lessonData,bootstrap])=>{setItems(lessonData.lessons);setSections(bootstrap.sections);setError("");}).catch(()=>setError(t("loadError")));};
  useEffect(load,[auth.user?.isAdmin,query,status,language]);
  if(auth.loading)return <AdminLayout locale={locale} title={title} onSiteHome={onHome}><div className="admin-state">{adminSystemT(locale,"loading")}</div></AdminLayout>;
  if(!auth.user?.isAdmin)return <AdminLayout locale={locale} title={title} onSiteHome={onHome}><div className="admin-state">{adminSystemT(locale,"adminRequired")}</div></AdminLayout>;
  const open=async(id:string)=>{setBusy(true);setError("");try{const result=await getJson<{lesson:ManagedLesson}>(`/api/listening/admin/lessons/${encodeURIComponent(id)}`);setSelected(result.lesson);setSentencesJson(JSON.stringify(result.lesson.sentences??[],null,2));}catch{setError(t("openError"));}finally{setBusy(false);}};
  const save=async()=>{if(!selected)return;setBusy(true);setError("");try{const sentences=JSON.parse(sentencesJson) as unknown;await auth.adminUpdateLesson(selected.id,{title:selected.title,slug:selected.slug,level:selected.level,description:selected.description,sortOrder:selected.sort_order,sectionId:selected.section_id,sentences});setSelected(undefined);load();}catch{setError(t("updateError"));}finally{setBusy(false);}};
  const remove=async(item:ManagedLesson)=>{if(!window.confirm(t("deleteConfirm",{title:item.title})))return;setBusy(true);setError("");try{await auth.adminDeleteLesson(item.id);if(selected?.id===item.id)setSelected(undefined);load();}catch{setError(t("deleteError"));}finally{setBusy(false);}};
  return <AdminLayout locale={locale} title={title} onSiteHome={onHome}>
    <button className="admin-inline-link" type="button" onClick={()=>navigate("/admin/listening")}>{adminSystemT(locale,"importTitle")}</button>
    <div className="admin-filters"><input aria-label={t("searchLessons")} value={query} onChange={event=>setQuery(event.target.value)} placeholder={t("searchPlaceholder")}/><select aria-label={t("status")} value={status} onChange={event=>setStatus(event.target.value)}><option value="all">{t("allStatuses")}</option><option value="published">{t("published")}</option><option value="draft">{t("draft")}</option></select><select aria-label={t("language")} value={language} onChange={event=>setLanguage(event.target.value)}><option value="all">{t("allLanguages")}</option><option value="en">{t("english")}</option><option value="zh">{t("chinese")}</option><option value="ja">{t("japanese")}</option></select></div>
    {error&&<p className="form-error" role="alert">{error}</p>}
    {selected?<form className="admin-import" onSubmit={event=>{event.preventDefault();void save();}}><label>{t("lessonId")}<input readOnly value={selected.id}/></label><label>{t("title")}<input required value={selected.title} onChange={event=>setSelected({...selected,title:event.target.value})}/></label><label>{t("slug")}<input required value={selected.slug} onChange={event=>setSelected({...selected,slug:event.target.value})}/></label><label>{t("level")}<input value={selected.level??""} onChange={event=>setSelected({...selected,level:event.target.value})}/></label><label>{t("description")}<textarea value={selected.description??""} onChange={event=>setSelected({...selected,description:event.target.value})}/></label><label>{t("placement")}<select value={selected.section_id} onChange={event=>setSelected({...selected,section_id:event.target.value})}>{sections.map(item=><option key={item.section_id} value={item.section_id}>{item.category_name} · {item.section_title}</option>)}</select></label><label>{t("order")}<input type="number" min={0} value={selected.sort_order} onChange={event=>setSelected({...selected,sort_order:Number(event.target.value)})}/></label><label>{t("scriptJson")}<textarea required value={sentencesJson} onChange={event=>setSentencesJson(event.target.value)}/><small>{t("scriptHint")}</small></label><div><button type="button" onClick={()=>setSelected(undefined)}>{t("cancel")}</button><button className="primary-button" disabled={busy}>{t("saveChanges")}</button></div></form>:<div className="admin-lesson-list">{items.map(item=><article key={item.id}><button type="button" disabled={busy} onClick={()=>void open(item.id)}>{item.title}</button><small>{item.id} · {item.path} · {item.level??"—"} · {t(item.is_published?"published":"draft")} · {new Date(item.updated_at).toLocaleString(localeTags[locale])}</small>{item.is_published&&<a href={item.path} onClick={event=>followPathLink(event,item.path)}>{t("open")}</a>}<button type="button" disabled={busy} onClick={()=>void remove(item)}>{t("delete")}</button></article>)}</div>}
  </AdminLayout>;
}

function mediaDuration(file:File){return new Promise<number>((resolve,reject)=>{const audio=new Audio(),url=URL.createObjectURL(file);audio.preload="metadata";audio.onloadedmetadata=()=>{const duration=Math.round(audio.duration*1000);URL.revokeObjectURL(url);Number.isFinite(duration)&&duration>0?resolve(duration):reject(new Error("Invalid audio duration"));};audio.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("Audio metadata could not be read"));};audio.src=url;});}
function playFileSegment(file:File,startMs:number,endMs:number){const audio=new Audio(URL.createObjectURL(file));audio.currentTime=startMs/1000;void audio.play();const stop=()=>{if(audio.currentTime>=endMs/1000){audio.pause();URL.revokeObjectURL(audio.src);}else requestAnimationFrame(stop);};requestAnimationFrame(stop);}

function LegacyAdminListeningPage3({onHome}:{onHome:()=>void}){
  const auth=useAuth(),[sections,setSections]=useState<Array<{section_id:string;category_name:string;section_title:string}>>([]),[file,setFile]=useState<File>(),[srtFile,setSrtFile]=useState<File>(),[transcript,setTranscript]=useState(""),[srt,setSrt]=useState(""),[importMode,setImportMode]=useState<"ai"|"pre_timed">("ai"),[title,setTitle]=useState(""),[level,setLevel]=useState("A1"),[sectionId,setSectionId]=useState(""),[lessonId,setLessonId]=useState(""),[review,setReview]=useState<ReviewSentence[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{if(auth.user?.isAdmin)void getJson<{sections:typeof sections}>("/api/listening/admin/bootstrap").then(x=>{setSections(x.sections);setSectionId(x.sections[0]?.section_id??"");}).catch(()=>setError("Unable to load admin data."));},[auth.user?.isAdmin]);
  if(auth.loading)return <Loading/>;if(!auth.user?.isAdmin)return <Shell onHome={onHome} title="Content management"><div className="content-state">Administrator access is required.</div></Shell>;
  const process=async()=>{if(!file)return;setBusy(true);setError("");try{const durationMs=await mediaDuration(file),srtText=importMode==="pre_timed"?(srtFile?await srtFile.text():srt):"";const form=new FormData();form.set("audio",file);form.set("transcript",transcript);form.set("importMode",importMode);if(importMode==="pre_timed")form.set("srt",srtText);form.set("title",title);form.set("level",level);form.set("sectionId",sectionId);form.set("durationMs",String(durationMs));const result=await auth.adminImportLesson(form);setLessonId(result.lessonId);setReview(result.sentences as ReviewSentence[]);}catch(reason){setError(reason instanceof Error?reason.message:"Import failed");}finally{setBusy(false);}};
  const publish=async()=>{setBusy(true);setError("");try{await auth.adminReviewLesson(lessonId,{publish:true,sentences:review});setLessonId("");setReview([]);}catch(reason){setError(reason instanceof Error?reason.message:"Publish failed");}finally{setBusy(false);}};
  return <Shell onHome={onHome} title="Listening content management"><p><a href="#/admin/listening/manage">Manage existing lessons</a></p>{error&&<p className="form-error" role="alert">{error}</p>}{!lessonId?<form className="admin-import" onSubmit={event=>{event.preventDefault();void process();}}><label>Import mode<select value={importMode} onChange={event=>setImportMode(event.target.value as "ai"|"pre_timed")}><option value="ai">AI Timing Import</option><option value="pre_timed">Pre-timed SRT Import</option></select></label><label>Section<select required value={sectionId} onChange={event=>setSectionId(event.target.value)}>{sections.map(item=><option key={item.section_id} value={item.section_id}>{item.category_name} · {item.section_title}</option>)}</select></label><label>Title<input required maxLength={200} value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Level<input maxLength={30} value={level} onChange={event=>setLevel(event.target.value)}/></label><label>Audio<input required type="file" accept="audio/*" onChange={event=>setFile(event.target.files?.[0])}/></label><label>Transcript<textarea required maxLength={50000} value={transcript} onChange={event=>setTranscript(event.target.value)}/></label>{importMode==="pre_timed"&&<><label>SRT file (optional)<input type="file" accept=".srt,application/x-subrip,text/plain" onChange={event=>setSrtFile(event.target.files?.[0])}/><small>Choose an SRT file or paste SRT below.</small></label><label>Pre-timed SRT<textarea required={!srtFile} value={srt} onChange={event=>setSrt(event.target.value)} placeholder={'1\n00:00:00,000 --> 00:00:01,200\nFirst sentence.\n\n2\n00:00:01,200 --> 00:00:02,500\nSecond sentence.'}/><small>One SRT cue per non-empty transcript line. AI is not called.</small></label></>}<button className="primary-button" disabled={busy||!file||!sectionId}>{busy?"Processing…":"Process"}</button></form>:<div className="alignment-review">{review.map((item,index)=><fieldset key={item.id}><legend>Sentence {item.position}</legend><button type="button" onClick={()=>file&&playFileSegment(file,item.startMs,item.endMs)}>▶</button><input type="number" min={0} value={item.startMs} onChange={event=>setReview(rows=>rows.map((row,i)=>i===index?{...row,startMs:Number(event.target.value)}:row))}/><input type="number" min={1} value={item.endMs} onChange={event=>setReview(rows=>rows.map((row,i)=>i===index?{...row,endMs:Number(event.target.value)}:row))}/><textarea value={item.text} onChange={event=>setReview(rows=>rows.map((row,i)=>i===index?{...row,text:event.target.value}:row))}/></fieldset>)}<button className="primary-button" disabled={busy} onClick={()=>void publish()}>{busy?"Publishing…":"Publish"}</button></div>}</Shell>;
}

export function AdminListeningPage({onHome,locale}:{onHome:()=>void;locale:UiLocale}){return <LessonImportPage onHome={onHome} locale={locale}/>;}
