import type { UiLocale } from "./types";
import type { SpeechRecognitionErrorKind } from "./lib/speechRecognition";

const messages = {
  en: { start: "Speak your answer", stop: "Stop listening", listening: "Listening… Speak your answer.", unsupported: "Speech input is not supported by this browser.", languageUnsupported: "Speech input is not available for this learning language.", permission: "Microphone access is blocked. Allow Microphone in this site's browser permissions, then try again.", noSpeech: "No speech was detected. Try again or type your answer.", audioCapture: "No microphone is available. You can continue typing your answer.", network: "Speech recognition could not connect. Try again or type your answer.", unknown: "Speech recognition could not complete. Your answer has been preserved." },
  vi: { start: "Đọc câu trả lời", stop: "Dừng nghe", listening: "Đang nghe… Hãy đọc câu trả lời.", unsupported: "Trình duyệt này không hỗ trợ nhập bằng giọng nói.", languageUnsupported: "Chưa hỗ trợ nhập bằng giọng nói cho ngôn ngữ đang học.", permission: "Quyền truy cập micro đang bị chặn. Hãy cho phép Microphone trong quyền của trang trên trình duyệt rồi thử lại.", noSpeech: "Không phát hiện giọng nói. Hãy thử lại hoặc nhập câu trả lời.", audioCapture: "Không tìm thấy micro. Bạn vẫn có thể nhập câu trả lời.", network: "Nhận dạng giọng nói không thể kết nối. Hãy thử lại hoặc nhập câu trả lời.", unknown: "Không thể hoàn tất nhận dạng giọng nói. Câu trả lời hiện có vẫn được giữ nguyên." },
  zh: { start: "说出答案", stop: "停止聆听", listening: "正在聆听… 请说出答案。", unsupported: "此浏览器不支持语音输入。", languageUnsupported: "当前学习语言暂不支持语音输入。", permission: "麦克风访问已被阻止。请在浏览器的网站权限中允许使用麦克风，然后重试。", noSpeech: "未检测到语音。请重试或输入答案。", audioCapture: "找不到麦克风。你仍可输入答案。", network: "语音识别无法连接。请重试或输入答案。", unknown: "语音识别未能完成。现有答案已保留。" },
  ja: { start: "答えを話す", stop: "聞き取りを停止", listening: "聞き取り中… 答えを話してください。", unsupported: "このブラウザは音声入力に対応していません。", languageUnsupported: "現在の学習言語では音声入力を利用できません。", permission: "マイクへのアクセスがブロックされています。ブラウザのサイト権限でマイクを許可してから、もう一度お試しください。", noSpeech: "音声を検出できませんでした。再試行するか、答えを入力してください。", audioCapture: "マイクが見つかりません。引き続き答えを入力できます。", network: "音声認識に接続できませんでした。再試行するか、答えを入力してください。", unknown: "音声認識を完了できませんでした。入力済みの答えは保持されています。" },
} as const satisfies Record<UiLocale, Record<string, string>>;

export type SpeechRecognitionMessageKey = "start" | "stop" | "listening" | "unsupported" | "languageUnsupported" | SpeechRecognitionErrorKind;
export const speechRecognitionT = (locale: UiLocale, key: SpeechRecognitionMessageKey) => messages[locale][key];
