import type { UiLocale } from "./types";

const en={translationOnly:"Translation only",lesson:"Lesson",translations:"Translations",targetLanguage:"Target language",translationFile:"Translation file",addTranslation:"Add translation",remove:"Remove",importTranslations:"Import translations",importing:"Importing…",translationImportSuccess:"Translations imported successfully.",selectLesson:"Select a lesson",expectedLines:"Expected {count} lines",matchesLines:"{count} lines — matches the lesson",blankLine:"Blank line at line {line}",lineMismatch:"Found {actual} lines; expected {expected}",invalidUtf8:"The file is not valid UTF-8.",duplicateLanguage:"Each target language may only be selected once.",missingFile:"Choose a UTF-8 TXT file.",loadLessonsFailed:"Could not load lessons."} as const;
export type TranslationImportKey=keyof typeof en;type Messages=Record<TranslationImportKey,string>;
const vi:Messages={translationOnly:"Chỉ nhập bản dịch",lesson:"Bài học",translations:"Các bản dịch",targetLanguage:"Ngôn ngữ đích",translationFile:"File bản dịch",addTranslation:"Thêm bản dịch",remove:"Xóa",importTranslations:"Nhập bản dịch",importing:"Đang nhập…",translationImportSuccess:"Đã nhập bản dịch thành công.",selectLesson:"Chọn một bài học",expectedLines:"Cần {count} dòng",matchesLines:"{count} dòng — khớp với bài học",blankLine:"Có dòng trống tại dòng {line}",lineMismatch:"Có {actual} dòng; cần {expected}",invalidUtf8:"File không phải UTF-8 hợp lệ.",duplicateLanguage:"Mỗi ngôn ngữ đích chỉ được chọn một lần.",missingFile:"Hãy chọn file TXT UTF-8.",loadLessonsFailed:"Không thể tải danh sách bài học."};
const zh:Messages={translationOnly:"仅导入翻译",lesson:"课程",translations:"翻译",targetLanguage:"目标语言",translationFile:"翻译文件",addTranslation:"添加翻译",remove:"移除",importTranslations:"导入翻译",importing:"正在导入…",translationImportSuccess:"翻译导入成功。",selectLesson:"选择课程",expectedLines:"需要 {count} 行",matchesLines:"{count} 行 — 与课程匹配",blankLine:"第 {line} 行为空",lineMismatch:"找到 {actual} 行；需要 {expected} 行",invalidUtf8:"文件不是有效的 UTF-8。",duplicateLanguage:"每种目标语言只能选择一次。",missingFile:"请选择 UTF-8 TXT 文件。",loadLessonsFailed:"无法加载课程。"};
const ja:Messages={translationOnly:"翻訳のみ",lesson:"レッスン",translations:"翻訳",targetLanguage:"対象言語",translationFile:"翻訳ファイル",addTranslation:"翻訳を追加",remove:"削除",importTranslations:"翻訳をインポート",importing:"インポート中…",translationImportSuccess:"翻訳をインポートしました。",selectLesson:"レッスンを選択",expectedLines:"{count}行必要です",matchesLines:"{count}行 — レッスンと一致",blankLine:"{line}行目が空です",lineMismatch:"{actual}行あります。{expected}行必要です",invalidUtf8:"有効なUTF-8ファイルではありません。",duplicateLanguage:"同じ対象言語は一度だけ選択できます。",missingFile:"UTF-8のTXTファイルを選択してください。",loadLessonsFailed:"レッスンを読み込めません。"};
const messages:Record<UiLocale,Messages>={vi,en,zh,ja};
export function translationImportT(locale:UiLocale,key:TranslationImportKey,values:Record<string,string|number>={}){return Object.entries(values).reduce((text,[name,value])=>text.replaceAll(`{${name}}`,String(value)),messages[locale][key]);}
