import type { UiLocale } from "./types";

const en={singleImport:"Single lesson",batchImport:"Batch import",importType:"Import type",chooseType:"Choose Audio or YouTube to continue.",audio:"Audio",youtube:"YouTube",lessonTitle:"Lesson title",lessonOrder:"Lesson order (01–99)",audioFile:"Audio file",youtubeUrl:"YouTube URL",srtFile:"SRT file",translations:"Optional translations",targetLanguage:"Target language",translationFile:"Translation TXT",addTranslation:"Add translation",remove:"Remove",validate:"Validate and preview",invalidYoutubeUrl:"Enter a supported HTTPS YouTube URL.",missingSource:"Choose the required lesson source and SRT file.",batchHint:"Use <name>.link.txt for YouTube or <name>.mp3 for audio and <name>.srt as the canonical timed transcript. Redundant .en.txt files are ignored."} as const;
export type YouTubeImportKey=keyof typeof en|"properNamesFile"|"properNamesConvention";type BaseKey=keyof typeof en;type Messages=Record<BaseKey,string>;
const vi:Messages={singleImport:"Một bài học",batchImport:"Nhập hàng loạt",importType:"Loại nhập",chooseType:"Chọn Audio hoặc YouTube để tiếp tục.",audio:"Audio",youtube:"YouTube",lessonTitle:"Tên bài học",lessonOrder:"Thứ tự bài (01–99)",audioFile:"File audio",youtubeUrl:"URL YouTube",srtFile:"File SRT",translations:"Bản dịch tùy chọn",targetLanguage:"Ngôn ngữ đích",translationFile:"File TXT bản dịch",addTranslation:"Thêm bản dịch",remove:"Xóa",validate:"Kiểm tra và xem trước",invalidYoutubeUrl:"Hãy nhập URL YouTube HTTPS được hỗ trợ.",missingSource:"Hãy chọn đủ nguồn bài học và file SRT.",batchHint:"Dùng <tên>.link.txt cho YouTube hoặc <tên>.mp3 cho audio; <tên>.srt là transcript có timestamp chuẩn. File .en.txt dư thừa sẽ được bỏ qua."};
const zh:Messages={singleImport:"单个课程",batchImport:"批量导入",importType:"导入类型",chooseType:"请选择 Audio 或 YouTube 以继续。",audio:"音频",youtube:"YouTube",lessonTitle:"课程标题",lessonOrder:"课程顺序（01–99）",audioFile:"音频文件",youtubeUrl:"YouTube URL",srtFile:"SRT 文件",translations:"可选翻译",targetLanguage:"目标语言",translationFile:"翻译 TXT",addTranslation:"添加翻译",remove:"移除",validate:"验证并预览",invalidYoutubeUrl:"请输入受支持的 HTTPS YouTube URL。",missingSource:"请选择所需的课程来源和 SRT 文件。",batchHint:"YouTube 分组使用 <名称>.link.txt + <名称>.srt，可选添加 <名称>.<语言>.txt。"};
const ja:Messages={singleImport:"単一レッスン",batchImport:"一括インポート",importType:"インポート種別",chooseType:"Audio または YouTube を選択してください。",audio:"音声",youtube:"YouTube",lessonTitle:"レッスン名",lessonOrder:"レッスン順（01–99）",audioFile:"音声ファイル",youtubeUrl:"YouTube URL",srtFile:"SRT ファイル",translations:"任意の翻訳",targetLanguage:"対象言語",translationFile:"翻訳 TXT",addTranslation:"翻訳を追加",remove:"削除",validate:"検証してプレビュー",invalidYoutubeUrl:"対応している HTTPS YouTube URL を入力してください。",missingSource:"必要なメディアと SRT ファイルを選択してください。",batchHint:"YouTube グループは <名前>.link.txt + <名前>.srt と任意の <名前>.<言語>.txt を使用します。"};
const messages:Record<UiLocale,Messages>={en,vi,zh,ja};
const properNamesFile:Record<UiLocale,string>={en:"Proper names JSON (optional)",vi:"File JSON danh từ riêng (tùy chọn)",zh:"专有名称 JSON（可选）",ja:"固有名詞 JSON（任意）"};
const properNamesConvention:Record<UiLocale,string>={en:"Optional proper names use <lesson>.name.json and reference parsed SRT sentence positions.",vi:"Danh từ riêng tùy chọn dùng <lesson>.name.json và tham chiếu vị trí câu SRT sau khi parse.",zh:"可选专有名称使用 <lesson>.name.json，并引用解析后的 SRT 句子位置。",ja:"任意の固有名詞は <lesson>.name.json を使用し、解析後の SRT 文位置を参照します。"};
const batchSourceHint:Record<UiLocale,string>={en:"Use <name>.link.txt for YouTube or <name>.mp3 for audio and <name>.srt as the canonical timed transcript. Redundant .en.txt files are ignored.",vi:"Dùng <tên>.link.txt cho YouTube hoặc <tên>.mp3 cho audio; <tên>.srt là transcript có timestamp chuẩn. File .en.txt dư thừa sẽ được bỏ qua.",zh:"YouTube 使用 <名称>.link.txt，音频使用 <名称>.mp3；<名称>.srt 是标准时间字幕，多余的 .en.txt 将被忽略。",ja:"YouTube は <名前>.link.txt、音声は <名前>.mp3 を使用し、<名前>.srt を正規の時間付き原文とします。余分な .en.txt は無視されます。"};
export function youtubeImportT(locale:UiLocale,key:YouTubeImportKey){return key==="properNamesFile"?properNamesFile[locale]:key==="properNamesConvention"?properNamesConvention[locale]:key==="batchHint"?batchSourceHint[locale]:messages[locale][key];}
