import type { UiLocale } from "./types";

const en={singleImport:"Single lesson",batchImport:"Batch import",importType:"Import type",chooseType:"Choose Audio or YouTube to continue.",audio:"Audio",youtube:"YouTube",lessonTitle:"Lesson title",lessonOrder:"Lesson order (01–99)",audioFile:"Audio file",youtubeUrl:"YouTube URL",srtFile:"SRT file",translations:"Optional translations",targetLanguage:"Target language",translationFile:"Translation TXT",addTranslation:"Add translation",remove:"Remove",validate:"Validate and preview",invalidYoutubeUrl:"Enter a supported HTTPS YouTube URL.",missingSource:"Choose the required lesson source and SRT file.",batchHint:"YouTube groups use <name>.link.txt + <name>.srt with optional <name>.<language>.txt files."} as const;
export type YouTubeImportKey=keyof typeof en;type Messages=Record<YouTubeImportKey,string>;
const vi:Messages={singleImport:"Một bài học",batchImport:"Nhập hàng loạt",importType:"Loại nhập",chooseType:"Chọn Audio hoặc YouTube để tiếp tục.",audio:"Audio",youtube:"YouTube",lessonTitle:"Tên bài học",lessonOrder:"Thứ tự bài (01–99)",audioFile:"File audio",youtubeUrl:"URL YouTube",srtFile:"File SRT",translations:"Bản dịch tùy chọn",targetLanguage:"Ngôn ngữ đích",translationFile:"File TXT bản dịch",addTranslation:"Thêm bản dịch",remove:"Xóa",validate:"Kiểm tra và xem trước",invalidYoutubeUrl:"Hãy nhập URL YouTube HTTPS được hỗ trợ.",missingSource:"Hãy chọn đủ nguồn bài học và file SRT.",batchHint:"Nhóm YouTube dùng <tên>.link.txt + <tên>.srt và các file <tên>.<ngôn-ngữ>.txt tùy chọn."};
const zh:Messages={singleImport:"单个课程",batchImport:"批量导入",importType:"导入类型",chooseType:"请选择 Audio 或 YouTube 以继续。",audio:"音频",youtube:"YouTube",lessonTitle:"课程标题",lessonOrder:"课程顺序（01–99）",audioFile:"音频文件",youtubeUrl:"YouTube URL",srtFile:"SRT 文件",translations:"可选翻译",targetLanguage:"目标语言",translationFile:"翻译 TXT",addTranslation:"添加翻译",remove:"移除",validate:"验证并预览",invalidYoutubeUrl:"请输入受支持的 HTTPS YouTube URL。",missingSource:"请选择所需的课程来源和 SRT 文件。",batchHint:"YouTube 分组使用 <名称>.link.txt + <名称>.srt，可选添加 <名称>.<语言>.txt。"};
const ja:Messages={singleImport:"単一レッスン",batchImport:"一括インポート",importType:"インポート種別",chooseType:"Audio または YouTube を選択してください。",audio:"音声",youtube:"YouTube",lessonTitle:"レッスン名",lessonOrder:"レッスン順（01–99）",audioFile:"音声ファイル",youtubeUrl:"YouTube URL",srtFile:"SRT ファイル",translations:"任意の翻訳",targetLanguage:"対象言語",translationFile:"翻訳 TXT",addTranslation:"翻訳を追加",remove:"削除",validate:"検証してプレビュー",invalidYoutubeUrl:"対応している HTTPS YouTube URL を入力してください。",missingSource:"必要なメディアと SRT ファイルを選択してください。",batchHint:"YouTube グループは <名前>.link.txt + <名前>.srt と任意の <名前>.<言語>.txt を使用します。"};
const messages:Record<UiLocale,Messages>={en,vi,zh,ja};
export function youtubeImportT(locale:UiLocale,key:YouTubeImportKey){return messages[locale][key];}
